### ISSUE TITLE
Can I haz spin plz ?

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#10]
@IceHacks Also good job would give money if I had

**Comment by IceHacks** [comment]
@TheSatanicAngeI Last time I remember seeing you, you were saying how you hated cheats and cheaters so no.

**Comment by IceHacks** [comment]
![image](https://user-images.githubusercontent.com/38994479/59464678-c897aa80-8dc4-11e9-8b16-1f1d8fee0de4.png)
As he removed all issues from his repo I can't read the whole thing but what I see is good enough.

**Comment by TheSatanicAngeI** [comment]
@IceHacks Fair enough...I just love spinning :joy:

**Comment by IceHacks** [comment]
Don't we all. Maybe I will release spin to the public. But I don't feel like spamming surviv with a bunch of spinning tryhard cheaters atm.

**Comment by IceHacks** [comment]
If you want updates, feel free to join the Discord server.

**Comment by TheSatanicAngeI** [comment]
@IceHacks Care to link me ? :+1:

**Comment by TheSatanicAngeI** [comment]
@IceHacks What about now ? :laughing: I had the chance to test it somehow between updates and it was AMAZING
