### ISSUE TITLE
game frequently freeze

### ISSUE THREAD

**Issue by 123wwa** [IceHacks/SurvivCheatInjector#104]
Game freezes after a few minute.

**Comment by 123wwa** [comment]
but It stops freeze when i off loothack Maybe because of loothack

**Comment by 0914461195tm** [comment]
I off all but it always freeze

Vào Th 7, 26 thg 10, 2019 vào lúc 19:03 123wwa <notifications@github.com>
đã viết:

**Comment by IceHacks** [comment]
Stop opening issues that already exist.
