### ISSUE TITLE
Surviv.io Holloween update

### ISSUE THREAD

**Issue by Reeyaad** [IceHacks/SurvivCheatInjector#106]
Surviv.io has updated just now and the new update of this cheat does not work on it.

**Comment by 1tarko** [comment]
Yep

**Comment by IceHacks** [comment]
Yep

**Comment by IceHacks** [comment]
ez fix

**Comment by zbot473** [comment]
it is known

**Comment by Arytor** [comment]
I'll wait for it. You'll have worked on it a lot today lol

**Comment by lol22233** [comment]
> ez fix

oh so just wanan ask hacks are getting fix today? or like tmrw and also there is a problem i tried to check lbs and its not loading ty!

**Comment by zbot473** [comment]
hacks fixed
