### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by BarneyFrendy** [IceHacks/SurvivCheatInjector#109]
The game can't load up.
![image](https://user-images.githubusercontent.com/57059328/67632003-f2e29400-f89d-11e9-8629-68f33d23e703.png)

**Comment by ALEXXANDRO23** [comment]
it's because the game has been updated :c

**Comment by BarneyFrendy** [comment]
> it's because the game has been updated :c

oh lol

**Comment by ay232** [comment]
The same problem ((

**Comment by MxrpLasHx9** [comment]
same.

**Comment by Reeyaad** [comment]
They are aware of it.

**Comment by ILOVECHEATING** [comment]
When they update the hack?

**Comment by SamMj2231** [comment]
its because of icehacks background picture

**Comment by Reeyaad** [comment]
They will update the hack whenever they want.

**Comment by zbot473** [comment]
Fixed
