### ISSUE TITLE
can't download latest file

### ISSUE THREAD

**Issue by gstrk** [IceHacks/SurvivCheatInjector#11]
It says virus detected and can't download

**Comment by IceHacks** [comment]
It's because the JS is obfuscated but I think `CTRL+J` does the trick

**Comment by vietguy64225** [comment]
what's the key to enable/disable autoloot?

**Comment by IceHacks** [comment]
There is no key just press "n" to open a menu of all options.

**Comment by gstrk** [comment]
ctrl+j just shows a list of all recent downloads and it says by latest.zip failed - virus detected. when I click the link to download it again, it fails again saying there is a virus detected.

**Comment by gstrk** [comment]
nevermind i just figured it out
