### ISSUE TITLE
I know this is a little bit too much to ask for but with the halloween hack that came out 2 hours ago, i freeze ingame with the hack on why is that?

### ISSUE THREAD

**Issue by prospecx** [IceHacks/SurvivCheatInjector#111]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by zbot473** [comment]
rip

**Comment by leoorantes08** [comment]
It freezes after playing sometime

**Comment by Roan3** [comment]
@zbot473 you are planing to do a uptdate of the hack.

**Comment by Roan3** [comment]
@zbot473 you are planing to do a uptdate of the hack?

**Comment by arsen1235456** [comment]
лаги не пдетски и зависает через 5минут

**Comment by zbot473** [comment]
yes I am going to fix
