### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by lfatal1ty** [IceHacks/SurvivCheatInjector#113]
After release (1.1.11) i play about 10 games, everything was perfect except picking up armor.

Now game freeze after about 30 sec from start.

**Comment by 1tarko** [comment]
looks like it freezes when the first kill in the game occurs

**Comment by sobol3d** [comment]
It does not occure with kiss, it just freeze in random moments, they devs must be looks close to Your patch and med the game to prevent this :( , hopes you will find the way to overrun them , Regards

**Comment by ay232** [comment]
it freezes after 2 - 3 minutes playing in haloween mode

**Comment by DNSGriff** [comment]
Same, Hack works but game freezes after about thirty seconds.
