### ISSUE TITLE
How to disable the annoying chrome message

### ISSUE THREAD

**Issue by Arytor** [IceHacks/SurvivCheatInjector#114]
I'll tell you how to disable the annoying chrome message "Disable developer mode extensions" every time you start chrome.

**Step 1**
- unzip the cheat to a folder

**Step 2**
- open chrome and go to chrome://extensions/

**Step 3**
- Click "Pack extension" and on "Extension root directory" Browse to the folder location then select it

**Step 4**
- Click "Pack extension", 2 files (a .crx and .pem) should've been created to the location where the folder was (not inside the folder)

**Step 5**
- drag the .crx file to  chrome on chrome://extensions/

**Step 6**
- Copy the ID of the extension and close chrome

**Step 7**
- Press Windows+R and type "gpedit.msc" (without the ") and hit Enter

**Step 8**
- Go to Computer Configuration>Administrative Templates>Google Chrome>Extensions

**Step 9**
- On the right tab, select "Configure extension installation whitelist" and Enable it if it is not already enabled

**Step 10**
- Click the Show button and on the blank space, paste the extension ID you copied earlier then press OK and Apply. You can then close gpedit

**Step 11**
- Open Chrome, wait for the popup notification to appear (this will only happen once, it'll not happen next times you open Chrome) then go to chrome://extensions/

**Step 12**
- Close the tab and you're done. You'll no longer have this message :D

**Comment by IceHacks** [comment]
Thanks, I forgot about this as I use Chrome Dev
