### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by lol22233** [IceHacks/SurvivCheatInjector#129]
the game keep freezing in the middle is this end of icehacks?

**Comment by TheSatanicAngeI** [comment]
@lol22233 RETARD LEARN TO FUCKING READ #125

**Comment by lol22233** [comment]
@TheSatanicAngeI RETARD wtf its saying? nothing its still freezing

**Comment by TheSatanicAngeI** [comment]
@lol22233 RETARD THAT THREAD EXIST TO STOP PEOPLE LIKE YOU MAKING STUPID DUPLICATED THREAD ABOUT THE SAME FUCKING ISSUES. 


SO LEARN HOW TO FUCK READ.  https://gyazo.com/05f2f1cb8037047a84ac4bfb41b057df

**Comment by lol22233** [comment]
@TheSatanicAngeI SO NIGGA EXACTLY what is wrong with making other isses?

**Comment by TheSatanicAngeI** [comment]
O MY FUCKING GOD

**Comment by TheSatanicAngeI** [comment]
@IceHacks

**Comment by lol22233** [comment]
AND I ASK YOU ITS END OF THE ICEHACKS IS DIFFERENT ISSUW RETARD

**Comment by TheSatanicAngeI** [comment]
"the game keep freezing in the middle is this end of icehacks?"

Yeah no I have totally no idea what that came to my mind *sarcasm*

**Comment by TheSatanicAngeI** [comment]
Its not a different issue retard. USE COMMON SENSE. If the cheat was going to be discontinued IceHacks would have said so.

**Comment by lol22233** [comment]
WHY THIS GAME FREEZING THO

**Comment by TheSatanicAngeI** [comment]
@lol22233 #125

**Comment by TheSatanicAngeI** [comment]
This is the thread to ASK for that question. Don't make duplicated thread when you can just post in #125

**Comment by lol22233** [comment]
@TheSatanicAngeI im sorry but i just joined this cov i dont understand :(

**Comment by TheSatanicAngeI** [comment]
@lol22233 Well sorry if I am rude af but I'm legit pissed of seeing every day hundred of threads of the same shit that probably discourage the developers and so on. 

This cheat was gave to us for FREE, the least we can do is RESPECT what the developers wants. Which is keeping the issues threads clean.

**Comment by lol22233** [comment]
@TheSatanicAngeI yeah sorry i understand now :D ill close this im sorry <3
