### ISSUE TITLE
Idea to add for aim on shoot

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#13]
When **shift** is hold aim on shoot is automatically disabled and when unhold it enable back.

This is to make looting easier when people are around

**Comment by IceHacks** [comment]
Ok

**Comment by RevoltZZ** [comment]
If you are going to add this, please make it possible to change the letter, to place a side mouse button, or another keyboard letter, Please.

**Comment by IceHacks** [comment]
@RevoltZZ You don't like shift?

**Comment by humphreygaming** [comment]
He probably uses shift for quick switching or something

**Comment by RevoltZZ** [comment]
No dude, it's because in the hack I was using the Kalaborative, I had to right-click and this was better for me, but if you can add this to the hack leave the option to change the key please leave the option use mouse button.

**Comment by RevoltZZ** [comment]
And yes, I use "shift" for quickswitch.

**Comment by IceHacks** [comment]
@RevoltZZ Aim on shoot is a separate option from the default right mouse.

**Comment by humphreygaming** [comment]
No further info, thread closed
