### ISSUE TITLE
end of hacks icehacks ;(?

### ISSUE THREAD

**Issue by lol22233** [IceHacks/SurvivCheatInjector#137]
i really want hacks and im seeing he haven't updated in like 3 days even tho he said he gonna update yesterday wtf going on im confused

**Comment by humphreygaming** [comment]
for now, icehacks is taken a break

**Comment by lol22233** [comment]
how long ;( @humphreygaming

**Comment by u1qqlv** [comment]
anti-cheat system very strong, surviv.io devs are very mad :)))

**Comment by lol22233** [comment]
@u1qqlv whats that

**Comment by HissingLambo500c** [comment]
Anti cheat system is a system most online games have to prevent mods like injectors and such

**Comment by leoorantes08** [comment]
i tried to talk with nick, he is not responding through linkedin

**Comment by sobol3d** [comment]
it is not end, icehack have school etc. he do not sit and make the hack all the time, sometimes you have to wait few hours, sometimes few days, just be patient, and try master your skill playing without it

**Comment by 123wwa** [comment]
Anyone who got banned? I was shocked that my main account got banned tho it has never been like this.

**Comment by XJayPlayzX** [comment]
![Screenshot 2019-11-04 at 8 13 59 AM](https://user-images.githubusercontent.com/56844356/68127689-ff896c80-fedb-11e9-81d2-8c1dd63fad86.png)

**Comment by XJayPlayzX** [comment]
got banned :/ how do i create a new account now?

**Comment by u1qqlv** [comment]
I had facebook linked account banned, and I created a new one linking my google/gmail account... do the same... use facebook or google

**Comment by IceHacks** [comment]
I'm not gone. I'm still here.

**Comment by anonymort** [comment]
For now everyone, if you go and delete the 'app-sid' cookie from the cookie data for surviv.io and play logged out, it doesn't seem to freeze.
