### ISSUE TITLE
Constant Freezing (Unplayable)

### ISSUE THREAD

**Issue by Bioniq12** [IceHacks/SurvivCheatInjector#139]
Every game you match up, it freezes after some while during the game

When the game freezes, you cannot do anything except to close down the tab.

The Freezing Issue makes the game literally unplayable, as winning a game is very rare, and is very frustrating when you have a really good start / Loot and then you end up freezing,

My guess is the Game's Anti-Cheat or something, Please update as soonest you can Ice Hacks, Thanks.

**Comment by IceHacks** [comment]
#134

**Comment by watertub18** [comment]
Is the freezing going to be fixed soon and is ice hacks still being updated>?
