### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by ItsJustDond** [IceHacks/SurvivCheatInjector#14]
Is there a discord server?

**Comment by gstrk** [comment]
I gochu homie https://discordapp.com/channels/576790905311330314/586473813353693214

**Comment by ItsJustDond** [comment]
That's not an invite...

**Comment by u1qqlv** [comment]
that's not icehacks official server, but it can be used as an non-official :D

**Comment by ItsJustDond** [comment]
I can't join a server with that type of link... I need a direct invite

**Comment by u1qqlv** [comment]
https://discord.gg/Fc6ddGX

**Comment by humphreygaming** [comment]
That's not the official server with REAL information, the official IceHacks server is this one: https://discordapp.com/invite/TaY5Esf (It has the Domino sponsored logo and the TM)

**Comment by GitHubFizz** [comment]
Hey everyone, for anyone wondering, im a irl friend of Humphrey, and this is our real server with instructions, and feel free to stay and chill there, and play some games with fellow hackers. https://discord.gg/bgXxQj2

**Comment by 123orb12** [comment]
all of them are invalid please send one that lasts forever
