### ISSUE TITLE
can you make it work on proxys

### ISSUE THREAD

**Issue by Themanicguy** [IceHacks/SurvivCheatInjector#141]
http;//ot38.club is the desired one

That would be cashmoneyAP of you

**Comment by IceHacks** [comment]
@Themanicguy Proxy support will the in the next version. Right now there is a workaround. Open `manifest.json` and replace all instances of
```js
"*://surviv.io/*",
```
with
```js
"*://surviv.io/*",
"*://ot38.club/*",
```
