### ISSUE TITLE
Alternative JavaScript File

### ISSUE THREAD

**Issue by Z4P3RM0nk** [IceHacks/SurvivCheatInjector#142]
The hack does seem immeasurable, however, it just won't work for me! After your hack didn't work I tried using different JavaScript files and they seemed to work better with Tampermonky. Since I'm so interested in testing your hack, I'm requesting that you add a .js script file for people that have a difficult time with the .zip file or just prefer to use a JavaScript in general. Thank you for your time!

**Comment by IceHacks** [comment]
@Z4P3RM0nk That's not how this works. It is not a UserScript (Tampermonkey) it is multiple `.js` files for a chrome extension. If you are having trouble installing I suggest you look at the guide provided and search up issues here.
