### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/SurvivCheatInjector#145]
![Screenshot 2019-11-15 at 11 47 50 PM](https://user-images.githubusercontent.com/35317687/68988264-8b679680-0802-11ea-93d3-8bfa26d8b87f.png)

**Comment by eimonpakzad** [comment]
I think it happens with the snipers

**Comment by watertub18** [comment]
yeah it happens underground too, my game usually freezes when it smooth too
