### ISSUE TITLE
Lag. This hack has very bad lags so it doesn't work what so ever when's the next update!

### ISSUE THREAD

**Issue by watertub18** [IceHacks/SurvivCheatInjector#146]

**Comment by zbot473** [comment]
system specs?

**Comment by watertub18** [comment]
i got a gaming pc bro it aint my pc whenever i turn off the hack my game is
chill

**Comment by TheSatanicAngeI** [comment]
@watertub18 Its your pc lmfao

**Comment by dinhanhx** [comment]
Or maybe even your internet connection to surviv.io sever?

**Comment by watertub18** [comment]
no its definitely the hack I can run triple-A games at least 160 fps

**Comment by watertub18** [comment]
Nah bro

**Comment by lilkaro** [comment]
mine is working perfectly fine

**Comment by watertub18** [comment]
didnt ask

**Comment by humphreygaming** [comment]
stupid flexer, no its not the hack, no the hack does not cause lag. Your "gaming" pc is probably the problem or the internet. Or your brain, whichever is bigger and has an actual function

**Comment by watertub18** [comment]
It is 100% the hack.

**Comment by IceHacks** [comment]
if you are using an expensive function it MIGHT lag but probs not. I said I'd be gone for a week.
