### ISSUE TITLE
Suggestion: TriggerBot functionality?

### ISSUE THREAD

**Issue by JaidenDestroyer** [IceHacks/SurvivCheatInjector#15]
A menu options to automatically shoot a player ONLY IF the cursor is on them, AND the shot is POSSIBLE, ie: direct path between path and enemy with NO solid obstacles (for example, glass would not count, while wooden walls would), AND the players clip is not empty. 

And, should this be made, the logic could be Incorporated into the Aimbot, forming a "aimbot-plus" like function.

**Comment by humphreygaming** [comment]
yes it is possible

**Comment by IceHacks** [comment]
@humphreygaming Yes it's possible but who really wants to do that much math :P

**Comment by humphreygaming** [comment]
You do, you said math is easy, you said anyone can get a good grade in math when I got an D+

**Comment by JaidenDestroyer** [comment]
kek, is there a place where i can find the source code for this project?

**Comment by humphreygaming** [comment]
I would recommend not trying to do de-obfuscate the code due to security purposes. But if Ice is ok with that then go ahead

**Comment by IceHacks** [comment]
@JaidenDestroyer I'm not stupid enough to do that

**Comment by IceHacks** [comment]
@humphreygaming He said source code, not the built code.

**Comment by JaidenDestroyer** [comment]
Er, alright. I suppose you would not want the code public so that it could not be patched out.

**Comment by IceHacks** [comment]
@JaidenDestroyer Exactly although I know their current patching methods I would not want them to develop a new one.

**Comment by IceHacks** [comment]
@JaidenDestroyer Also a few days ago I tested this feature out and it worked but sometimes it would be wrong and either not shoot when they are out in the open or shoot when they are behind something.

**Comment by JaidenDestroyer** [comment]
huh, are you using ray tracing? (or whatever it is called)

**Comment by IceHacks** [comment]
No, and from my understanding that is a feature for 3d rendering.

**Comment by JaidenDestroyer** [comment]
er, sorta. okay, basically a line from the center of **A** to the center of **B**, then checking if any **blocking materials** intersect this line (collision detection). If false: fire, else: nothing

**Comment by IceHacks** [comment]
@JaidenDestroyer If your good at math give me your discord and maybe you could help.

**Comment by JaidenDestroyer** [comment]
alright, @IceHacks, Discord: JaidenDestroyer#6248

**Comment by coolboy10121416** [comment]
hey everyone how is life

**Comment by humphreygaming** [comment]
I guess this concludes this thread
