### ISSUE TITLE
its starting to freeze again

### ISSUE THREAD

**Issue by StrappyOWO** [IceHacks/SurvivCheatInjector#155]
**Describe the bug**
freezing up
**Expected behavior**
for it too work with no freezes
**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by IceHacks** [comment]
#134 I'm on vacation and therefore can't update until Saturday

**Comment by watertub18** [comment]
ok enjoy ur vacation!

**Comment by RANATALHA1** [comment]
ok will it update sunday morning?
give me answer plz@icehacks
