### ISSUE TITLE
Aim Bot Request

### ISSUE THREAD

**Issue by BeRiBoY1433** [IceHacks/SurvivCheatInjector#165]
Could the aimbot not lock onto knocked down players,
because it locks onto them and while i'm killing them, their teammate kills me.
Could it just lock onto the alive players, like it used (a few updates ago)

**Comment by icehacksfanaa** [comment]
use ''mouse to aim'' and pls dont make other issues #134  @BeRiBoY1433 also hacks are borken how are u playing?

**Comment by HK1170** [comment]
i've always like aimbot at knocked down player, you know, you just knock them down, may as well kill them, quick and easy, or they'll revive. the actual flaw is aimbot always lock the closest one to you and that is not smart. let's play new version 2.0.0 and see if there is any problem

**Comment by HK1170** [comment]
let's wait to play 2.0.0 first
