### ISSUE TITLE
Freezing :/

### ISSUE THREAD

**Issue by StrappyYE** [IceHacks/SurvivCheatInjector#166]
**Describe the bug**
Freezing when im playing
**Expected behavior**
For it not to freeze
**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by HK1170** [comment]
really ? you posted this, on a new thread ? anyway just wait for a day or two there will be a brand new version.

**Comment by u1qqlv** [comment]
give you a link might help - https://github.com/u1qqlv/SURVIV.IO-PRO-HACK

**Comment by niek-gamer** [comment]
some of the hacks make the hack freeze for example the auto shoot
