### ISSUE TITLE
Feature - Scroll Zoom

### ISSUE THREAD

**Issue by ScripterLima** [IceHacks/SurvivCheatInjector#167]
Add the usual Left Shift + Scroll to zoom in and out ik its a shitty idea
![Screenshot (84)](https://user-images.githubusercontent.com/57508046/69558653-95159a80-0f76-11ea-9518-6efe4040a0d9.png)

**Comment by u1qqlv** [comment]
I think it is form my hack, please use that hack page for support

**Comment by lollol10ki** [comment]
> I think it is from my hack, please use that hack page for support

ok so i used ur hack as a example sorry if i made u mad

**Comment by IceHacks** [comment]
I lack motivation to re-add it.

**Comment by RANATALHA1** [comment]
@IceHacks when you release chaet?

**Comment by icehacksfanaa** [comment]
@IceHacks how do we turn off enemny names?

**Comment by Awesomecow67** [comment]
I liked the Left shift + Scroll Zoom thing

**Comment by BurningSnowYT** [comment]
*PLZ DONT MARK AS OFF TOPIC I NEED HELP*

With spin bot enabled, what do u press to turn it off when u need to wack creates?
