### ISSUE TITLE
escape key menu issue 

### ISSUE THREAD

**Issue by Awesomecow67** [IceHacks/SurvivCheatInjector#169]
when you try to change your settings ingame, the new thing where you press escape to open the menu opens the menu, but also opens the normal non-hack window that opens when you press escape ingame so please change the menu key back to n :)

**Comment by icehacksfanaa** [comment]
please join discord stop making issue

**Comment by icehacksfanaa** [comment]
#134

**Comment by IceHacks** [comment]
@Awesomecow67 That is on purpose.
