### ISSUE TITLE
(Please Fix)

### ISSUE THREAD

**Issue by IceHacksFan** [IceHacks/SurvivCheatInjector#17]
Hi i have this issue for a week, pretty much i will go onto surviv.io . But once i press (Solo,Duo,Squads) my screen goes black for about 3seconds and then my game looks like this
![Capture](https://user-images.githubusercontent.com/52057426/59892139-4d18a780-941b-11e9-8136-eec7f84950a5.PNG)
if you can fix this it would be great :)

**Comment by IceHacks** [comment]
@IceHacksFan Try redownloading and make sure that the twitch streamers thing shows on surviv.io.

**Comment by IceHacksFan** [comment]
> @IceHacksFan Try redownloading and make sure that the twitch streamers thing shows on surviv.io.

ok ill try now. is there anyway i can get spinbot i can contact u on discord and u can send the download link with spinbot thanks - regards AIDEN

**Comment by humphreygaming** [comment]
@IceHacksFan Yes, you can buy the plugin for spinbot by contacting Nah B#8258 and asking for the selly.gg link or joining the official discord server @https://discord.gg/TaY5Esf

**Comment by IceHacksFan** [comment]
closed
