### ISSUE TITLE
Feature - Binds

### ISSUE THREAD

**Issue by HK1170** [IceHacks/SurvivCheatInjector#171]
aimbot: need alternative for [rmb aim] (right mouse+left mouse). last update i use this : [left shift+left mouse] customizable to that and it felt easier

last update have this crazy deathly feature: auto everything that enabled [impersonate mobile player] and [auto attack] bind auto every thing to (a button) and you will totally automatic spin around and punching enemy to death. maybe add again ? thank you IceHacks very much !

**Comment by HK1170** [comment]
also, i figured out to bind emo to something else

**Comment by IceHacks** [comment]
Auto attack is in this version... I'll see to adding mobile movement back

**Comment by maryopenass** [comment]
I want the full version soon, I hope sailing

**Comment by u1qqlv** [comment]
why left mouse + right mouse buttons instead of "shoot on click"?

**Comment by IceHacks** [comment]
some people like it that way

**Comment by Mxcc07one** [comment]
@IceHacks add  lerp,speed lerp,speed multiplier and aim in knockout

**Comment by RANATALHA1** [comment]
@IceHacks plz add auto attack distance plz plz plz plz

**Comment by RANATALHA1** [comment]
![addd](https://user-images.githubusercontent.com/51949345/70420646-003c9200-1a8a-11ea-9b12-315334094f79.PNG)
addd this plz plz [lz

**Comment by RANATALHA1** [comment]
and
![newadd](https://user-images.githubusercontent.com/51949345/70420698-164a5280-1a8a-11ea-86b5-0e5758caf43e.PNG) plz also add this

**Comment by RANATALHA1** [comment]
plz plz plz ice hacks

**Comment by IceHacks** [comment]
Please open new issues instead of commenting on other issues. I'm more likely to see a new issue than check on an old one.

**Comment by IceHacks** [comment]
test

**Comment by TheSatanicAngeI** [comment]
@IceHacks I still freeze guess your hack is just too cold.

**Comment by BobbyTheDev** [comment]
@TheSatanicAngeI, Please do not post hate or anything rude here. If you have an issue please create a new issue, thanks!

**Comment by IceHacks** [comment]
@TheSatanicAngeI Do you have autoloot enabled?
