### ISSUE TITLE
how bumpfire works

### ISSUE THREAD

**Issue by muWander** [IceHacks/SurvivCheatInjector#173]

**Comment by BurningSnowYT** [comment]
PLZ DONT MARK AS OFF TOPIC I NEED HELP

With spin bot enabled, what do u press to turn it off when u need to wack creates?

**Comment by icehacksfanaa** [comment]
@IceHacks is there anyway u can hide icehacks logo and put surviv logo after games end?

**Comment by IceHacks** [comment]
@BurningSnowYT There is not, I forgot to add that feature. @muWander please describe what you want.
