### ISSUE TITLE
The LEGIT MODE doesn't work

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/SurvivCheatInjector#174]
![Screenshot 2019-12-01 at 10 59 58 AM](https://user-images.githubusercontent.com/35317687/69916514-cc2df500-1429-11ea-8361-059a45920f60.png)

**Comment by humphreygaming** [comment]
i honestly can't believe you guys fall for such things, smh. Honestly, if we announced a gun spawner update and released a fake version you guys would fall for it

**Comment by eliteog23** [comment]
lmfaooo I knew it

**Comment by StabbyAlbert** [comment]
cheat is optional

**Comment by zbot473** [comment]
bruh who told you this
