### ISSUE TITLE
A lot of lag

### ISSUE THREAD

**Issue by JaxKazuto** [IceHacks/SurvivCheatInjector#175]
**Describe the bug**
Well recently when using the hacks the game has gotten very laggy the game was working fine with it for the first few days now its all messed up I tried the game without the hack and there are no lags

**Expected behavior**
I dont know man I just dont want it to lag XD 

**Screenshots**
-Impossible to screenshot lags-

**Version**
Latest (Dec 2nd 2019)

**Comment by DNSGriff** [comment]
I have had this problem also with the large amounts of lag

**Comment by IceHacks** [comment]
I'll check it out. However refreshing usually works.
