### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by aopsmathguy** [IceHacks/SurvivCheatInjector#178]
**Describe the bug**
Da hax don't work because there is a spinning circle and the battle passes don't load and i can't play

**Expected behavior**
every time hacks are on an no times hacks are off

**Version**
2.0.0

**Comment by zbot473** [comment]
console screenshot

**Comment by IceHacks** [comment]
@zbot473 I doubt it would be in the console as no one else has this issue and the cheat is cross-platform. @aopsmathguy what's your chrome version? Try re-installing.

**Comment by aopsmathguy** [comment]
Sorry i made a stupid mistake and used an archive.

**Comment by zbot473** [comment]
@aopsmathguy which class on aops u taking rn

**Comment by aopsmathguy** [comment]
woot and physwoot
