### ISSUE TITLE
ADD ICE PLS

### ISSUE THREAD

**Issue by maryopenass** [IceHacks/SurvivCheatInjector#179]
Icehacks,add lerp,speed lerp,speed multiplier and aim in knockout pls u are icehacks,can you please?

**Comment by icehacksfanaa** [comment]
pls stop making issues join icehacks discord it would be more easy please!

**Comment by IceHacks** [comment]
You have asked this already many times, as I have said: I have those features in test version it is only a matter of time before I release.
