### ISSUE TITLE
Icehacks my dude new issue

### ISSUE THREAD

**Issue by IceHacksFan** [IceHacks/SurvivCheatInjector#18]
i redownloaded the latest one , havent got black screen or messed up page but about 2sec after im in a game it will say Aw Snap

**Comment by u1qqlv** [comment]
try ctrl + f5 XD

**Comment by humphreygaming** [comment]
try what alexv said which is clearing the cache. If it still does not work, try downloading a previous version of the hack


_Thread will be closed after 3 days of inactivity_

**Comment by IceHacks** [comment]
@IceHacksFan Show me PC specs the cheat works fine for everyone else.

**Comment by IceHacksFan** [comment]
CLOESD
