### ISSUE TITLE
Spinbot Feature 

### ISSUE THREAD

**Issue by ScripterLima** [IceHacks/SurvivCheatInjector#180]
can ya add a button to stop the spin bot so i can open sum boxes lmao gg on this cheat m8 ur doing well

**Comment by IceHacks** [comment]
ok

**Comment by zbot473** [comment]
Tbh a temp unbind for all is good

**Comment by IceHacks** [comment]
@ScripterLima turning on aim at objects fixes, but if you don't want to do that I can still reopen this and add it later.
