### ISSUE TITLE
Some new buttons 

### ISSUE THREAD

**Issue by SwitchMe33** [IceHacks/SurvivCheatInjector#183]
Why did you bring the "ice hacks' smoke back?  It looked fine with the original smoke...
is there any possible way that you could just add a button if someone wants see through smoke, they can just click a button for it and actually make the smoke just like the original for those that like playing it just for the aimbot and auto looting!  That is only reason I use the cheat! and sometimes I just have auto loot on and aimbot off, but don't like the ice hacks smoke...  :( its a turn off :(  Wish there was just a aimbot and auto loot cheat only!

**Comment by icehacksfanaa** [comment]
FUCK OFF icehacks deserve the credit

**Comment by SwitchMe33** [comment]
> FUCK OFF icehacks deserve the credit

This has nothing to do with the credit... He is a good creator no doubt, but your reply was uncalled for!  How about you say that to my face?  Idiot

**Comment by SwitchMe33** [comment]
How about I report him and this to surviv.io each and every time he updates?!?!? 

Bet yall wouldnt like that, so how about you keep your opinions to yourself for now on!

**Comment by humphreygaming** [comment]
The icehacks smoke is for licence/watermark reasons. Its very easy to pass the hack as your own if you don't have the smoke watermark

**Comment by IceHacks** [comment]
@SwitchMe33 you have never given a reason to remove it other than you don't like it. You should see that adding options to remove watermarks makes the watermarks pointless.

**Comment by SwitchMe33** [comment]
Well you actually removed it last time, and I was able to update the file with a legit looking smoke png, then you change the file system, which I have no clue about.  Why have invisible smoke, when you have a aimbot?!??!  Can't you put your watermark elsewhere instead on the smoke?   You have a huge watermark in the left corner ... I just never understood why you creators wanna make a aimbot everyone can use with watermarks that "surviv mods" can see when they team with you!  You are pretty much getting people banned across the game with watermarks... maybe you work for surviv and that is the reason why you created this aimbot...
