### ISSUE TITLE
Surviv.io now stopping people using SurvivCheatInjector by closing host

### ISSUE THREAD

**Issue by dinhanhx** [IceHacks/SurvivCheatInjector#184]
Like the title at about 5:45 pm GMT+7, when I was using the tool, each match, for about 5 seconds to 30 seconds, the match stopped and shown "Host closed"

**Comment by u1qqlv** [comment]
I can not replicate

**Comment by dinhanhx** [comment]
Sorry guys. It was my internet connection.
