### ISSUE TITLE
Tutorial - How to be deadly

### ISSUE THREAD

**Issue by HK1170** [IceHacks/SurvivCheatInjector#186]
I play in the Asia server and sometimes another cheater uses a more deadly configuration of their cheat and they kill me. I hadn't configured mine to be that deadly until I saw what they were using. Now I have configured my version to be better than theirs.

Although this may not look deadly at first, when you try it yourself and confront an enemy you simply move to them and hold down the fire button (not even clicking it!) and they will die.

- Use two SniperSwitch weapons (ex: SPAS+Mosin)
- Turn AimBot on
  - Set the type to "on shoot"
  - Set AutoAttack to true
- Turn AutoLoot on
- Turn BumpFire on
- Turn ESP on
- Turn Transparency on
- Everything else can be off or on, it's up to you.

Some other things you should know:

A question I asked in a [previous issue](https://github.com/IceHacks/SurvivCheatInjector/issues/138) was answered to help me make this, I'm beyond satisfied with that. And if you wish to view stats simply disable the extension first (IceHacks will fix this issue) or use a proxy (like http://ot38.club/stats/)

Rewritten for clarity by IceHacks.

Note from IceHacks:
> I love seeing people configure the cheat (that's why I made an options menu lol) I get a lot of questions about the best configuration although typically that is subjective, in this case it is just a really great configuration.

**Comment by humphreygaming** [comment]
If you play on Asia server, you might get a chance to do a hacker 1v1 against Hack R&D Dog

**Comment by RANATALHA1** [comment]
plz plz @humphreygaming give us best hacker setting plz plz bro
god bless you

**Comment by RANATALHA1** [comment]
my hacker setting is
![settting gpg](https://user-images.githubusercontent.com/51949345/71306782-af705600-2406-11ea-87fb-a41fbdd3fffe.PNG)
![settting](https://user-images.githubusercontent.com/51949345/71306783-b008ec80-2406-11ea-96b8-c24a35f46baa.PNG)

**Comment by RANATALHA1** [comment]
give me best setting plz
an tips to use this hacks @IceHacks @humphreygaming 
my highest kill 16 thats very low kill plz plz help
and tell me when next version update?

**Comment by RANATALHA1** [comment]
iam also from asia

**Comment by humphreygaming** [comment]
at this point, i'm not going to even respond to this. It is such a foolish question. Maybe i need to bold it.
**THERE IS NO, I REPEAT, NO BEST HACK SETTING. IT IS ONLY BASED ON USER EXPERIENCE AND IMPUT. IF YOU ALREADY HAVE SOME DECENT SETTINGS BUT YOU SUCK ASS (which i bet you do) THEN NO SETTINGS WILL GET YOU HIGH KILLS**. It is just impossible. I don't know if you are stupid or retarded or something, but stop asking such stupid questions and spamming them.

**Comment by RANATALHA1** [comment]
plz show me your hack setting

**Comment by RANATALHA1** [comment]
iam sure your setting is defrent but you not show me your real setting
plz plz plz bro
