### ISSUE TITLE
Freezing> ;(

### ISSUE THREAD

**Issue by eliteog23** [IceHacks/SurvivCheatInjector#187]
**Describe the bug**
(The hack is freezing midgame, some games freeze, some games no freeze. If I did a test, 7/10 freeze :(

**Expected behavior**
(No freeze?)

**Screenshots**
(Can't really ss a "frozen screen" 

**Cheat version**
(v2.0.1)
**Chromium version**
dunno "_"

**Comment by HK1170** [comment]
unrelated to this thread minor bug: red container visually disappear
![eeeeeeeeeeeeeeeeeeeeeee](https://user-images.githubusercontent.com/57206034/70777965-13b66880-1dbc-11ea-9820-9803a55b511e.png)

**Comment by dinhanhx** [comment]
You are not the only one.
Cheat version
(v2.0.1)
Latest Microsoft Edge Dev version

**Comment by HK1170** [comment]
did you go on a rampage with bump fire ? i freeze once doing that with this version, and i freeze a lot doing that with older 1.x version

**Comment by humphreygaming** [comment]
will see/try to verify. If it doesn't happen, its your internet

**Comment by StabbyAlbert** [comment]
It shouldn't be, try leaving it on default settings. I only change to aim at downed and aim on shoot

**Comment by IceHacks** [comment]
@eliteog23 what do you have enabled? Bump fire may cause freeze if some other options are off.

**Comment by IceHacks** [comment]
The following settings will probably make it freeze:

- Autoloot off
- Bumpfire on

If you use bumpfire also use autoloot or risk freezing. In-game you can see bumpfire has a freeze warning on it. I'll wait for your response before closing this issue.

![image](https://user-images.githubusercontent.com/38994479/70826346-c40b7900-1d8a-11ea-8408-133ae742fde8.png)

**Comment by IceHacks** [comment]
I waited long enough lol.

**Comment by eliteog23** [comment]
Oh shit im sorry

**Comment by IceHacks** [comment]
np

**Comment by eliteog23** [comment]
I forgot to check my email bro lol

**Comment by eliteog23** [comment]
The problem is definitely not my wifi, I have insane wifi speeds, up to 1GB per sec. Also I use aim on RMB

**Comment by IceHacks** [comment]
But, do you have Autoloot off and Bumpfire on?

**Comment by eliteog23** [comment]
Yes

**Comment by eliteog23** [comment]
Autoloot messes me up

**Comment by eliteog23** [comment]
Bumpfire is when you hold down and it spams the punch right?

**Comment by IceHacks** [comment]
Well, @eliteog23 this autoloot is very good and having that off and bumpfire on will cause freeze. There is no fix.

**Comment by eliteog23** [comment]
Ah. Do you know why having autoloot off causes this issue?

**Comment by IceHacks** [comment]
Yes

**Comment by eliteog23** [comment]
? :)

**Comment by zbot473** [comment]
Both on has no freeze for me

**Comment by IceHacks** [comment]
@zbot473 yup it won't freeze like that unless they update. Which is what I said. He was autoloot off. If you have autoloot off you must also have bumpfire off.
