### ISSUE TITLE
Feature - Aim at downed, only when there are not any live players.

### ISSUE THREAD

**Issue by justiceowens2001** [IceHacks/SurvivCheatInjector#193]
An option to only aim at downed once there are no more live players to shoot.

**Comment by Reeyaad** [comment]
jUST DISABLE THE AIM AT DOWNED......... EASY FIX

**Comment by Reeyaad** [comment]
tHANKS TO iCEhACKS ;)
![image](https://user-images.githubusercontent.com/20893493/70912655-9ea69580-203e-11ea-9c48-d369799c3b21.png)

**Comment by RANATALHA1** [comment]
bro iam banned

**Comment by RANATALHA1** [comment]
plz give me best setting of this hack

**Comment by justiceowens2001** [comment]
> tHANKS TO iCEhACKS ;)
> ![image](https://user-images.githubusercontent.com/20893493/70912655-9ea69580-203e-11ea-9c48-d369799c3b21.png)

![image](https://user-images.githubusercontent.com/58893681/71200570-22ce6800-224d-11ea-803a-b13e48f45acb.png)

**Comment by IceHacks** [comment]
Possible but requires changing the whole aimbot structure.
