### ISSUE TITLE
Aimbot easy toggle switch

### ISSUE THREAD

**Issue by justiceowens2001** [IceHacks/SurvivCheatInjector#194]
It would be really great to have a hotkey to toggle aimbot on and off, for example right shift. It could still incorporate the option to aim on shoot, or not. Basically an option to play without aimbot then turn it on at will to destroy some players. 
Whatever key it was that would change it, it would need to be easy to quickly change in game.

**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IceHacks** [comment]
there is the right mouse hold

**Comment by justiceowens2001** [comment]
Right mouse is great, but im playing on a trackpad, so in order to right click its two finger touch.

**Comment by IceHacks** [comment]
![image](https://user-images.githubusercontent.com/38994479/70855763-50de3180-1e74-11ea-99d7-92293d32441e.png)
this is in 2.0.2

**Comment by justiceowens2001** [comment]
Oh sweet.
