### ISSUE TITLE
when i ever i load the unpacked extension a message pops up and says: "Failed to load extension" and its annoying someone plz help 

### ISSUE THREAD

**Issue by mynamejoejeff** [IceHacks/SurvivCheatInjector#195]
![Screen Shot 2019-12-14 at 10 15 58 PM](https://user-images.githubusercontent.com/58896810/70857578-50b75380-1ebf-11ea-8058-8d5699964382.png)

**Comment by IceHacks** [comment]
If you read the README.md/install instructions file you will see how to fix this.
