### ISSUE TITLE
Feature - Map Tooltips Toggle

### ISSUE THREAD

**Issue by xWintertime** [IceHacks/SurvivCheatInjector#197]
Shows a small tooltip for the puzzles on the map based on where you find them. Good for new players to understand how to access hidden items or sectors that they didn't know before. You may also make a repository that explains every known map puzzle so players can look back upon the user interface.

**Comment by IceHacks** [comment]
adding tooltips to the map is too much work for something so little imo.

**Comment by zbot473** [comment]
Possibly just a floating box

**Comment by IceHacks** [comment]
I will reopen if more people think this is a good idea. Right now I don't feel like implementing.
