### ISSUE TITLE
Feature - Weapon Ranking ESP

### ISSUE THREAD

**Issue by xWintertime** [IceHacks/SurvivCheatInjector#199]
Weapon tooltip will show Damage, Fire rate, DPS, and Capacity for each weapon upon equip. (Wiki)
Will show relative difference between equipped weapon and weapon on the ground for reference.
Have a tier list repository based on drop rate, etc, the general consensus from players in an user interface.

Will show enemies currently equipped weapon and their Armor + Helmet Level above their names. Toggleable On/Off.

**Comment by humphreygaming** [comment]
Will consider...

**Comment by IceHacks** [comment]
Yeah. But the wiki is dumb, just get it from the game.

**Comment by RANATALHA1** [comment]
plz give me best setting of this hack 
@humphreygaming

**Comment by humphreygaming** [comment]
@RANATALHA1 There is NO best setting, it's up to you to figure that kind of stuff out by experimenting with it

**Comment by IceHacks** [comment]
not for this update.
