### ISSUE TITLE
Great Suggestion :)

### ISSUE THREAD

**Issue by IceHacksFan** [IceHacks/SurvivCheatInjector#20]
Add Option - so lets say a team of 3 comes at u, make the Aimbot/AimOnShoot to target the lowest heath player :) 

just thought i would be qucker to kill the lowest heath playyer - REGARDS AIDEN

**Comment by JaidenDestroyer** [comment]
As far as i know, enemies health are unknown, i might be wrong though.

**Comment by IceHacks** [comment]
@JaidenDestroyer is right. The only way to find their health is to assume they have full health and then subtract bullet damage which would always be wrong. @IceHacksFan
