### ISSUE TITLE
maybe don't use bump fire in 50v50 (freeze proof) (i'm still testing, doesn't freeze a single time)

### ISSUE THREAD

**Issue by HK1170** [IceHacks/SurvivCheatInjector#200]
(i don't even know if this is even a issue, but i have made a mess of words and "( )" haha) (IceHacks said and you should follow: don't use bumpfire without also enable autoloot) so, because in 50v50 you infict a whole lot of damage and if with bump fire it may cause freeze, i'm just a normal player and still testing and can't get it to freeze. (ya dont wanna freeze while being a commander) (actually this is an use it don't floor it scenario) this is base on experience with freeze in 50v50 2 months ago using version 1.2.2 or something like that: every time i become a sergeant or marksman (no more sergeant in this new 50v50) in 50v50 and given a semi-auto weapon (also applied if you are a no perk player and just pick up any semi-auto) and i use it with bump fire and make a whole lot of damage i will freeze, *every single time*. this time though i can't confirm because i'm don't want a ban. although i believe that is still true. so uh, you can test or just don't bump fire semi-auto

**Comment by HK1170** [comment]
this version 2.0.1 is really great, you can use every setting but bump fire (don't use in 50v50, normal game is fine, i use a little in normal game all the time, no freeze) and have a lot of convenience and a lot of minor annoying bugs fixed

**Comment by humphreygaming** [comment]
thx for this, will investigate and see if it can be fixed in 2.2

**Comment by HK1170** [comment]
the always freeze in the last 50v50 a few months ago i never use auto loot, back then i don't know bump fire was causing freeze, so i thought it was auto loot that was causing freeze. so i guess i freeze back then because i didn't use autoloot, IceHacks said in issue 187 if only 1 of the 2 (autoloot, bumpfire) enable it will probaly freeze. i was testing too, both autoloot and bumpfire on, can't get it too freeze lmao (hey surviv dev don't mad !)

**Comment by HK1170** [comment]
this entire create issue section must have act as a double blade, definitely add stuff to surviv dev's to do list too. XD

**Comment by Reeyaad** [comment]
MY PERSONAL BEST ON 50V50 USING THE ICEHACKS 
![image](https://user-images.githubusercontent.com/20893493/70912513-496a8400-203e-11ea-9f02-00c486cae6ba.png)

**Comment by HK1170** [comment]
i think i should close this

**Comment by zbot473** [comment]
You either need Bump on or both off. We basically simulate a mobile player, so autoloot without mobile player = freeze

**Comment by watertub18** [comment]
i was banned, i can still play but my account has been deleted
