### ISSUE TITLE
You could be banned

### ISSUE THREAD

**Issue by TheGuardian226** [IceHacks/SurvivCheatInjector#202]
Just a note for everyone using this; surviv has begun properly using their anti-cheat in order to identify hackers using accounts. Instead of the old "freeze-game" trick, they have begun banning accounts.

Not exactly sure if there is a reporting system, or whether the anti-cheat just looks for aim-locks, but for the good of your account, be careful!

**Comment by IceHacks** [comment]
No doubt the anticheat is looking for something, and I think I know what. I doubt it's aim-locks. Not everyone has been banned, which is good. I'm not a big supporter of cheating on accounts or trying to conceal cheats. I like trolling. So if you do get banned don't expect sympathy from me.
