### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#207]
I was banned lmao, help me get back on. Send me an invite @HumphreyGaming#5951

**Comment by MrRobotSurviv** [comment]
Where is the new serv? Im french baguette

**Comment by MrRobotSurviv** [comment]
https://discord.gg/Gr7UGv

**Comment by BobbyTheDev** [comment]
server got deleted bro, everyone was banned.

**Comment by IceHacks** [comment]
He means his account on Discord was deleted. And he made a new one. He was the server owner.

**Comment by IceHacks** [comment]
@BobbyTheDev he means his discord account got deleted.
