### ISSUE TITLE
Please Help im confused bro

### ISSUE THREAD

**Issue by IceHacksFan** [IceHacks/SurvivCheatInjector#21]
in the Readme.mt u have a Section that says Premuim, can i get premuim is it paid / do u need my discord - just a little confuseed :))

**Comment by IceHacks** [comment]
I know little to nothing about how the premium version gets' distributed and my part of the deal is that if the ones selling it don't bother me they can sell it. So you will have to ask them. 

Have a nice day.

FYI: spinbot only rapidly (or slowly) spins the player. Not changing any hitboxes or anything.

**Comment by IceHacksFan** [comment]
who do i ask?

**Comment by IceHacksFan** [comment]
So spinbot spins you Slow/Fast until sees somone then stops then i kill them and it starts agian?

**Comment by IceHacks** [comment]
@IceHacksFan That's how it would act if you used autoaim. I recommend "aim on shoot" or the defaults for the best experience.
