### ISSUE TITLE
NOT AN ISSUE (but read please lol)

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#210]
### I JUST WANNA SAY THANKS TO @IceHacks AND @humphreygaming FOR EVERYTHING 🎊 

1. You guys are awesome [✔️]
2. You guys kept updating this hack and improving it [✔️] 
3. You guys spent time and effort despite this hack being free [✔️]
4. You guys were open-minded to problems occuring and kept working even if people were toxic and annoying about it taking it for granted etc [✔️]

Now i have an idea that may help a lot of people or useless threads/reply been noticed for FAQ. 

Just make an official FAQ thread and redirect people to them for common issues. 

Also a guide that explain how things works or what things are. 

For instance I have no fucking clue what "Aim FOV" is nor do I know what "LegitMode™️" is supposed to be/do. 

Because I remember a time when you were able to hover your mouse on the settings and a bubble of text would appear telling you more informations about it.

**Comment by IceHacks** [comment]
Thanks.

We do have a readme with a basic FAQ but people seem to ignore this. For a guide explaining stuff and the hovering to get a description I just have little patience to add these to the many features we have c:

Aim FOV: it's the aimbot field of view to restrict the angle between mouse and enemy.
LegitMode™: smooths the back to mouse after aiming for more realism.

I'll see about maybe making a guide. Thanks for the support!

**Comment by WinterManTM** [comment]
Thats Nice :)

**Comment by humphreygaming** [comment]
haha, thx SatanicAngel

**Comment by TheSatanicAngeI** [comment]
`INFO ABOUT THE HACK (NOT OFFICIAL TEMPLATE)`
**Type:** _Auto aim at nearest ennemie / Aim when triggering the shoot key /Inverted (?)_
**Use Collisions:** _Don't aim at people inside buildings or lower levels (I think)_
**Aim with mouse:** _My favorite feature, aim with RMB_
**AutoAttack™️:** _Also known as Auto loot shh dont tell anyone. Automatically attack ennemies using guns or melee_
**AutoShoot™️:** _Tired of actually doing stuff in the game ? Now when you see an ennemie you shoot it without even thinking about it 😄_
**Aim at downed:** _Are you tired of doing SQUAD SOLO and being killed because the team ennemie keeps guarding and reviving their mates ? Now you can be an asshole and aim at the one who can't defend themselves!_
**Aim at objects:** _You can now look smart by shooting perfectly boxes and barrels etc._
**Mobile Movement™️:** _This is basically almost any .io games feature also why the hell does it exist? 
You move the direction your mouse is pointing_
**Legit Mode™️:** _smooths the back to mouse after aiming for more realism._
**Aim FOV:** _it's the aimbot field of view to restrict the angle between mouse and _enemy._
**Velocity Multi:** _Uhh help? 🤣 I'm assuming it has something to do with the smoothness in which you follow ennemie while aiming_
**Auto loot/doors:** _Do I seriously have to explain this?_
**Auto Switch™️:** _Play style that pros do for snipers and close/far range weapons. Switch weapon after you shoot._
**Binds:** _This is new and uhhh pretty sure it is self explanatory. You put a key that enable/disable a feature in the hack._
**Bumpfire:** _The curse of every great cheat developers on surviv.io this feature is highly requested but it also comes with freezing. Allows you to spam bullets on weapons that can't usually do it. Basically shooting as soon as it is physically possible. (I think)_
**Dark Theme:** _All the 😎 kids use it! FAQ : Disable it if you wanna do duo/squad_
**ESP:** _Pretty sure it has something to do with knowing the radius of grenades and barels and also where ennemies are._
**Grenade Timer:** _This feature prevents you from committing Allah Akbar. You now know when to throw the grenade to not blow yourself up. ⏲_
**SpinBot™️:** _Do you wanna look RETARDED AND obviously CHEATING?! This feature is for you_
**Transparency:** _Allow you to basically xray stuff. You can now see inside buildings and stuff very cool._

**Comment by WinterManTM** [comment]
damn bro thats hot

**Comment by humphreygaming** [comment]
Will add a wiki page on https://icehacks.github.io/ when ice gives me perms

**Comment by WinterManTM** [comment]
good humpy :100: 👍

**Comment by IceHacks** [comment]
lol

**Comment by TheSatanicAngeI** [comment]
`FAQ (NOT OFFICIAL TEMPLATE)`
**Q:** How do I download the hack ? 
**A:** _How to install IceHacks: Extract the ZIP file into a folder (if on ChromeOS follow extraction instructions). Open Chrome*, and enter "chrome://extensions" in the address bar, or get to extensions via settings. Once you have gotten to extensions, click the button on the top right labeled "developer mode" to turn on Dev Mode. Now on the top left corner, there is a button labeled "load unpacked". Click that and select the folder in which you extracted the Cheat files.
You now have the IceHacks cheat! (Or you should). If you want to enable IceHacks for incognito, click on "details", scroll down and select "allow in incognito". The cheat supports any chromium browser with extension support (this includes: Opera, Chrome, Edge Chromium, Vivaldi, ...). If you get any errors while installing make sure to have the right folder selected._
**Q:** Why is the hack freezing ?
**A:** _There are many reasons that may cause the freezing. Make sure you have the lastest version of the hack installed. Before opening an issue on SurvivCheatInjector go in [https://github.com/IceHacks/SurvivCheatInjector/releases/tag/2.0.2]([url](url)) and check the dates of both surviv.io update and IceHacks. If it doesn't match well that's probably why. Another reason could be bumpfire, make sure to disable it (it isn't necessary and I'm like 99% sure thats why you freeze))_
**Q:** Why is the hack not updated yet (open new thread +999999 me angery!)
**A:** _This hack is given to you by amazing developers that probably have a life and also don't charge for it. Don't expect it to work 24/7/365. Just give it time or request features but don't open useless threads that will make the devs want to commit not alive and stop this project._ 
**Q:** WHY MY ACCOUNT GOT BANNED IM SO MAD!
**A:** _The developers of SurvivCheatInjector are not responsible for the actions you took using this cheat. Therefore if you have a complain go talk to the devs of surviv.io and be ip banned aswell for cheating._
**Q:** What are the best settings for the hack ? 
**A:** _It's because of people like YOU that @TheSatanicAngeI spent 30 minutes making a fucking wiki. Well now go read it and decide what is the best play style for you!_ 

### More stuff will be added soon...?

**Comment by WinterManTM** [comment]
geez dude

**Comment by TheSatanicAngeI** [comment]
### ACTUAL ISSUE!

For some reasons I can't access the leaderboards and my statistics on surviv.io with the cheat enabled.

It just does this : https://gyazo.com/fb89a2a160c65f578be979a8f86b80f1
https://gyazo.com/6309f2a57f8a70fc2f020c12e6aa1d99

There's just that idk

**Comment by TheSatanicAngeI** [comment]
[https://i.gyazo.com/76d3a854da8f2c1c0df860122d9d1890.png](url)


LOL

**Comment by IceHacks** [comment]
@TheSatanicAngeI use a surviv proxy to access leaderboard rn

http://ot38.club/stats
