### ISSUE TITLE
I have a very small bug

### ISSUE THREAD

**Issue by IceBoi8000** [IceHacks/SurvivCheatInjector#212]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by IceBoi8000** [comment]
The bug is that everytime I am unarmed and I have to use my fists in order to get a kill, the aimbot tells me to use my fists in circles, not directly to the target. This is a disadvantage, because the target can just circle around me, and I am also circling with my fists, and then it just ends  up in an infinite loop of circles. What I expected was that I head directly TO the target, not select a target, and then circle them over and over again, because now 70% of the time I die and they get the kill.

**Comment by IceBoi8000** [comment]
P.S the update is the latest update, the christmas themed one.

**Comment by TheSatanicAngeI** [comment]
@IceBoi8000 Do you use mobile ? This may have something to do with auto attack. 

@IceHacks help

**Comment by TheSatanicAngeI** [comment]
Also next time make a better ### TITLE

this isn't a small issue to me looks like an actual problem.

**Comment by WinterManTM** [comment]
sir the icehacks title is fine rn

**Comment by humphreygaming** [comment]
Maybe spinbot may be on, as auto attack is very shitty with that. You might have also enabled mobile movement, which also does not work very well with auto attack. A video would be useful @IceBoi8000

**Comment by IceBoi8000** [comment]
no its not spinbot, I never use it because, like everyone said, its trash and technically useless, unless you are on enemy fire and you need to hide/escape. But im on Windows, and not mobile
