### ISSUE TITLE
Binds and Smart Switch

### ISSUE THREAD

**Issue by TommyZzZz** [IceHacks/SurvivCheatInjector#215]
**Describe the bug**
Not really a bug, just really confused on how the binds work. So you set it to a key and there is options press and toggle. Like it doesn't work for me when I try it. Also what does smart switch do on the new update. I wish there is a description of each hack.  What is a minimum fire delay lol.
**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by humphreygaming** [comment]
SmartSwitch was made by zbot i think, you should ask him

**Comment by WinterManTM** [comment]
Yes.

**Comment by TommyZzZz** [comment]
?? who is zbot

**Comment by K7Albert** [comment]
> ?? who is zbot

Join the discord:  https://discord.gg/mvsqsfG

And DM zbot473 there

**Comment by zbot473** [comment]
me

**Comment by TommyZzZz** [comment]
what is smart switch zbot
