### ISSUE TITLE
Selecting username with "n" conflicts with the opening of the cheat menu

### ISSUE THREAD

**Issue by ears-ears** [IceHacks/SurvivCheatInjector#216]
The warning that the user receives when "n" is pressed appears even when the user is typing in his/her own username. Please fix so that the user only receives the warning when "n" is pressed outside of typing in the username box, or get rid of the warning altogether. 

Thanks
- ears_ears

**Comment by WinterManTM** [comment]
It Should Only Happen once or when u press it make sure to turn off the gui poping up

**Comment by ears-ears** [comment]
> It Should Only Happen once or when u press it make sure to turn off the gui poping up

Ah, sorry about that. I didn't see the option to disable the warning, my bad.

**Comment by IceHacks** [comment]
Glad to see that fixed it. But this is still not a wanted behavior added to todo-list.
