### ISSUE TITLE
Zombsroyale.io aimbot when...? 

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#218]
Ok so I basically found this guy who is literally asking you to go on his patreon or some shit buy a membershit to access his gay ass shitty trash aimbot extra features that is still in progress. 

@IceHacks @humphreygaming You guys wanna flex on him and make a better aimbot for free on this game ? 

https://github.com/HackerHansen/Zombsroyale.io-Aimbot-BETA

I also have the files so you can see how he did the aimbot. 
[SOURCE CODE.txt](https://github.com/IceHacks/SurvivCheatInjector/files/4001144/SOURCE.CODE.txt)

He made it a gui thing its pretty much broken etc. 

So if you guys are uhhh having a lot of free time consider this

**Comment by humphreygaming** [comment]
Haha, yea we tried this once. However, getting into the zombsroyale source code is a tad bit hard. So we gave up on that game

**Comment by IceHacks** [comment]
I got into the important stuff fine, just didn't know where to go from there. The game isn't too interesting tbh.
