### ISSUE TITLE
IceHacks "Cheatsheet" 

### ISSUE THREAD

**Issue by ears-ears** [IceHacks/SurvivCheatInjector#219]
For anyone confused with what all the settings do :) 

#### Type: 
- On shoot: Aimbot activates when you fire your weapon or attack with melee. 
- Inverted aim: Aimbot activates when you hold down the right mouse button. 
- Autoaim: Aimbot is always on regardless of what else you do. 

#### Use collisions:
If set to “true”, the aimbot does not activate when there is a wall or other object blocking the player from shooting an enemy. 

#### Aim with mouse:
The mouse position, rather than distance (from player) will decide which target the aimbot will lock on to. 

#### AutoAttack:
If set to “true”, the player automatically switches to melee and follows enemies around while attacking them with melee if the player is within a certain distance of an enemy. Super OP with axe/hammer and adrenaline. 

#### AutoShoot: 
Player automatically shoots when detecting an enemy, if using Aim on shoot this won’t make a difference. 

#### Aim at downed:
If set to “true”, the aimbot will aim at downed players. Vice versa if set to false. 

#### Aim at objects:
If set to “true”, the aimbot will aim at a breakable object that gives loot (such as a crate or barrel in the casino). This will only happen if the player is EXTREMELY close to the object, AKA within kissing range. 

#### MobileMovement:
If set to “true”, the player will follow the cursor on the screen.

#### LegitMode:
If set to “true”, the player will mimic more “natural” movements and won’t obviously aimlock on an enemy. Aimbot’s still in effect, and it’s not infallible, but it’s a step in the right direction if you’re playing competitive in surviv.io discord for example and you don’t want people to notice you locking onto enemies in a building. 

#### Aim FOV:
The Field of Vision of the aimbot (with respect to where the cursor is). For example, if the Aim FOV is set to 120, then the aimbot won’t snap back to someone behind you if your cursor is in front of your player. Generally this is only really useful for closet cheating. 

#### Velocity Mult:
Called “LERP” or “Speed LERP” in previous versions of IceHacks, this determines how much the aimbot will compensate for enemy movement when firing. Because there is bullet speed, the aimbot can’t just fire directly at a player’s position if they’re moving; all the bullets will miss barely because of bullet speed. A higher Velocity Mult value will compensate MORE for player movement, and vice versa. 

## Auto loot/doors: 
Pretty self-explanatory. If set to “true”, the player will automatically open doors it meets as well as auto-loot ammo, pills, bandages, etc. until they are full in the player’s inventory. The player will automatically pick up any weapons on the ground (including melee) if the slot is empty; however, if full, the player will NOT pick up any more weapons on the ground. 

#### Mode: 
- Sniperswitch: Automatically switches the player to the second slot if the player is using an M870 or Sniper and fires. 
- Smartswitch: Switches guns when one is out of ammo. 

#### Ignore Auto Weapons:
Ignores automatic weapons when doing Sniperswitch.

#### Min. Fire Delay:
The firing delay between shooting each bullet. 

#### Aimbot:
If enabled, pressing the bind-key will enable or disable Aimbot. 

#### Spinbot:
If enabled, pressing the bind-key will enable or disable Spinbot. 

#### AutoSwitch:
If enabled, pressing the bind-key will enable or disable AutoSwitch. 

## Bumpfire:
When this setting is turned on (it will be in white when done so), the player will automatically fire any semi-automatic weapon when the mouse is hold down. 

## Dark Theme: 
Self-explanatory. Turn this setting on and off if you truly wish to see what it does. 

#### Flashlight:
Shows the range and spread of a player’s weapon. It’s marked in blue and acts like a flashlight emanating from the player. The player will also see enemies with the same “flashlight”. 

#### Blast Radius:
Shows the radius of which a harmful explosive (like a MIRV, frag or oil barrel) will damage the player. Outlined in red. 

#### Grenade Timer: 
Shows the time for a grenade to fully cook, when a player’s grenade’s pin is pulled. 

## SpinBot:
When enabled, the player “spins” once per frame. Only aimbot interaction can override this; human interaction cannot. 

#### Spin Angle:
The value dictates the angle at which the player spins per frame. Since surviv.io 

#### Obstacles:
The value dictates how transparent obstacles (silos, rocks, trees, etc.) are. The lower the value, the more transparent, and vice versa. 

#### Roofs:
The value dictates how transparent roofs (on top of buildings, such as the casino, mansion, etc.) are. The lower the value, the more transparent, and vice versa.

**Comment by TheSatanicAngeI** [comment]
@ears-ears BRUH I literally did this already but vouch...yours is less esthethic but more accurate and easy to understand. 
😞

**Comment by ears-ears** [comment]
> @ears-ears BRUH I literally did this already but vouch...yours is less esthethic but more accurate and easy to understand.
> 😞

If you did then sorry, I didn't see it.

**Comment by eimonpakzad** [comment]
where @TheSatanicAngeI

**Comment by TheSatanicAngeI** [comment]
@eimonpakzad https://github.com/IceHacks/SurvivCheatInjector/issues/210

**Comment by WinterManTM** [comment]
boomer

**Comment by ears-ears** [comment]
> boomer

rEpOrt

**Comment by WinterManTM** [comment]
ill boomer u
