### ISSUE TITLE
Can you make a firefox version of this cheat?

### ISSUE THREAD

**Issue by ILOVECHEATING** [IceHacks/SurvivCheatInjector#220]
I request firefox because I have a potato pc and chrome is eating up my ram
Firefox is more lightwehight so can you make a firefox version of this cheat?

**Comment by ILOVECHEATING** [comment]
Or you can make a client that don't eat too much system resources

**Comment by ears-ears** [comment]
+1

**Comment by humphreygaming** [comment]
Probs

**Comment by WinterManTM** [comment]
Maybe :D

**Comment by IceHacks** [comment]
Different APIs, but, you can use any other chromium-browser (opera, vivaldi, slimijet, ...)

**Comment by IceHacks** [comment]
+1 on client tho
