### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by K7Albert** [IceHacks/SurvivCheatInjector#221]
WINTER MAN & FIN PLS Un MTUE AND VERIFY ME IN ICE HACKER DISCORD PLS PLS  I DIDNT DO ANYTHING I DIDNT SPAM I DONT SPAM PLS UN MUTE AND VERIFY ME TY

**Comment by K7Albert** [comment]
BTW lima ia still mad cuz she CANt BAN!! lol!!!

**Comment by humphreygaming** [comment]
lmao, imaging coming to github to complain
