### ISSUE TITLE
freeze

### ISSUE THREAD

**Issue by icehacksfanaa** [IceHacks/SurvivCheatInjector#223]
version 2.01 freezeing in potato mode and i dont play snow mode cuz its look so wired

**Comment by HK1170** [comment]
yup, it's the new game update that's freezing again, would IceHacks fix this or would he just enjoy new year fully XD

**Comment by gh67uyyghj** [comment]
HERE WE GO AGAIN
![](https://i.imgur.com/k0IGUXx.jpg)
