### ISSUE TITLE
game freezes after about 30 seconds (every time)

### ISSUE THREAD

**Issue by davidcheater** [IceHacks/SurvivCheatInjector#225]
**Describe the bug**
game freezes after about 30 seconds (every time) with error codes

**Cheat version**
2.0.1 & 2.0.2

**Comment by umarkhan852** [comment]
and 2.0.0 its working?

**Comment by tomoIkebukuro** [comment]
Hi, davidcheater.
Would you tell us the error codes?
Because that error codes could be a breakthrough to solve this problem.
Even though I used developement tools in google chrome,
I cant find error codes.

**Comment by eimonpakzad** [comment]
it is not working for me

**Comment by WinterManTM** [comment]
its ok, u gatta wait for ice to get back :D hes on break rn
