### ISSUE TITLE
The cheat is freezing 

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/SurvivCheatInjector#227]
The cheat is freezing 
![Screenshot 2019-12-30 at 10 54 57 AM](https://user-images.githubusercontent.com/35317687/71589430-d9a2d180-2af2-11ea-9c6c-faf02028b93b.png)
every (30 sec)

**Comment by WinterManTM** [comment]
we know, we need ice to get back and the prob will be fixed :D

**Comment by rogerangell97** [comment]
Seriously?! 6 topics about same issue.

**Comment by WinterManTM** [comment]
yea man its sad
