### ISSUE TITLE
HEY GUYS GUESS WHAT ?!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#228]
The cheat is freezing the game updated with events. 

Now shut the fuck up and get good.

Or cry and wait for @IceHacks to be back

kthx bai.

**Comment by WinterManTM** [comment]
bruh u know how these 7 year olds be lmfao they wont understand

**Comment by TheSatanicAngeI** [comment]
https://gyazo.com/e9ab0a4b391fb7f458a7bfc4a9b82cfd

**Comment by WinterManTM** [comment]
ok boomer
