### ISSUE TITLE
Before opening any issues, read this

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#229]
Yes, we are aware of freezing. Unfortunately, IceHacks is on vacation or something and will be back sometime around next week.

**Comment by eimonpakzad** [comment]
can you not fix the hack

**Comment by humphreygaming** [comment]
maybe if i had the source code or something

**Comment by ears-ears** [comment]
o k o k o k o k

**Comment by umarkhan852** [comment]
we wanna play potato mode
past we can't play ptato mode
why?

**Comment by umarkhan852** [comment]
when new hacks come?
