### ISSUE TITLE
Humphrey Gaming read 

### ISSUE THREAD

**Issue by IceHacksFan** [IceHacks/SurvivCheatInjector#23]
ice hacks said to come to u about buying / getting premuim

**Comment by humphreygaming** [comment]
@IceHacksFan yes, message me on discord @HumphreyGaming#1789

**Comment by IceHacksFan** [comment]
will later

**Comment by IceHacksFan** [comment]
so i get for free or i pay

**Comment by humphreygaming** [comment]
pay
