### ISSUE TITLE
IS IT SUPPOSED TO FREEZE EVERY 5 SECONDS??????

### ISSUE THREAD

**Issue by jeff12345lol** [IceHacks/SurvivCheatInjector#234]

**Comment by pilgrimoflight** [comment]
No, but you supposed to FUCK OFF (!!!)

**Comment by TheSatanicAngeI** [comment]
@jeff12345lol Yes its supposed to freeze every 5 seconds.

**Comment by humphreygaming** [comment]
**READ THE FUCKING PINGED ISSUE YOU LAZY FUCKS**
