### ISSUE TITLE
its fin c:

### ISSUE THREAD

**Issue by BobbyTheDev** [IceHacks/SurvivCheatInjector#235]
hey i just wanna see how everyone is doing c:

**Comment by IceHacks** [comment]
vaca 😎

**Comment by ears-ears** [comment]
tion 😎

**Comment by humphreygaming** [comment]
vaca = cow

**Comment by u1qqlv** [comment]
> vaca = cow

this is in moldavian language? :D

**Comment by K7Albert** [comment]
> vaca = cow

jódete hijueputa

**Comment by K7Albert** [comment]
PQ NO TODOS HABLAN ESPAÑOL? ??

**Comment by Griff0118** [comment]
So did the freezing bug get fixed?
