### ISSUE TITLE
i can't play duos or squads 

### ISSUE THREAD

**Issue by PersonNamedAlex** [IceHacks/SurvivCheatInjector#238]
i have the latest one, downloaded just now as of this comment 

![image](https://user-images.githubusercontent.com/40143912/71644381-57064780-2c95-11ea-9b23-7bac24728429.png)

sure i can make a team but i can't play with others,
i think this might be a me only type of problem, not globally tho but i still need help please

**Comment by IceHacks** [comment]
Just disable darkmode.

**Comment by PersonNamedAlex** [comment]
im probably dumb but wdym by dark mode? surviv doesnt have a dark mode, i disabled all themes and what not for chrome, what do you mean by dark mode? Im on incognito in the pic tho idk how you can tell

**Comment by PersonNamedAlex** [comment]
oh wait nvm i got it lmao
