### ISSUE TITLE
I cant see all cheat features

### ISSUE THREAD

**Issue by DSLSucuk** [IceHacks/SurvivCheatInjector#239]
I can't see the whole cheat in the main menu.
I got a picture of it and 2 pictures with errors.
![Unbenannt](https://user-images.githubusercontent.com/59420135/71645365-95bcf180-2cd7-11ea-9e50-3633a7e3cc8c.png)
![Unbenannt2](https://user-images.githubusercontent.com/59420135/71645366-96558800-2cd7-11ea-8c2d-e6a7d574ea22.png)
![Unbenannt3](https://user-images.githubusercontent.com/59420135/71645367-96558800-2cd7-11ea-97eb-126e4f14e99c.png)

It would be nice if you could help me out.

**Comment by IceHacks** [comment]
Just disable darkmode. And if you read those "errors" you'd realize they mean nothing.
