### ISSUE TITLE
Conditional/Context-sensitive SniperSwitch

### ISSUE THREAD

**Issue by StroggVorbis** [IceHacks/SurvivCheatInjector#241]
Like standard SniperSwitch, except you need to have two weapons eligible for it, otherwise don't switch.

E.g. two shotguns, two snipers, one shotgun & one sniper.

If the other slot is empty or contains a full auto weapon, don't switch upon firing.

Basically as before but where it previously switched to fists it instead keeps the fired weapon selected. 

Alternative: an additional "Switch to fists" bool as a SniperSwitch parameter.

**Comment by zbot473** [comment]
SmartSwitch is already an option if u click on mode

**Comment by StroggVorbis** [comment]
Yes, but SmartSwitch doesn't do what I describe here. At first I thought it did, given the name, but for me it didn't appear to work given my expectations.

**Comment by IceHacks** [comment]
I understand
