### ISSUE TITLE
Aimbot not working with spud gun and potato cannon and OT-38, famas ump and saiga-12 not quick switching.

### ISSUE THREAD

**Issue by picatrota** [IceHacks/SurvivCheatInjector#242]
aimbot is not working with spud gun and potato cannon and ot-35, famas, ump and saiga are not quick switching. Version 2.0.3

**Comment by humphreygaming** [comment]
Aimbot works with spud gun/potato cannon (for me at least). ot-35, famas, ump, and saiga are not supposed to quickswitch i think
