### ISSUE TITLE
Squad and team mode gone

### ISSUE THREAD

**Issue by Reeyaad** [IceHacks/SurvivCheatInjector#245]
If I use the cheat, the squad mode goes away. 
I have read the previous issue and thought that it's an internet problem but I have no internet problem and this problem occurs only when I enable the extension.
I have tried using a VPN, but still, it's the same.
If I disable the cheat, it goes back to normal.

![image](https://user-images.githubusercontent.com/20893493/71773731-8ca87a80-2f8c-11ea-9f9e-f7cf643daff6.png)
![image](https://user-images.githubusercontent.com/20893493/71773734-992cd300-2f8c-11ea-9936-2e1c74b54fc1.png)

**Comment by humphreygaming** [comment]
have you tried clicking on create team?

**Comment by Reeyaad** [comment]
> have you tried clicking on create team?

there is no option to click on team or squad as you can see in the screenshot below. 

![image](https://user-images.githubusercontent.com/20893493/71773740-b5c90b00-2f8c-11ea-90cc-7b6d0c4f4451.png)

**Comment by Reeyaad** [comment]
> have you tried clicking on create team?

yes , it works if I click on team, Thanks!

**Comment by humphreygaming** [comment]
the create team button is right there lmao

**Comment by humphreygaming** [comment]
or you can just disable darkmode
