### ISSUE TITLE
Zoom pls

### ISSUE THREAD

**Issue by BopItFreak** [IceHacks/SurvivCheatInjector#246]
pls add zoom. I like it even if it doesn't load more without scopes. Also pls add the cool line that leads you to better gear like in your friend's hack.

**Comment by humphreygaming** [comment]
zoom is useless, ice doesn't see a point. He might do it tho. As for the cool lines, it has been considered for some time

**Comment by u1qqlv** [comment]
I can add zoom if they make me dev lol

**Comment by humphreygaming** [comment]
zoom is an easy thing to do, it is just that it falls last in ice's to-do list
