### ISSUE TITLE
Before any issues, read this

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#25]
Yes, we are aware that surviv updated today at around 7pm PST, yes I'm trying my hardest on fixing, no Ice will not be here for another week, good night

**Comment by u1qqlv** [comment]
for me the old build works, I don't know how, just letting you know

**Comment by humphreygaming** [comment]
@u1qqlv this hack technically did not stop working, it just bugged out the aimbot's prediction and stuff like that
