### ISSUE TITLE
Game Update

### ISSUE THREAD

**Issue by ehxhidra** [IceHacks/SurvivCheatInjector#251]
Hi, the game updated literally just now, and the cheat is now not working. Can you please update it? :)

**Comment by humphreygaming** [comment]
it did? wow. surviv finally implemented snow mode. those lazy bastards....

**Comment by ILoveIcehacks** [comment]
Yeah it updated

**Comment by ehxhidra** [comment]
XD I'm the first to know... I should get a life and reduce playing surviv.io :D

**Comment by humphreygaming** [comment]
just so you know, im not the one who makes the hacks. that's ice. and ice is not here atm. so it could take a while

**Comment by ehxhidra** [comment]
Ok Thx for the info :)

**Comment by Griff0118** [comment]
A week ago my account got banned. Lol

**Comment by ehxhidra** [comment]
lol my first account got banned few weeks ago XD

**Comment by IceHacks** [comment]
hmm

**Comment by IceHacks** [comment]
@ehxhidra what's broken about it, I played a round with no bugs.

**Comment by IceHacks** [comment]
@ehxhidra just refresh the extension whenever the game updates.
