### ISSUE TITLE
Bullet Reflection Auto-Aim

### ISSUE THREAD

**Issue by Griff0118** [IceHacks/SurvivCheatInjector#253]
Since in surviv the bullets reflect off of some wall surfaces I was thinking you could maybe make the Auto-Aim calculate the angle at which your bullets would reflect and hit someone in places like a bunker, off a barrel, or other reflective surfaces. I do however realize this would be difficult because you have to program every angle. One instance where this would be useful is when someone is hiding from you near a reflective surface, if they keep faking you out then you could shoot off that surface and kill them. I hope you will consider this as an enhancement.

**Comment by Griff0118** [comment]
I am at school right now so if you have any questions I will respond a little later.

**Comment by IceHacks** [comment]
you mean like a trickshot bot right @Griff0118

**Comment by Griff0118** [comment]
Yes, Precisely

**Comment by IceHacks** [comment]
That's pretty computationally expensive stuff. The human mind is much better at figuring stuff like that out so as of now I don't think I could do it in a high-performance way.

**Comment by Griff0118** [comment]
Ok, thats fine because as I said it would be difficult to program.

**Comment by magikol** [comment]
It's been done :D
