### ISSUE TITLE
Close This Please

### ISSUE THREAD

**Issue by Griff0118** [IceHacks/SurvivCheatInjector#256]
I do not understand how this hack fully works but I was wondering if you could make a XP Booster so I could gain levels faster.

**Comment by StabbyAlbert** [comment]
Please use your head before posting any enhancements that are not possible, those are serversided and we cant control it.

**Comment by Griff0118** [comment]
I mean as I said I didn't understand this hack fully.

**Comment by Griff0118** [comment]
I knew it probably would not happen but I still wondered.

**Comment by humphreygaming** [comment]
Yea, not possible, or it would have been added some time ago
