### ISSUE TITLE
Rmb Aim

### ISSUE THREAD

**Issue by Olaf013** [IceHacks/SurvivCheatInjector#259]
It's a stupid question to be honest but how do you auto-aim with RMB? the 2.0.2 version had a mode for it in the aimbot section of the hack, but it got removed and now there is a inverted aim mode instead. again it's a stupid question.

**Comment by humphreygaming** [comment]
Inverted aim is the same as RMB, which stands for Right Mouse Button
Click RMB: Aimbot turns on and locks to nearest player
Release RMB: Aimbot turns off
