### ISSUE TITLE
when i play in team mode with friends not as leader game not starts and all other games not starts before i clean cookies. its only at newest version.

### ISSUE THREAD

**Issue by muWander** [IceHacks/SurvivCheatInjector#26]

**Comment by muWander** [comment]
btw at newest version autoswitch works anyway

**Comment by JaidenDestroyer** [comment]
I cannot understand your issue, could you re-write this in a clearer way?

**Comment by humphreygaming** [comment]
@muWander Yea, what Jaiden said, try clearing up and elaborating more on it. What I understand tho, are you saying that the game does not start unless you are team leader/clear cookies (using CTRL + F5)?

**Comment by IceHacks** [comment]
@muWander Do you mean you get a plain green-screen when playing on team mode?
