### ISSUE TITLE
Container Attack

### ISSUE THREAD

**Issue by thebeast548** [IceHacks/SurvivCheatInjector#262]
When you are right outside a bunker or a house and you are attacking someone, it doesn't let you move and the player keeps going against the wall trying to attack the person inside. When you are right outside a building and someone is inside right in front of where you are, the survivr keeps trying to go forward and attack the person inside..
Could you please try to fix the problem?

**Comment by IceHacks** [comment]
*the problem*

lol

Just disable auto-attack if you don't want it to auto-attack.
