### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by Reeyaad** [IceHacks/SurvivCheatInjector#264]
This new code lasted the longest time I have ever seen, kudos to all the developers who worked so hard to make this cheat come alive. Thank you.

**Comment by pilgrimoflight** [comment]
So sad.d

**Comment by humphreygaming** [comment]
@Reeyaad yes, and will probably continue doing so. I have a feeling Kongregate did not contribute to this update. Justin and Nick probably had something to do with this

**Comment by IceHacks** [comment]
@humphreygaming why is this closed, does the cheat work again?

**Comment by humphreygaming** [comment]
no lmao
