### ISSUE TITLE
Icehacks glitch which makes it not to work

### ISSUE THREAD

**Issue by picatrota** [IceHacks/SurvivCheatInjector#265]
the glitch basically makes the hack unusefull, it doesnt load the hack options and stuff, the game doesnt start with the hack. V 2.0.3

**Comment by IceHacks** [comment]
@picatrota what "glitch", please add more information.

**Comment by picatrota** [comment]
nvm @IceHacks , for some reason its working again. Like... 3 or 4 hours ago it wasnt working for me and my friend. sorry for the disturb

**Comment by IceHacks** [comment]
No problem. We fixed that issue.
