### ISSUE TITLE
Game Mode

### ISSUE THREAD

**Issue by Tarun430** [IceHacks/SurvivCheatInjector#266]
Hi guys,
Is there a way for the aimbot to be on, but on your screen it looks like the normal game. I want this so that when I play with people and they see my screen they won't know I have an aimbot.
Thanks guys

**Comment by IceHacks** [comment]
@Tarun430 turn off ESP, and other graphical things, then use either the AimBot FOV or aim on shoot. Also, I recommend disabling auto attack and auto shoot.
