### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#267]
the game is freezing

**Comment by IceHacks** [comment]
cannot reproduce, but we will keep trying.

**Comment by u1qqlv** [comment]
they updated the game and my hack broke, your hack freezes for me.

**Comment by IceHacks** [comment]
I found the problem, I will fix it. Thank you for alerting me!

**Comment by IceHacks** [comment]
Fixed. I will release with 2.0.4
