### ISSUE TITLE
>:C

### ISSUE THREAD

**Issue by IceHacks** [IceHacks/SurvivCheatInjector#27]

**Comment by JaidenDestroyer** [comment]
Nice issue coach

**Comment by coolboy10121416** [comment]
what happen son @IceHacks

**Comment by SpiffyJUNIOR** [comment]
cool

**Comment by DamienVesper** [comment]
More hacks, ay? (Gotta report).

**Comment by humphreygaming** [comment]
@DamienVesper Yes, more hacks (good luck reporting)

**Comment by DamienVesper** [comment]
Reported :P

**Comment by humphreygaming** [comment]
Yay! I wish the best of luck to the devs who will try to figure out how to patch this (cuz IceHacks ain't no lazy bitch like ipissin)

**Comment by DamienVesper** [comment]
Well, I mean, the use of zip files would be pretty annoying (zips inside the repository).

**Comment by humphreygaming** [comment]
smh, you don't understand. It's all about the CODE.

**Comment by DamienVesper** [comment]
YOU THINK I DON'T UNDERSTAND CODE

**Comment by humphreygaming** [comment]
Hehe, good luck reading it. And if you don't understand it, neither will the surviv devs :)

**Comment by DamienVesper** [comment]
So, you're saying I'm better at coding than surviv devs. Thanks :P

**Comment by humphreygaming** [comment]
Uhu, why don't you think surviv.io has progressed? There should be cities, new guns, better server support. And is there that? No

**Comment by DamienVesper** [comment]
And what's the need for hacks? That's the question I pose to you.

**Comment by humphreygaming** [comment]
Idk, recognition? User demand? "Fun"? Plus, fine, you reported it. That's ok. That's _totally_ fine. And what if we unpatch it? Will you report it again?

**Comment by DamienVesper** [comment]
No they'll patch it themselves.

**Comment by humphreygaming** [comment]
Hehe, good luck to them finding spare time. They don't even have time for their own game

**Comment by IceHacks** [comment]
lol loser

**Comment by IceHacks** [comment]
@DamienVesper I wouldn't call them new (new to Github, yes :D). I wouldn't call them hacks either (proper term: cheats :P). As for the reporting I say, "whatever, report your heart out". xD

**Comment by humphreygaming** [comment]
@DamienVesper Here is a TXT file link for the obfuscated code if you want to give it to the devs: https://bit.ly/IqT6zt

**Comment by FallingBoi** [comment]
@humphreygaming lmao
