### ISSUE TITLE
name not showing in leaderboards

### ISSUE THREAD

**Issue by gautamgxtv-V2** [IceHacks/SurvivCheatInjector#272]
its me gautamgxtv but i forgot my password so i made a new email anyways if you get like 20 kills with the hack and check the leaderboards in surviv my name wont show up.

Can you fix this so i can brag to my friends i got #1 in the leaderboards(they dont know im hacking lol)

**Comment by IceHacks** [comment]
@gautamgxtv-V2 in order to be on the leaderboards you must have a surviv account.

**Comment by gautamgxtv** [comment]
but i do have an account.....
surviv.io/stats/Coder-Gautam-yt

**Comment by gautamgxtv** [comment]
for example, i was in a game with iblissin solos(he killed me) and at the end he had over 20 kills. I checked the leaderboards and he wasnt there

**Comment by gautamgxtv** [comment]
never mind sorry my name showed up. iblissins account was deleted thats why his name wasnt showing up
