### ISSUE TITLE
stuck on green screen

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#274]
Valentines mode is here and i really want to play it!!! but the cheat is froze on the green screen if you play it. pls fix this

**Comment by IceHacks** [comment]
I'm sure everybody wanted to play it. But I'll look ar it later.

**Comment by IceHacks** [comment]
I fixed this, but surviv doesn't work. Even without cheats. Devs broke their game.

**Comment by joe69ligma** [comment]
oh ok

**Comment by luketobin-maker** [comment]
> I fixed this, but surviv doesn't work. Even without cheats. Devs broke their game.

**Comment by luketobin-maker** [comment]
> I fixed this, but surviv doesn't work. Even without cheats. Devs broke their game.

That is not true icehacks. I turned off my hacks and I could play Valintines day mode fine.

**Comment by IceHacks** [comment]
Well for everyone else it was true.
