### ISSUE TITLE
screen freezes with  bunch of random info

### ISSUE THREAD

**Issue by joe69ligma** [IceHacks/SurvivCheatInjector#275]
![Screen Shot 2020-02-10 at 4 43 36 PM](https://user-images.githubusercontent.com/60901587/74193442-61691900-4c25-11ea-9c1d-0927d55c1f8b.png)

**Comment by IceHacks** [comment]
#274

**Comment by asadkid** [comment]
same issue for me, i already tried refreshing doesnt work
