### ISSUE TITLE
dude the devs did not break the game the hack is just not working #greenscreenissue

### ISSUE THREAD

**Issue by joe69ligma** [IceHacks/SurvivCheatInjector#276]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by IceHacks** [comment]
They did. Sad you didn't read my messages. I fixed greenscreen in a test file, but surviv still didn't work. So I went without cheats and it still didn't work. Now I have found the solution to their mistake and published the cheat. Please read messages before creating issues.
