### ISSUE TITLE
ot-38 as sniper-switch weapon

### ISSUE THREAD

**Issue by gautamgxtv-V3** [IceHacks/SurvivCheatInjector#279]
hey it would be really nice if you can make the ot-38 a sniperswitch weapon like you can have spaz+ot and it would quickswitch. 

Also whats the difference between sniperswitch and smartswitch and which one is better?

**Comment by IceHacks** [comment]
You can customize your options to include it. Sniper switch switches after shooting, smart switch switches when reload or based on distance.

**Comment by gautamgxtv** [comment]
how do i customize it?

**Comment by IceHacks** [comment]
change fire delay to 0.4

**Comment by IceHacks** [comment]
or smth like that

**Comment by gautamgxtv** [comment]
can you send me a screenshot?

**Comment by IceHacks** [comment]
![image](https://user-images.githubusercontent.com/38994479/74299593-3ea43680-4cf1-11ea-8061-94197acacd09.png)

it divides it by 10 in post

**Comment by gautamgxtv-V3** [comment]
Thx!
