### ISSUE TITLE
Weapon switch bug

### ISSUE THREAD

**Issue by 1tarko** [IceHacks/SurvivCheatInjector#28]
Some weapons switch automatically after one shot (mosin nagant,m480,super-80)...

Regards

**Comment by coolboy10121416** [comment]
@1tarko all you have to do is every time your refresh your page turn auto switch on then off it should work

**Comment by IceHacks** [comment]
@1tarko The update that @humphreygaming released was not supposed to be released. It was just a test. I don't know what made @humphreygaming release it. But for a temporary fix if you want to keep that update just turn on and then off.
