### ISSUE TITLE
Follow bot sniper switch inoperative

### ISSUE THREAD

**Issue by Mmids** [IceHacks/SurvivCheatInjector#280]
2.0.5

And even with a single sniper gun, can it be switched automatically?
1 weapon -> 3 fist -> 1 weapon

**Comment by IceHacks** [comment]
![image](https://user-images.githubusercontent.com/38994479/74290301-89b05080-4cd5-11ea-88e9-f9eae0df3b04.png)

Try turning Equip Melee off

**Comment by Mmids** [comment]
> ![image](https://user-images.githubusercontent.com/38994479/74290301-89b05080-4cd5-11ea-88e9-f9eae0df3b04.png)
> 
> Try turning Equip Melee off

Thanks but, Follow bot sniper switch inoperative 

It seems to occur limited to sniper guns
