### ISSUE TITLE
Adv Auto Reload & Auto Heal

### ISSUE THREAD

**Issue by Mmids** [IceHacks/SurvivCheatInjector#281]
Auto Heal
- No automatic consumption of Heal, Soda or Pills when the enemy is detected around me.

Auto Reload
- If the enemy falls within the range of my Auto Attack during reload, I would like to have the option of canceling the reload and attacking immediately.

These two things will be more perfect when they are complemented.

**Comment by gautamgxtv-V3** [comment]
yes please you should add this.... this is exactly the reason why i disabled Auto Heal and Auto Reload.
one time i was just standing there using pills while a guy was shooting at me(i died)

**Comment by StabbyAlbert** [comment]
Thanks, added to suggestion list
