### ISSUE TITLE
Hack on Twitch Server

### ISSUE THREAD

**Issue by gautamgxtv-V3** [IceHacks/SurvivCheatInjector#283]
Can you guys add the hack on the twitch servers(link below) so I can play private matches with my friends with the hack. thx so much guys!!

https://c79geyxwmp1zpas3qxbddzrtytffta.ext-twitch.tv/c79geyxwmp1zpas3qxbddzrtytffta/1.0.2/ce940530af57d2615ac39c266fe9679d/index_twitch.html

**Comment by IceHacks** [comment]
Please check previous issues on this topic. Thanks.
