### ISSUE TITLE
A new type of gun with AutoShoot.

### ISSUE THREAD

**Issue by Mmids** [IceHacks/SurvivCheatInjector#284]
This type of gun 

- Potato Cannon (Heart Cannon)
- Spud Gun
- M79 

is that does not apply to AutoShoot. 

I think it would be nice to have these guns applied.

**Comment by IceHacks** [comment]
Launcher guns have never worked (I never bothered to look why) I think it's fine as they are only there for a little while.

**Comment by IceHacks** [comment]
I haven't looked at this yet. But as just a guess, they are probably not in the "guns" list or they are missing some required parameters.
