### ISSUE TITLE
Cheat not working

### ISSUE THREAD

**Issue by cock-and-ball-torture** [IceHacks/SurvivCheatInjector#285]
Mixed Content: The page at 'https://surviv.io/' was loaded over HTTPS, but requested an insecure image 'http://surviv.io/img/gui/close.svg'. This content should also be served over HTTPS.

Without the extension it loads fine but with, it does not load properly or at all and I am unable to play.

**Screenshots**
https://i.imgur.com/nwhguOF.png
https://i.imgur.com/vwr0gQu.png
Edit: https://i.imgur.com/0UWLqg7.png

**Cheat version**
2.0.5

**Chromium version**
79.0.3945.130 (Official Build) (64-bit) (cohort: Stable)

**Comment by StabbyAlbert** [comment]
hey, have u tried reloading the extension in chrome://extensions/?

**Comment by cock-and-ball-torture** [comment]
Yes, I had reloaded the extension, unpacked and repacked multiple times, cleared my browser cache, deleted cookies but it still does not work for me.

**Comment by IceHacks** [comment]
@cock-and-ball-torture Try using proxies and doing Ctrl+f5 happens to me without the cheat sometimes too. You just gotta refresh a bunch until surviv.io loads.
