### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#286]
When loading surviv, there is a brief flash of normal (SCI-less) main menu, which is then replaced by what you see in the screenshot (almost correct SCI interface, but with surviv logo instead of ICEHACKS at the top). Cheat menu doesn't work. I can play the game from here just fine as if SCI wasn't installed (cheats don't work). I have tried reinstalling, deleting cookies, going through surviv proxies and opening surviv in incognito mode (after giving SCI permissions to operate in incognito) to make sure there's no interference from other addons. Nothing useful in dev console either.

Everything was working just fine yesterday, then this morning I had the correct interface with "ICEHACKS" logo at the top and a working cheat menu, but I could not play (the loading wheel began spinning, then after a long wait it said "host closed the connection" and nothing happened). I reinstalled and then this happened.

**Screenshots**
https://i.imgur.com/gP1xIVS.png

**Cheat version**
2.0.5

**Chromium version**
80.0.3987.106

**Comment by IceHacks** [comment]
#285

**Comment by Nihilistics** [comment]
I saw that before making this issue. The symptoms are completely different. I am not getting the green screen and there are no errors (well, only one - https://i.imgur.com/RSDOOb9.png )

**Comment by IceHacks** [comment]
It's the same issue. With the same solution. See his picture: https://i.imgur.com/vwr0gQu.png

**Comment by Nihilistics** [comment]
No, it's not the same issue. That screenshot is completely unlike mine.

**Comment by IceHacks** [comment]
It's the same issue I've had it

**Comment by IceHacks** [comment]
It initializes the page like this (https://i.imgur.com/vwr0gQu.png) and then loads the page like yours (https://i.imgur.com/gP1xIVS.png)

**Comment by Nihilistics** [comment]
He said that "Without the extension it loads fine but with, it does not load properly or at all and I am unable to play." - it's not the case for me, I can play with the extension (but then cheats don't work).
I can see that CSI gets loaded - there's the ASCII art in the dev console. Also, I've been checking the site on a off for the last 12 hours or so and every time I get the exact same result, despite Ctrl+F5ing probably 40 times in total.

**Comment by IceHacks** [comment]
reload the extension.

**Comment by Nihilistics** [comment]
Already did, several times. Same result.

**Comment by IceHacks** [comment]
The only possibilities and fixes for them are as follows:

1. Surviv updated, refresh extension
2. The game didn't load properly, refresh/use a proxy site
3. The game is freezing, wait for update/refresh extension
4. They patched the cheat, wait for an update

We know 4 hasn't happened because only you have this exact issue. So it is one of the others.
