### ISSUE TITLE
Which file to actually use?

### ISSUE THREAD

**Issue by Luigibro123** [IceHacks/SurvivCheatInjector#287]
I have downloaded the files but it kept on saying "could not manifest". How to Fix?
![image](https://user-images.githubusercontent.com/61103004/74599455-3162bf80-50d6-11ea-8b36-a23c85408079.png)

**Comment by Luigibro123** [comment]
I also have copied ALL the files to the folder

**Comment by StabbyAlbert** [comment]
https://github.com/IceHacks/SurvivCheatInjector/releases/tag/2.0.5

**Comment by IceHacks** [comment]
there are instructions for this issue.
