### ISSUE TITLE
Aim bot is not accurate 

### ISSUE THREAD

**Issue by zerodark088888** [IceHacks/SurvivCheatInjector#288]
**Describe the bug**
well i use this hack and idk why but it not working properly with aim bot i change setting try out diffrent things but still aim bot is not  accurte on aiming

**Expected behavior**
i thought it should aim perfectly on  enemys but its not

**Screenshots**

**Cheat version**
IceHacks Cheat v2.0.5

*Chromium version**
79.0.3945.130

**Comment by zerodark088888** [comment]
well i try have been used other aim bots but due to update they are not workig anymore
so i m using this one and i been mainly needed aim bot but when ever  aim bot aoto shot or without aoto shot . it not accuraltely aim on enemy but aim nearly 40-30degree away from enemy and due to aim bot i myself also not able to aim while aimbot is on and while enemy is hideing it no reason aoto shot and it casue me to die becuz it shot on barrel once  while enemy was behind barrel

**Comment by IceHacks** [comment]
Aimbot 2.0 is being updated. It's a new system and is only really good at medium range with accurate guns. The next update will fix this.
