### ISSUE TITLE
Option to automatically stop for a frame for sniper shots

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#289]
All guns have an increased spread with moving, which resets instantly when you stop. I think it should be possible to add an option to stop the player for a frame whenever he is about to shoot a sniper rifle for increased precision, even if a movement direction is held, and resume movement the next frame.

**Comment by StabbyAlbert** [comment]
will consider

**Comment by humphreygaming** [comment]
been thinking about this, sort of an autojitter thing.
