### ISSUE TITLE
WHAT THE ACTUAL FUCK IS THIS I HAVE NIGHTMARES NOW PLEASE FIX

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#29]

**Comment by TheSatanicAngeI** [comment]
![a30820da2f227a33092a30e13ef2fef5](https://user-images.githubusercontent.com/19210871/60474430-e88df180-9c3f-11e9-8bdc-55a5af0a6079.png)

**Comment by coolboy10121416** [comment]
just download the new one

**Comment by TheSatanicAngeI** [comment]
@coolboy10121416 I did what the hell ?

**Comment by TheSatanicAngeI** [comment]
It makes the piano noises too when I hit lmao

**Comment by coolboy10121416** [comment]
@TheSatanicAngeI did you download the one from 3 hours ago

**Comment by TheSatanicAngeI** [comment]
@coolboy10121416 yes

**Comment by coolboy10121416** [comment]
what

**Comment by coolboy10121416** [comment]
wtf

**Comment by TheSatanicAngeI** [comment]
axe is replaced to piano somehow

**Comment by coolboy10121416** [comment]
I know

**Comment by coolboy10121416** [comment]
do u still have spinbot

**Comment by TheSatanicAngeI** [comment]
yea

**Comment by coolboy10121416** [comment]
k thats not to be

**Comment by coolboy10121416** [comment]
download the new one now

**Comment by coolboy10121416** [comment]
download it over

**Comment by coolboy10121416** [comment]
Delete the on you have now  then go to https://github.com/IceHacks/SurvivCheatInjector/tree/master/build and click latest.zip then click open it extract it and you know how to install it to chrome

**Comment by TheSatanicAngeI** [comment]
@coolboy10121416 thanks! I don't know if it worked yet but I think I know what I did wrong... I updated from latest without build integrating the "icons" (idk)

still that was the funniest shit  I ever saw


https://gyazo.com/141eb721eb20a5002dcb4dcd72c354d0

spinning with a piano :rofl:

**Comment by TheSatanicAngeI** [comment]
@coolboy10121416 Damn it tho I enjoyed spinning

**Comment by TheSatanicAngeI** [comment]
@IceHacks give me ur discord

**Comment by humphreygaming** [comment]
@TheSatanicAngeI That piano feature IS intended

**Comment by IceHacks** [comment]
@humphreygaming No, you were not supposed to release that. It was a test not an update.

**Comment by IceHacks** [comment]
@TheSatanicAngeI Give me yours.

**Comment by coolboy10121416** [comment]
@IceHacks  know which one he is using lol
