### ISSUE TITLE
after update aoto attack not work

### ISSUE THREAD

**Issue by zerodark088888** [IceHacks/SurvivCheatInjector#290]
Sorry i means auto shoot
and auto aim is not working after update

**Comment by IceHacks** [comment]
Will fix.

**Comment by IceHacks** [comment]
Fixed. Re-install 2.0.6

**Comment by David-Rodden** [comment]
Not sure why this is closed when there seems to be many issues with the auto-aim still:
- functions as previously had when a melee weapon is drawn
- seemingly-random behavior when using a gun, not focused and/or firing at a random angle in a haphazard manner
