### ISSUE TITLE
When SniperSwitch is enabled and there's no sniper/shotgun in second slot, switch to the same gun instead of melee

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#291]
If you have a sniper rifle and e.g. an automatic rifle or nothing in the second slot, after a sniper shot SCI will switch to melee, making the player manually have to select the sniper again. I think it would be a good idea to instead make it switch to the gun that was just shot.

This is similar to #241, except instead of keeping the weapon selected, it would momentarily select melee to reset slowdown before switching back.

**Comment by IceHacks** [comment]
there is a bug that does this.

**Comment by Nihilistics** [comment]
Sorry, what do you mean?
