### ISSUE TITLE
Show all grenades in inventory on the screen at once

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#293]
One pet peeve with surviv's interface I've had for years is that it's impossible to see how many grenades you have of types other than the one you have selected. So I suggest changing the interface to something like this, if possible:

https://i.imgur.com/XN8Rxpc.png

The dark background is moved to whatever type of grenade is currently selected.

**Comment by humphreygaming** [comment]
will consider a UI change
