### ISSUE TITLE
Show how much ammo there is in the guns in the bottom right corner

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#296]
I'm thinking something like this: https://i.imgur.com/0nIOh2T.png

Empty guns have ammo count in red, partially filled - in orange, full - in white.

**Comment by IceHacks** [comment]
maybe...

**Comment by DamienVesper** [comment]
Kid you can stop hacking.

**Comment by oofgangcrypin** [comment]
Can you shut your retarded ass up? Jesus fucking christ my autistic brother is smarter than you get a fucking life you sad sack of shit

**Comment by SniperXKiller** [comment]
@DamienVesper HMM, I THINK oofgangcrypin IS SAYING THAT YOU'RE SO DUMB, THE ONLY WORDS YOU KNOW ARE "Stop hacking Kid", SO YOU DON'T REALLY KNOW WTH YOU'RE TALKING ABOUT.
I DON'T EVEN THINK YOU KNOW IF YOU KNOW IF THAT PERSON YOU ARE COMMENTING TO IS LIKE, 70 YEARS OLD. IF THAT IS "Kid" IS 70, YOU SHOULD BE LIKE ABOUT UH, 9999999999 CENTILLION YEARS OLD, KNEW CAVEMEN, WHICH MAKES SENSE WHY YOU DON'T KNOW WHAT YOU ARE TALKING ABOUT.

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201803/29/2475086/2475086_180_87dd.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://images.pornpics.com/1280/201907/05/2787406/2787406_073_adf1.jpg)
