### ISSUE TITLE
Pan hero

### ISSUE THREAD

**Issue by cornmask** [IceHacks/SurvivCheatInjector#297]
Pans dont drop frequently nowadays, but when they do, you can seriously up your kills per time unit by heavily reducing incoming damage by simply deflecting it. I remember even a few times i managed to deflect AWM-S rounds! It would be really cool to see deflelecting bullets automated.
- algorithm that controls player rotation (and maybe some movement) to deflect (most of) incoming bullets
- toggle/hold enabling options to give more control over its usage

**Comment by IceHacks** [comment]
anything is possible!

**Comment by e45d6rtfuvyig** [comment]
this is genius

**Comment by DamienVesper** [comment]
Stop hacking, kid.

**Comment by e45d6rtfuvyig** [comment]
hmmm, and if i dont what are u going to do?

**Comment by SniperXKiller** [comment]
@DamienVesper  GET WRECKED

**Comment by SniperXKiller** [comment]
@DamienVesper  YOUR SO STUPID, WHEN YO MAMMA WAS FARTING, YOU SAID:
" Mom, what are you cooking, it smells so good!"

**Comment by e45d6rtfuvyig** [comment]
lol

**Comment by SniperXKiller** [comment]
@e45d6rtfuvyig Do you want me to rub it in DamienVesper's face even more? (Does he even HAVE a face?)

**Comment by e45d6rtfuvyig** [comment]
Please do.

**Comment by kirillovmr** [comment]
Pan hero will be released soon. we are working on it

**Comment by 068scar** [comment]
lol

**Comment by humphreygaming** [comment]
pan hero is here

**Comment by e45d6rtfuvyig** [comment]
NICE!!
