### ISSUE TITLE
Wrong build folder provided ❌🔗

### ISSUE THREAD

**Issue by khvnhtung** [IceHacks/SurvivCheatInjector#3]
The link to the build folder in Readme.md is not the correct link to build folder
Change it from
https://github.com/IceHacks/SurvivCheat/tree/master/build
To
https://github.com/IceHacks/SurvivCheatInjector/tree/master/build

**Comment by IceHacks** [comment]
ok thanks

**Comment by IceHacks** [comment]
yeah, I had renamed this.
