### ISSUE TITLE
this is wierd

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#300]
SycoBak#0001(https://surviv.io/stats/sycobak0001)
this person has 46 kills in a solo game. that would be a world record. first how is that even possible and second why isnt he on the surviv all time leaderboards he is probably hacking he has only played a few games

**Comment by u1qqlv** [comment]
he is https://surviv.io/stats/

**Comment by humphreygaming** [comment]
@gautamgxtv it's a secret :)

**Comment by gautamgxtv-V3** [comment]
please tell me how he did that is it part of 'destroying surviv'? pls tell me i am ur biggest fan Pls Pls tell me
