### ISSUE TITLE
Streamer  mode

### ISSUE THREAD

**Issue by gautamgxtv-V3** [IceHacks/SurvivCheatInjector#303]
A mode that disables all GUI of aimbot

For example:

- Smoke grenade texture

- Aimbot, ESP, SpinBot, Follow other aimbot things(yeah can be customized manually but this mode should automatically turn these of)

-Icehacks logo on main screen(even on dark mode off)

- any other visual thing of the aimbot

This is basically for people who want to use aimbot but they are streamoing or dont want the aimbot to be shown visually so ppl think they are not hacking

**Comment by gautamgxtv** [comment]
why cant you add this?
