### ISSUE TITLE
Highlight usable loot on the screen

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#304]
I imagine the following: ammo of the types you don't have maxed out is surrounded with a small static white square border; usable permanent loot (armor, helmets, backpacks) has a pulsing circular border.

**Comment by IceHacks** [comment]
I guess. If for some reason you didn't want autoloot.

**Comment by Nihilistics** [comment]
I do use autoloot; however, when you e.g. have a massive pile of loot in the club and outside it and enemies from all sides, it would be helpful to shorten the time you need to analyse this whole mess to pick out the useful parts.

**Comment by IceHacks** [comment]
oh ok
