### ISSUE TITLE
scrims and private server support

### ISSUE THREAD

**Issue by Nighthawk605** [IceHacks/SurvivCheatInjector#31]
working aimbot for http://c79geyxwmp1zpas3qxbddzrtytffta.ext-twitch.tv/c79geyxwmp1zpas3qxbddzrtytffta/1.0.2/ce940530af57d2615ac39c266fe9679d/index_twitch.html?anchor=panel&language=en&mode=viewer&state=released&platform=web&popout=true
and
http://www.twitch.tv/popout/timmy_bits/extensions/c79geyxwmp1zpas3qxbddzrtytffta/panel

thanks

**Comment by humphreygaming** [comment]
since it doesn't get updated, yea we could do it

**Comment by IceHacks** [comment]
They are made differently then Surviv.io more difficult than you think.
