### ISSUE TITLE
Use collisions is bugged

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#312]
**Describe the bug**
Breakable objects are not taken into account as it always was.

**Expected behavior**
Breakable objects must be taken into account with the "Use collisions" feature.

**Screenshots**
N/A

**Cheat version**
2.0.6

**Chromium version**
80.0.3987.132

**Comment by StabbyAlbert** [comment]
Please record a clip

**Comment by MoonRoller** [comment]
Use collisions is true, there are breakable objects between me and the enemy.
AIM does not take into account the collision.

https://i.imgur.com/rPoE3la.gifv
