### ISSUE TITLE
FollowBot sometimes is bugged

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#313]
**Describe the bug**
The bot doesn't always follow the closest or leader player, instead follows another player of the team or in the case of a duo moves to another place.

The same happens when one moves too far from the bot, the bot stops following and takes another direction.

**Expected behavior**
In the old extension if remember correctly the bot followed the player who was closest, maybe we could have an option to choose whether to follow the player that is closest or the leader (first player of the team).

**Screenshots**
N/A

**Cheat version**
2.0.6

**Chromium version**
80.0.3987.132

**Comment by StabbyAlbert** [comment]
It's not, please record if it is a striking issue

**Comment by MoonRoller** [comment]
![image](https://user-images.githubusercontent.com/54990448/76370215-e7f04380-6314-11ea-97da-52e4c85d7ca2.png)
