### ISSUE TITLE
SmartSwitch is bugged

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#314]
**Describe the bug**
I don't use SmartSwitch myself, but SniperSwitch.
However, FollowBot use SmartSwitch (for obvious reasons) and I have noticed sometimes the bots switch weapon without firing, just keep switching weapons constantly.

**Expected behavior**
Perhaps the failure is due to the fact that cannot correctly choose which weapon to use or both match the parameters to be used at that time (for example if you have two similar weapons).

**Screenshots**
I could get them if they were useful, although I think you understand what I say and it is easy to check.

**Cheat version**
2.0.6

**Chromium version**
80.0.3987.132

**Comment by StabbyAlbert** [comment]
See existing

**Comment by MoonRoller** [comment]
> See existing

I can't see any open issues with the same problem and the closed issues are supposed to have been resolved, or not?

**Comment by RubyGirl777** [comment]
This happens to me sometimes and it's getting annoying.
