### ISSUE TITLE
Disable AIM on shoot

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#315]
**Describe the bug**
The key bind isn't working with AIM on shoot. You can't disable AIM on shoot.

**Expected behavior**
Be able to disable AIM on shoot with the assigned key bind.

**Screenshots**
N/A

**Cheat version**
2.0.6

**Chromium version**
80.0.3987.132

**Comment by StabbyAlbert** [comment]
please leave this as enhancement

**Comment by MoonRoller** [comment]
> please leave this as enhancement

You can change the label to enhancement and/or add to the to do list.
