### ISSUE TITLE
AutoAttack bug

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#316]
**Describe the bug**
When you are very close to the enemy and we have AutoAttack enabled, this does not allow us to shoot. I'm not sure if it happens all the time or only in some cases, but it has happened to me several times.

**Expected behavior**
Do not block the shot (mouse click) or shorten the distance to AutoAttack with melee.

**Screenshots**
N/A

**Cheat version**
2.0.6

**Chromium version**
80.0.3987.132

**Comment by StabbyAlbert** [comment]
not a issue

**Comment by MoonRoller** [comment]
This is an important problem, trying to attack with melee when the distance is very large and on top of not allowing the enemy to be shot only results in being shot and killed, nonsense.
