### ISSUE TITLE
SniperSwitch sometimes is bugged

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#317]
**Describe the bug**
This happens very rarely really, but sometimes the quickswitch is not done correctly.

**Expected behavior**
Always quickswitch correctly.

**Screenshots**
N/A

**Cheat version**
2.0.6

**Chromium version**
80.0.3987.132

**Comment by StabbyAlbert** [comment]
Then switch manually

**Comment by MoonRoller** [comment]
@StabbyAlbert then close the GitHub project or don't allow issues if you don't want solve bugs.

I'm trying to contribute to the project by reporting the errors that I have found, since there is no source to simply improve it and make a PR.
