### ISSUE TITLE
AutoAttack FOV

### ISSUE THREAD

**Issue by MoonRoller** [IceHacks/SurvivCheatInjector#318]
**Describe the feature you'd like**
AutoAttack FOV
 
**Describe alternatives you've considered**
1. Add FOV option to AutoAttack
2. Option to disable AIM FOV on AutoAttack

**Additional context**
The FOV option may be useful for aiming, but leaves the autoattack function unusable (or at least much less effective).

Melee attacks are very effective (one of the best things your extension has), I would like them to be less bot like and more human like too (if possible).

**Comment by StabbyAlbert** [comment]
I don't understand what your saying

**Comment by MoonRoller** [comment]
@StabbyAlbert What do you not understand?
