### ISSUE TITLE
R.I.P Ice

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#319]
i saw his video on yt

does this mean no more hacks??????????

pls humpry at least you update hackssss

**Comment by humphreygaming** [comment]
he is gone, he is gone

**Comment by Griff0118** [comment]
Is he dead?

**Comment by Griff0118** [comment]
Humphrey these hacks can still pull through we just need to ask people on discord servers if they are good at javascript, the only way we can make this survive is if we search for a coding pro. If this is the last of the hacks I would like to say it's been fun, but you know all good things have to come to an end.

**Comment by Griff0118** [comment]
Humphrey without you there will be nothing left. If all goes to crap, the last option we have for hacks is to give the code to iblissin so he can support the hacks by combining them.

**Comment by gautamgxtv** [comment]
i asked for the source
i am not rlly good programmer in javascript(better at python)
anyways if he gives me the source i will try to fork
not sure depends on how complex the code is

**Comment by gautamgxtv** [comment]
i will try to search for new hacks
i will update u guys here
nice **hacking** with you guys
