### ISSUE TITLE
uhhh

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#321]
`Uncaught TypeError: Cannot read property 'plugins' of undefined
    at i.$ (<anonymous>:9:464036)
    at WebSocket.Et.ws.onopen (<anonymous>:9:442549)`

**Comment by AtomicSlumber** [comment]
And it looks like you can't start a game on surviv.io with the extension :(

**Comment by StabbyAlbert** [comment]
ok simp

**Comment by AtomicSlumber** [comment]
lol

**Comment by BopItFreak** [comment]
welp

**Comment by gautamgxtv-V3** [comment]
ICE WE NEED YOU!!!

**Comment by AlessioSwire** [comment]
No longer able to start a game with extension enabled...

**Comment by gautamgxtv** [comment]
we need a javasceript coding pro
