### ISSUE TITLE
Where is IceHacks?

### ISSUE THREAD

**Issue by ay232** [IceHacks/SurvivCheatInjector#324]
Who knows - where is IceHack and why he gone?

**Comment by u1qqlv** [comment]
I know he is in USA :D, he gone because he needs to study...

**Comment by ay232** [comment]
It seems to me that it would be great just to collect donations so that IceHacks continues its work.

**Comment by gautamgxtv** [comment]
yeah

**Comment by humphreygaming** [comment]
IceHacks is in Hawaii, currently on a Christian holiday (lent). After that, he is gone for an indefinete time (more info here https://www.youtube.com/watch?v=quBK_-qh8yg)
