### ISSUE TITLE
whaaaa?

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#325]
wait there is going to be an update??!!!!!
yay

**Comment by AlessioSwire** [comment]
I **REALLY** hope it's true.

**Comment by WinterManTM** [comment]
it might ??

**Comment by AlessioSwire** [comment]
> it might ??

Well coronavirus quarantine **does** help in working more on this lol

**Comment by IceHacks** [comment]
2.0.6 just worked however I'm not going to be playing surviv. I'll just be teaching others how to update the cheat from now on.

**Comment by gautamgxtv** [comment]
okay thanks man
