### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by xXAngelDustXx** [IceHacks/SurvivCheatInjector#326]
Hello, i have used IceHacks before the Current update
I went to download the Latest.zip file
but none was present
If either its not there yet or there is a different way now, I would love to know ASAP
Keep on With the great hacks!

**Comment by humphreygaming** [comment]
elaborate please

**Comment by WinterManTM** [comment]
?

**Comment by AlessioSwire** [comment]
> Hello, i have used IceHacks before the Current update
> I went to download the Latest.zip file
> but none was present
> If either its not there yet or there is a different way now, I would love to know ASAP
> Keep on With the great hacks!

yeah get in line lol

**Comment by WinterManTM** [comment]
line?

**Comment by gautamgxtv-V3** [comment]
The hacks r patched anyways

**Comment by gautamgxtv-V3** [comment]
It’s called surviv.cheat.injector or whatever

**Comment by xXAngelDustXx** [comment]
Well, for the instrctions on how to get icehacks, it says to get Latest.zip file
i did it the first time but now its not there
