### ISSUE TITLE
Version 2.0.7 not working

### ISSUE THREAD

**Issue by picao6969** [IceHacks/SurvivCheatInjector#328]
i've extracted the surviv cheat injector and i tried multiple times to download it on chrome extenions but it still doesnt work for some reason :/ can u guys fix  that?

Cheat Version 2.0.7

**Comment by WinterManTM** [comment]
Yes Join https://discord.gg/NTZ5s9g 2.0.8 Is There

**Comment by gautamgxtv** [comment]
2.0.7 is the same thing as 2.0.6 except for easier install... all code is the same
