### ISSUE TITLE
collab?

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#333]
sup its me coder. 
Can I collab on the easiest thing possible.
I dont know much js I admit it.
But if you could let me collab on like a really easy thing it would be very nice.
thanks man

**Comment by u1qqlv** [comment]
no, you spy! you want the code so you can make the hack stop working...

**Comment by gautamgxtv** [comment]
what! no.... I just wanted to try the feedbot thing

**Comment by Synthity** [comment]
feed bot isnt free dude u just want to steal it ?
