### ISSUE TITLE
2.0.8 aimbot revision

### ISSUE THREAD

**Issue by IcehackeurSurvivIo** [IceHacks/SurvivCheatInjector#334]
I can't install version 2.0.8 its bug :c

**Comment by gautamgxtv** [comment]
the new aimbot is trash.
i am still using v2.0.6 because its better

**Comment by Synthity** [comment]
🤡

**Comment by BopItFreak** [comment]
Please undo the new aimbot
It's bad

**Comment by oofgangcrypin** [comment]
facts, aimbot aint as good
