### ISSUE TITLE
FollowBot multiple ppl

### ISSUE THREAD

**Issue by gautamgxtv** [IceHacks/SurvivCheatInjector#335]
how do I get many followbots in my game
some ppl have like 3 followbots
I only have 1 pc
Whenever I open multiple tabs and enable followbot, it doesnt work
the players just stands still and I have to manually control them
but if i have just one tab open with follow bot it works
tell me pls how to fix this

**Comment by Synthity** [comment]
has to be on "Auto Fill" if i'm correct
