### ISSUE TITLE
thank u alot for hack

### ISSUE THREAD

**Issue by zerodark088888** [IceHacks/SurvivCheatInjector#340]
i used to have some issues with aim bot

but after update of 2.0.8 i really think aim bot is best and hack is so easy to use
and i even get like 20-30 kills easly 
thanks for hack

**Comment by AlessioSwire** [comment]
30 kills? The best I get is 17 kills in prime matches lol

**Comment by AlessioSwire** [comment]
> i used to have some issues with aim bot
> 
> but after update of 2.0.8 i really think aim bot is best and hack is so easy to use
> and i even get like 20-30 kills easly
> thanks for hack

30 kills? The best I get is 17 kills in prime matches lol

**Comment by zerodark088888** [comment]
> > i used to have some issues with aim bot
> > but after update of 2.0.8 i really think aim bot is best and hack is so easy to use
> > and i even get like 20-30 kills easly
> > thanks for hack
> 
> 30 kills? The best I get is 17 kills in prime matches lol

well it depend upon in which server ur playing and how much players are there in that match

**Comment by AlessioSwire** [comment]
> > > i used to have some issues with aim bot
> > > but after update of 2.0.8 i really think aim bot is best and hack is so easy to use
> > > and i even get like 20-30 kills easly
> > > thanks for hack
> > 
> > 
> > 30 kills? The best I get is 17 kills in prime matches lol
> 
> well it depend upon in which server ur playing and how much players are there in that match

I always play on Europe server and usually get around 70 players per match

**Comment by zerodark088888** [comment]
> > > > i used to have some issues with aim bot
> > > > but after update of 2.0.8 i really think aim bot is best and hack is so easy to use
> > > > and i even get like 20-30 kills easly
> > > > thanks for hack
> > > 
> > > 
> > > 30 kills? The best I get is 17 kills in prime matches lol
> > 
> > 
> > well it depend upon in which server ur playing and how much players are there in that match
> 
> I always play on Europe server and usually get around 70 players per match

i play in asia  server with like 20-30 players per match  but  some times i get  70 so i can get more kills lol
