### ISSUE TITLE
the autoshoot stoped working 

### ISSUE THREAD

**Issue by silver766** [IceHacks/SurvivCheatInjector#342]
**Describe the bug**
It's NOT WORKING one day I log on with the hack and its not auto-attacking even when I set it to . i tryed  reloading i tryed super reloading ( ctrl+f5) but its not working like why i even messed with the setting like plz pix 

**Expected behavior**
it never hit or attacked or even opened a crate but it did make a line showing me where it is 

**Cheat version**
(ex: 2.0.8)

**Chromium version**
 uuuuuuuuuuuuuu the latest one

**Comment by Synthity** [comment]
works for me
