### ISSUE TITLE
AUTOHEAL doesnt work XD

### ISSUE THREAD

**Issue by 068scar** [IceHacks/SurvivCheatInjector#343]
**autoheal**
doesnt work automatcly make youtube vid on how to make it work?

**Expected behavior**
mouse 3 press i did it but still doesnt work PLs REPLY OR FIx, 

**Chromium version**
(go to chrome://version/)

**Comment by Synthity** [comment]
hmm

**Comment by 068scar** [comment]
hmmmmmm....... IDK
