### ISSUE TITLE
2.0.9 doesn't work

### ISSUE THREAD

**Issue by me7513** [IceHacks/SurvivCheatInjector#346]
Additional settings won't pop up and it won't load into games. When I try to get into a game it just says "host closed connection."

**Comment by zerodark088888** [comment]
same here

**Comment by zerodark088888** [comment]
> Additional settings won't pop up and it won't load into games. When I try to get into a game it just says "host closed connection."

same here

**Comment by AlessioSwire** [comment]
> Additional settings won't pop up and it won't load into games. When I try to get into a game it just says "host closed connection."

Same, it just stopped working and I get the same error.

**Comment by gautamgxtv** [comment]
same
