### ISSUE TITLE
CANT ESCAPe cheat menu

### ISSUE THREAD

**Issue by coder580** [IceHacks/SurvivCheatInjector#35]

**Comment by BobTheFish1238** [comment]
im having same problem

**Comment by IceHacks** [comment]
Press "n" no caps lock or shift.

**Comment by IceHacks** [comment]
You can see it here:
![image](https://user-images.githubusercontent.com/38994479/61006508-31ac0880-a306-11e9-825b-f1160dc42fc8.png)
