### ISSUE TITLE
Auto Grenade Thrower

### ISSUE THREAD

**Issue by magikol** [IceHacks/SurvivCheatInjector#360]
I have an idea to help make this hack a little better. You should probably add an auto grenade thrower feature that throws grenades or smokes for you at the right time and place. Please take this request to heart!
 
Features:

- The Auto Thrower should be able to work with the grenade timer

- There should also be an aim for it as well for precision.

**Comment by Synthity** [comment]
Hmm Sounds Cool, Might try to add

**Comment by 068scar** [comment]
awesome but what if u blow urself instead

**Comment by Qbert2030** [comment]
well dont
