### ISSUE TITLE
The hack doesn't even load and the download file is gone weird. 

### ISSUE THREAD

**Issue by Zonxiarnbuvbuv** [IceHacks/SurvivCheatInjector#363]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by Zonxiarnbuvbuv** [comment]
The download file has no manifest and other stuffs

**Comment by 068scar** [comment]
yea but wait and play some games withour hacks later he will fix

**Comment by Synthity** [comment]
stop cryin were workin on it
