### ISSUE TITLE
The download file doesn't have a manifest or any .json files. I tried downloading 50 times and there are no supporting files. Please just update this. plzplzplzplpzpllzplzplzplzlpzlzlpz

### ISSUE THREAD

**Issue by Zonxiarnbuvbuv** [IceHacks/SurvivCheatInjector#364]
**Describe the bug**
The hack doesn't load and the download doesn't have the necessary files.

**Expected behavior**
There should be 2 folders and a few files, but instead there is one folder called "archive" and a readme, and archive.md document and contribute.md file. 

**Screenshots**
I don't have any screenshots and im sure you would know if you just downloaded it yourself.

**Cheat version**
1.3.696969

**Chromium version**
(go to chrome://version/)

**Comment by 068scar** [comment]
same i got it but doesnt work

**Comment by Synthity** [comment]
stop cryin were workin on it
