### ISSUE TITLE
"Host Closed The Connection Error"

### ISSUE THREAD

**Issue by RubyGirl777** [IceHacks/SurvivCheatInjector#365]
So I just recently installed the 2.0.9b ZIP and when I tried clicking play  buttons it kept saying "Host Closed The Connection." Can you please fix this?

The Error:
![Screenshot-20200401235143-321x391](https://user-images.githubusercontent.com/51972983/78211862-cac21700-7473-11ea-8d29-e472256e52f8.png)
The proper extension:
![Screenshot-20200401235153-491x249](https://user-images.githubusercontent.com/51972983/78211869-ceee3480-7473-11ea-993f-37ff77a89ad1.png)

**Comment by Zonxiarnbuvbuv** [comment]
Same bruh!

**Comment by 068scar** [comment]
it doesnt even let me play lol

**Comment by BopItFreak** [comment]
bruh moment

**Comment by Synthity** [comment]
stop cryin were workin on it lmao

**Comment by RubyGirl777** [comment]
Thanks.
