### ISSUE TITLE
Say at least thank you to Humphrey for his work! He will surely fix this! Thank you Humphrey! :) cheers!!! 

### ISSUE THREAD

**Issue by RAR122112** [IceHacks/SurvivCheatInjector#366]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zonxiarnbuvbuv** [comment]
Thanks Humphrey @humphreygaming

**Comment by 068scar** [comment]
thn @humphreygaming

**Comment by BopItFreak** [comment]
bruh moment

**Comment by caccasanta12** [comment]
go HUMPYYYY <3 THANK YOU <3

**Comment by Synthity** [comment]
yyeahhhh humpyyyyyyyyyyyyyyyyyyy lmao

**Comment by e45d6rtfuvyig** [comment]
Thank you!
