### ISSUE TITLE
I cant join to the game

### ISSUE THREAD

**Issue by Keolass** [IceHacks/SurvivCheatInjector#369]
I cant join to the game, connection error

**Comment by caccasanta12** [comment]
do not worry , Humphrey will fix it! :)

**Comment by julienloveshacks** [comment]
just be paintent

**Comment by Synthity** [comment]
stop cryin were workin on it lmao 🤣

**Comment by e45d6rtfuvyig** [comment]
Thank you guys. But (it would be awesome) if you could finish it before 50v50 ends!
