### ISSUE TITLE
Revert changes for aimbot

### ISSUE THREAD

**Issue by acimanx** [IceHacks/SurvivCheatInjector#37]
Please return the ability to use a second mouse for aimbot, or make it optional.

**Comment by pilgrimoflight** [comment]
+ TO THIS issue. Please its important .
I dont like full aimbot. It shoots when enemy is behind wall too
 Also where is gone ability to zoom?(

**Comment by IceHacks** [comment]
@acimanx Yes, I agree. Autoaim is for noobs. I actually am adding it. This new cheat injector just had me restart everything.

@pilgrimoflight I am busy re-adding everything.
