### ISSUE TITLE
Humpy we love you!!! GO beat the devs ! Thank you for your kind work! :)

### ISSUE THREAD

**Issue by caccasanta12** [IceHacks/SurvivCheatInjector#370]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mecreuda** [comment]
Hello, it stopped working on the south america server. already downloaded and installed the latest version but it doesn't work.

**Comment by caccasanta12** [comment]
Hola hablas espanol? el man que se llama Humphrey lo va a hacer funcionar ! Todo va a salir bien! En algunos dias (o puede ser que tambien hoy lo haga! ) :)

**Comment by Synthity** [comment]
ty humpyhrey 🤣

**Comment by e45d6rtfuvyig** [comment]
Wait are you guys working on the hacks? If you are I am more than willing to help you test. Comment if you need me :)

**Comment by RAR122112** [comment]
yes we are working on hacks!!! go tell humphrey that you can do it too! maybe you can team with him :) HE IS on DISCORD! the name is HumphreyGaming#3408 :) GOOO! :)
