### ISSUE TITLE
"Host closed the connection." 

### ISSUE THREAD

**Issue by chargedpika** [IceHacks/SurvivCheatInjector#371]
it aint loading in. but whatever. 

also, would it be possible to allow older versions of this to still be playable, instead of trying to load into a game, and it says the hacks are outdated?

like, how windows 10 is outdated, but still usable? 

idk, just a thought.

**Comment by mi99cool** [comment]
Hi, stop creating new issues about the host closed connection they now this and are working on it ffs. there is about 5 already about this same issue pay attention.

**Comment by Synthity** [comment]
bruh were going to fix read the other 80 same shit about this
