### ISSUE TITLE
plz fix this bug

### ISSUE THREAD

**Issue by RuStyNice** [IceHacks/SurvivCheatInjector#374]
are yall going to fix it cause im bored now im in corentine and im super bored

**Comment by zerodark088888** [comment]
> are yall going to fix it cause im bored now im in corentine and im super bored

same here bro

but try to understand he is doing his best to fix it 
and think soon it will be

**Comment by Synthity** [comment]
shut up we will, its not the end of the world

**Comment by strikingforce909** [comment]
i mean, i am still proe without hacks, since i only use the aimbot part it really makes little difference foir me, other than the part of my shots not hitting as much as they normally do

**Comment by oofgangcrypin** [comment]
Y’all killing me 😂 So funny… LET THE DUDES DO THEIR WORK
