### ISSUE TITLE
FOOLS STOP CREATING NEW ISSUES ABOUT THIS CONNECTION ERROR. IF I WAS CREATING THIS HACK FOR YOU ALL I WOULD STOP DOING IT, UNGRATEFUL MORONS

### ISSUE THREAD

**Issue by mi99cool** [IceHacks/SurvivCheatInjector#377]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by Synthity** [comment]
yes we might stop if yall keep going

**Comment by mi99cool** [comment]
that something you could consider or you could do is not release the new hack for at least few days and let everyone shut up. or delay the release if new issues are created about the same thing that's the only way I can think of for people to start showing appreciation. Right now it all me me me I want hack now now now, not thinking that you guys are giving your time to get this hack to them.  

I for one appreciate what you coders do thank you
