### ISSUE TITLE
KONGREGATE RULES!

### ISSUE THREAD

**Issue by ILoveKongregate** [IceHacks/SurvivCheatInjector#380]
**KONGREGATE RULES HUMPHREY SUCKS I HOPE HE NEVER FINDS OUT HOW TO FIX THE ANTIVIRUS YOU STUPID LITTLE KID!**

**Comment by magikol** [comment]
WTF

**Comment by ILoveKongregate** [comment]
**ISSUE CLOSED STOP WHINING KONG RULES GET OVER IT I SUPPORT THEM TOO BY DONATING AND CLICKING ON THEIR ADS!!!!!**

**Comment by simpleperson123** [comment]
is that a troll?
