### ISSUE TITLE
PSA: You guys are stupid

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#381]
Cheats were never patched, did you not know that April Fools exists?

**Comment by magikol** [comment]
Now im pissed

**Comment by oofgangcrypin** [comment]
This some booshit

**Comment by magikol** [comment]
Why did you delete my feature request btw?

**Comment by humphreygaming** [comment]
i closed all of them thanks to you guys spamming this place up

**Comment by mi99cool** [comment]
@humphreygaming excellent lmao

**Comment by Synthity** [comment]
skids

**Comment by zerodark088888** [comment]
> i closed all of them thanks to you guys spamming this place up

man like really ? 

well maybe that was reason it was saying that in additional setting version 2.0.6 

ut it created big problem for all users lol

**Comment by RuStyNice** [comment]
BRuuhhhh u made me delete the extension

**Comment by caccasanta12** [comment]
wtf you are a weirdo . Ice was better . Wtf is this service. I thought you were a different person! you damaged us xD

**Comment by mi99cool** [comment]
damaged you wtf lol

**Comment by Zonxiarnbuvbuv** [comment]
What does "cheats were never patched" mean? Does that mean you didn't fix them? Bruh they still ain't working.

**Comment by Zonxiarnbuvbuv** [comment]
BRUH

**Comment by AlessioSwire** [comment]
> Cheats were never patched, did you not know that April Fools exists?

lmaoooo

I just switched to another game waiting for you to fix the cheats instead of spamming the entire place up, but I see that literally NO ONE did the same lol

**Comment by SniperXKiller** [comment]
> Cheats were never patched, did you not know that April Fools exists?

Wow. Now you should do something for Christmas.
