### ISSUE TITLE
GAY

### ISSUE THREAD

**Issue by caccasanta12** [IceHacks/SurvivCheatInjector#382]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by caccasanta12** [comment]
we' re not stupid , you are the gay who trolled us, wtf is this service! We are in fucking quarantine and hacking is a way to do something else. Fuck you little hamster of shit , ice was better xD

**Comment by caccasanta12** [comment]
we' re not stupid , you are the gay who trolled us, wtf is this service! We are in fucking quarantine and hacking is a way to do something else. Fuck you little hamster of shit , ice was better xD

**Comment by mi99cool** [comment]
then contact ice for the hacks then hes busy soon these other coders will be busy too so no more hack. also ungrateful much.

**Comment by Synthity** [comment]
ice isnt giving them away

**Comment by humphreygaming** [comment]
@caccasanta12 ice did the same thing last april fools, don't act all high and mighty on me, script kiddie
