### ISSUE TITLE
Download package is weird. There is no manifest or anything but just an archive folder with a ton of ZIP files in them.What do i do?

### ISSUE THREAD

**Issue by Zonxiarnbuvbuv** [IceHacks/SurvivCheatInjector#385]
![Screenshot 2020-04-03 at 1 37 49 PM](https://user-images.githubusercontent.com/62414105/78327834-550f9580-75b0-11ea-8dc9-5bcb21d16470.png)

**Comment by zerodark088888** [comment]
see its not a problem u downloaded wrong package
go to https://github.com/IceHacks/SurvivCheatInjector/releases/tag/2.0.9
and download first pack named Surviv.io.Cheat.Injector.2.0.9  there is dot after each word lol u can 
understand from that  in name of that pack 
first one not the 2nd or 3rd one  
2nd and  3rd one contains old versions 
only first one is latest and best version  2.0.9
