### ISSUE TITLE
NO SPINBOT

### ISSUE THREAD

**Issue by gitgitgithubhubhub1** [IceHacks/SurvivCheatInjector#39]
THERE IS NO SPINBOT

**Comment by humphreygaming** [comment]
u need code

**Comment by DamienVesper** [comment]
just stop using aimbot period

**Comment by IceHacks** [comment]
@DamienVesper You are so toxic lol. @gitgitgithubhubhub1 You too.

**Comment by DamienVesper** [comment]
@IceHacks nah aimbotters are just trash.
