### ISSUE TITLE
Auto Grenade Thrower

### ISSUE THREAD

**Issue by magikol** [IceHacks/SurvivCheatInjector#390]
I have an idea to help make this hack better. You should probably add an auto grenade thrower feature that throws grenades or smoke grenades for you so they can explode at the right time and place to get extra kills.
 
Features:

- The Auto Thrower should be able to work with the grenade timer,

- There should also be an aim for it as well for precision. 

- It should be able to throw the grenade near the opponents or an explosive next to them.

**Comment by DamienVesper** [comment]
Hacking is bad.
