### ISSUE TITLE
Cheats r brokeh again

### ISSUE THREAD

**Issue by CharmandertheEPIC** [IceHacks/SurvivCheatInjector#393]
2.0.9 broke something, aimbot no longer works right. It's almost like as soon as it locks on, something triggers the stupid spinbot. aiming is nonexistent

**Comment by AlessioSwire** [comment]
> 2.0.9 broke something, aimbot no longer works right. It's almost like as soon as it locks on, something triggers the stupid spinbot. aiming is nonexistent

Weird. I'm using the same version and everything works just fine.

**Comment by gh67uyyghj** [comment]
maybe clean your browser cache and try again

**Comment by CharmandertheEPIC** [comment]
Never mind, for some reason the velocity multiplier was set to 100. Everything is good
