### ISSUE TITLE
Frozen on loading screen

### ISSUE THREAD

**Issue by Zonxiarnbuvbuv** [IceHacks/SurvivCheatInjector#397]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by BlTWISE** [comment]
Can you dumbasses even fill the error template properly?

**Comment by humphreygaming** [comment]
Template not filled, NEInfo
