### ISSUE TITLE
Auto loot

### ISSUE THREAD

**Issue by system123786** [IceHacks/SurvivCheatInjector#4]
Auto loot is a bit dogey because it sometimes automatically picks up weapons when I already have 2 and this it bad because it can mess up a fight if you are in one

**Comment by IceHacks** [comment]
That's just because there is a weapon near the loot it is trying to pick up. I will try fixing later today. Sorry for the inconvenience.

**Comment by IceHacks** [comment]
@system123786 how would disabling autoloot when you are shooting work for you?

**Comment by system123786** [comment]
yes that would work but sometimes what happens is that if u move over someweapons even when not shooting it will still pick it up even though 2 weapons are still in slots

**Comment by IceHacks** [comment]
@system123786 I am pushing an update that should fix this issue.
