### ISSUE TITLE
Idea to add to aiming

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#40]
So...I was thinking...the stream option is not there anymore...

_Can you please @IceHacks  sama add it back?_

Making the aiming circles aka BoxLockon invisible. Same with the white line

**Comment by u1qqlv** [comment]
and add scroll zoom too

**Comment by TesterBoy22** [comment]
Thats crazy angel, a few months ago you were complaining about cheats and now you’re using ours?

**Comment by DamienVesper** [comment]
cheats break the game ^^^

**Comment by IceHacks** [comment]
@TheSatanicAngeI I'm not going to help you if you don't update your cheat version. I added "hiding the boxlockon lines" last week. Also, the stream option never worked.

**Comment by IceHacks** [comment]
And @u1qqlv you don't need to say that in every open issue. It's on my list, just not high because it's stupid.

**Comment by u1qqlv** [comment]
@IceHacks - or at least add +10-20% to the current zoom, because sometimes I see red enemy lines but i do not see the enemy... maybe because monitor is not square :D

**Comment by IceHacks** [comment]
Been there done that.
