### ISSUE TITLE
Loading delay problem on v2.0.5

### ISSUE THREAD

**Issue by BlTWISE** [IceHacks/SurvivCheatInjector#401]
**Describe the bug**
Initially loading the page hangs and says waiting for chat-oven.glitch.me...for around 30 seconds, then eventually loads.

**Expected behavior**
It should not hang and load instantly.

**Cheat version**
2.0.5

**Chromium version**
80.0.3987.163 (Official Build) (64-bit) (cohort: Stable)

**Other Details**
This just started happening today.

**Comment by humphreygaming** [comment]
there is a reason why versions under 2.0.8 are unsupported
