### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by likseBSMC** [IceHacks/SurvivCheatInjector#405]
**Describe the bug**
Joining a game will result in "Host closed the connection."

**Expected behavior**
Actually joining the game.

**Screenshots**
https://i.imgur.com/gOYp43P.png

**Cheat version**
2.0.9

**Chromium version**
81.0.4044.113 (Official Build) (64-bit) (cohort: 81_Win_92)

(Tested on 4 different IPs)

**Comment by NotLima** [comment]
Hey everyone, as you know, Icehacks does not currently work. Our devs have no motivation to fight against Kongregates anticheat. For two years we developed this cheat for free. We ask you to pitch in $.30-1 to help us continue developing the cheat.   https://www.paypal.me/LimaTM
