### ISSUE TITLE
WON"T CONNECT, BUT WITHOUT AIMBOTS, IT WILL!!!

### ISSUE THREAD

**Issue by jspetrini1** [IceHacks/SurvivCheatInjector#406]
WIX IT NOW

**Comment by NotLima** [comment]
Hey everyone, as you know, Icehacks :tm: does not currently work. Our devs have no motivation to fight against Kongregates anticheat. For two years we developed this cheat for free. We ask you to pitch in $.30-1 to help us continue developing the cheat.   https://www.paypal.me/LimaTM

**Comment by julienloveshacks** [comment]
my moms credit card will serve you well
