### ISSUE TITLE
SurvivCheatInjectorQuestion

### ISSUE THREAD

**Issue by SenseiKat** [IceHacks/SurvivCheatInjector#407]
So I accidentally cleared my settings. How do I get them back?

**Comment by SenseiKat** [comment]
![image](https://user-images.githubusercontent.com/64160094/80160262-05563580-8582-11ea-8f1c-c2307106c692.png)

**Comment by NotLima** [comment]
Hey everyone, as you know, Icehacks™️ does not currently work. Our devs have no motivation to fight against Kongregates anticheat. For two years we developed this cheat for free. We ask you to pitch in $.30-1 to help us continue developing the cheat. https://www.paypal.me/LimaTM

**Comment by SenseiKat** [comment]
This hack still works for me, but I accidentally deleted my settings. How
do I get them back?

**Comment by simp3** [comment]
has anyone donated?

**Comment by sld6416** [comment]
@humphreygaming Is it true about donate?

**Comment by Vodka-ph** [comment]
> Привет всем, как вы знаете, Icehacksв настоящее время не работает. Наши разработчики не имеют никакой мотивации, чтобы бороться с античитом Kongregates. В течение двух лет мы разрабатывали этот чит бесплатно. Мы просим вас внести $ 30-1, чтобы помочь нам продолжить разработку чита. https://www.paypal.me/LimaTM




I do not have PayPal where else can I transfer money?

**Comment by jspetrini1** [comment]
Do u have cash app
