### ISSUE TITLE
Hack is not working!!

### ISSUE THREAD

**Issue by hank10322** [IceHacks/SurvivCheatInjector#410]
![image](https://user-images.githubusercontent.com/45732841/80215843-bbe41400-866f-11ea-9874-453d4eeeddb5.png)

**Comment by NotLima** [comment]
Hey everyone, as you know, Icehacks ™️ does not currently work. Our devs have no motivation to fight against Kongregates anticheat. For two years we developed this cheat for free. We ask you to pitch in $.30-1 to help us continue developing the cheat. https://www.paypal.me/LimaTM
