### ISSUE TITLE
Host closed the connection? (chomeos)

### ISSUE THREAD

**Issue by dakillet** [IceHacks/SurvivCheatInjector#411]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by dakillet** [comment]
Wont start the game after injecting the scripts, saying that host closed the connection.

**Comment by NotLima** [comment]
Hey everyone, as you know, Icehacks ™️ does not currently work. Our devs have no motivation to fight against Kongregates anticheat. For two years we developed this cheat for free. We ask you to pitch in $.30-1 to help us continue developing the cheat. https://www.paypal.me/LimaTM
