### ISSUE TITLE
HAIL KONG

### ISSUE THREAD

**Issue by MaulDandHaxSurviv** [IceHacks/SurvivCheatInjector#414]
KONG HELPED SURVIV
WHEN THEY SOLD IT TO THEM, THE LORE GOT BOOSTED
HAIL KONG!
THEY HeLpED THE GAME SO MUCH YOU GUYS JUST CANT UNDERSTAND IT
I DONATED OVER 100 DOLLARS TO THEIR TIP AND YOU GUYS WONT RECIVE A SINGLE FUCKING CENT
OH AND I CLICK ON THEIR ADS SO THEY GAIN REVENUE! 
HAIL KONG

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by MaulDandHaxSurviv** [comment]
hail kong

**Comment by StabbyAlbert** [comment]
Heil Mein Furhr

**Comment by DamienVesper** [comment]
hail kong
