### ISSUE TITLE
Indicate when it's safe to use a medkit in the red zone

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#416]
I think all of us had the situation where you want to use a medkit in the red zone, but your health is so low that you have to use some bandages first to gain enough health to last you the medkit timer. Using too few bandages leaves you dead, using too many slows you down (you get back to full health later) and wastes resources, but it can be really hard to judge when it's safe to use the medkit, since the red zone damage varies. I think it would be convenient to have some marker on the health bar to show when it would be safe to use a medkit - for example, color it orange if the red zone would kill you before the medkit triggers.

**Comment by NotLima** [comment]
nice

**Comment by StabbyAlbert** [comment]
too complex

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://images.pornpics.com/1280/201807/27/8326231/8326231_009_15fb.jpg)
