### ISSUE TITLE
THEY MIGHT SHUT US DOWN

### ISSUE THREAD

**Issue by BopItFreak** [IceHacks/SurvivCheatInjector#417]
![image](https://user-images.githubusercontent.com/41522720/80265306-20e63c80-8665-11ea-8c43-b4e17c68ac6a.png)
![image](https://user-images.githubusercontent.com/41522720/80265312-25aaf080-8665-11ea-88ff-8789b5ea26d1.png)
![image](https://user-images.githubusercontent.com/41522720/80265317-28a5e100-8665-11ea-8514-82e325bf62c3.png)
![image](https://user-images.githubusercontent.com/41522720/80265322-2f345880-8665-11ea-84e0-e93fd14f681a.png)

DON'T LET THEM BAN US!!!!!!!!!

**Comment by minhtanhd256** [comment]
So what, you use hack machine, that is not fucking right in the 1st place. When you really get banned, take it, don't fucking complain. CÓ CÁI ĐẦU BUỒI

**Comment by BopItFreak** [comment]
Are you from the surviv server? We are hackers here.

**Comment by StabbyAlbert** [comment]
cheating is not gonna go anywhere, zbot and ice are gonna make sure it remains rampant.

**Comment by StabbyAlbert** [comment]
Additionally, please take into account that this is the community manager, your job is to calm down the community. Next time take into consideration your reliability of your information.

**Comment by AlessioSwire** [comment]
> ![image](https://user-images.githubusercontent.com/41522720/80265306-20e63c80-8665-11ea-8c43-b4e17c68ac6a.png)
> ![image](https://user-images.githubusercontent.com/41522720/80265312-25aaf080-8665-11ea-88ff-8789b5ea26d1.png)
> ![image](https://user-images.githubusercontent.com/41522720/80265317-28a5e100-8665-11ea-8514-82e325bf62c3.png)
> ![image](https://user-images.githubusercontent.com/41522720/80265322-2f345880-8665-11ea-84e0-e93fd14f681a.png)
> 
> DON'T LET THEM BAN US!!!!!!!!!

Well I logged into my account yesterday and a message popped up saying I got banned. Not giving a freaking fu*k, I just play without an account and that's it lol

**Comment by StabbyAlbert** [comment]
I play without account Lol

**Comment by NotLima** [comment]
^

**Comment by minhtanhd256** [comment]
Do you know that you are fucking ruinning the game? What the fuck?

>

**Comment by belugawhale1** [comment]
Fuck you all people just want to play this game for fun and your ruin it with your stupid hacks you failed abortion

**Comment by AlessioSwire** [comment]
> Fuck you all people just want to play this game for fun and your ruin it with your stupid hacks you failed abortion

lmao

**Comment by SniperXKiller** [comment]
@belugawhale1  SHUT THE HELL UP, YA DICKWEED.

**Comment by SniperXKiller** [comment]
I PROBABLY got banned from surviv.io by DamienVesper, but i use the proxy sites
