### ISSUE TITLE
new cheat prevention: Cheater only games after detection

### ISSUE THREAD

**Issue by LucianDevran** [IceHacks/SurvivCheatInjector#418]
I just got the message after "Host closed connection" after my game froze midgame
"Cheaters play with cheaters! x to close, r to reload!
and now I assume everyone in my games are also hackers

**Comment by LucianDevran** [comment]
albert told me to do this

**Comment by NotLima** [comment]
uhh
i 
need
proof

**Comment by LucianDevran** [comment]
yeah sorry I don't have any... also this seems either to be only temporary or very trigger-happy since I later got full matches again with people that seemed not to be cheating
