### ISSUE TITLE
Lock on offscreen enemies by identifying where their bullets converge

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#419]
If you fire a bullet and then, without moving, turn by any angle and fire another, someone who sees both bullets can easily trace them both back and identify the spot they came from, even if it's far offscreen. A human player doesn't really have time for mental triangulation, but a script is obviously not limited by the puny human mind. I'm imagining the script creating a virtual enemy (maybe with a differently-colored ESP trace) for, let's say, three seconds after it identifies two bullets that came from the same gun from a roughly similar direction, and then updating this position and resetting the life timer with every new bullet from this gun; this should result in the aim jumping to the newest position of the enemy (since they are probably not going to sit still) and result in a pretty decent offscreen hitrate in combination with the natural bullet spread.

**Comment by NotLima** [comment]
hm
idk

**Comment by StabbyAlbert** [comment]
This is Dog level tryhard hack

**Comment by SniperXKiller** [comment]
AGREED

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://images.pornpics.com/1280/201807/27/8326231/8326231_009_15fb.jpg)
