### ISSUE TITLE
Update hack for 50v50

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#42]

**Comment by ALEXXANDRO23** [comment]
Yes please The strange thing is that it only worked for me In a 50 vs. 50 game And the hack failed

**Comment by u1qqlv** [comment]
aim is not working, other thing seems to work... aim is working in solo mode and that's strange

**Comment by Ziko2005** [comment]
Aim is very buggy

**Comment by NeoNHitmaN** [comment]
Aim is not working in 50/50 mode, he work only in solo and duo mode, fix it please!

**Comment by humphreygaming** [comment]
Ah, Satan himself is back...

**Comment by IceHacks** [comment]
Ok, I told everyone I would be gone and not to bug me. Very annoying.

**Comment by IceHacks** [comment]
As far as I can tell the only "buggy" thing is auto dodge dodging your team's bullets. There is nothing wrong with the aim.
