### ISSUE TITLE
For potato mode, add an option to automatically drop AWM-S after every shot so that it doesn't get swapped

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#421]
If you drop a gun right after a shot that would have swapped it (kill or potato hit), it won't get swapped. Nobody likes getting his AWM-S swapped. Therefore, dropping AWM-S right after shooting will make everybody happy.

**Comment by Platinum-Phoenix** [comment]
Yea that would be a good Idea.

**Comment by humphreygaming** [comment]
does dropping it work without cheats?

**Comment by Nihilistics** [comment]
I've managed to drop it manually and thus avoid swapping by shooting a potato in the bottom right corner of the screen (so my mouse would be a few pixels from the gun) with an 8x scope.

**Comment by StabbyAlbert** [comment]
drop then pickup very fast, maybe in icehacks plus

**Comment by NotLima** [comment]
What Alberto Said

**Comment by SniperXKiller** [comment]
Honestly, that sounds OP

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://images.pornpics.com/1280/201807/27/8326231/8326231_009_15fb.jpg)
