### ISSUE TITLE
Hack Glitches

### ISSUE THREAD

**Issue by krish41225** [IceHacks/SurvivCheatInjector#422]
For me the hacks are glitching and sometimes don't work. The hacks make surviv slow.

This was used on version **2.0.9**

**Comment by NotLima** [comment]
its ur pc

**Comment by krish41225** [comment]
no its not it works fine on browsers without the hack

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
