### ISSUE TITLE
Hack needs to be updated to 2.9.4

### ISSUE THREAD

**Issue by Qbert2030** [IceHacks/SurvivCheatInjector#428]
**Describe the bug**
Cheat code is not up to date with game code there fore are clashing and is preventing the game from loading

**Expected behavior**
Game should load up with IceHacks logo above game menu, and then should be able to just click (solo squads or duos) and load in to a match.
 
**Screenshots**

**Cheat version**
(ex: 2.0.9)

**Chromium version**
(go to chrome://version/)

Google Chrome | 81.0.4044.129 (Official Build) (64-bit)
-- | --
Revision | 3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS | macOS Version 10.15.4 (Build 19E287)
JavaScript | V8 8.1.307.31
Flash | 32.0.0.363 /Users/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.363/PepperFlashPlayer.plugin

**Comment by humphreygaming** [comment]
updated?
