### ISSUE TITLE
Ice hacks is gone

### ISSUE THREAD

**Issue by strikingforce909** [IceHacks/SurvivCheatInjector#429]
**Describe the bug**
In surviv official they have announced that ice hacks has been fixed, and that they can report hackers and ip ban them, meaning they can never play surviv again ;-;

**Expected behavior**
I expected a normal surviv game

**Screenshots**
![image](https://user-images.githubusercontent.com/39530102/81010626-6811c180-8e0b-11ea-86a2-39b517014269.png)

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)
latest version

**Comment by humphreygaming** [comment]
cheats still work
