### ISSUE TITLE
RIP ?!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#430]
https://surviv.io/changelog.html
## [0.9.4] - May. 4, 2020
- Players using unauthorized extensions (a.k.a. cheating) will be barred from playing Surviv.

**Comment by TheSatanicAngeI** [comment]
`DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

**Comment by TheSatanicAngeI** [comment]
Impossible to play on Google chrome, Firefox, Microsoft edge....

**Comment by TheSatanicAngeI** [comment]
Using a VPN seems to bypass it.

**Comment by TheSatanicAngeI** [comment]
https://gyazo.com/6553f3189c13481fc012e0290fdde84a

**Comment by TheSatanicAngeI** [comment]
https://mega.nz/file/w2plVaDa#JNdRcj45KVWJBzTpekQp15UcrEoysjmoZRafeu5AuJU

Here's a cracked VPN if you need one. You install and when it launch you close it and it will make you premium. 

Proof : https://i.gyazo.com/6bef83390f04b20303696b6442e3802b.png

**Comment by TheSatanicAngeI** [comment]
I think they just reverted changelogs. Maybe it was preventing everyone from being able to play I dont know. But still in case get a VPN if they put this shit out it will be your only way to still be able to play.

**Comment by Nihilistics** [comment]
I can bet there will be no IP bans. A sizeable chunk of the playerbase is kids playing at school from the same IP; if they ban one cheater, they can take out a dozen non-cheaters, and that will _actually_ kill the game.

**Comment by humphreygaming** [comment]
Servers were down a couple hours ago. I myself can still play somehow

**Comment by kirillovmr** [comment]
It cannot be that they create an unrivaled cheat. Everything can be hacked

**Comment by TheSatanicAngeI** [comment]
> Servers were down a couple hours ago. I myself can still play somehow

They reverted update because it was crashing their servers I believe. They were suppoesd to also reveal a new event the 4th along with the new anti-cheat but its not working 100% so they reverted untill they fix it. If they use network script or something that goes along "this user IP is banned from playing surviv.io because of cheats" then VPN will be the only way.

**Comment by TheSatanicAngeI** [comment]
Then again, I don't know much about scripting yet so I'm talking crap much lol
