### ISSUE TITLE
They added an Anti Cheat

### ISSUE THREAD

**Issue by Developer-XYZ** [IceHacks/SurvivCheatInjector#432]
Title says it all. Kong added an anticheat, and this could be the end of the hack forever!!!!

**Comment by humphreygaming** [comment]
o really?

**Comment by oofgangcrypin** [comment]
Idek what you guys are talking about, my hacks are working

**Comment by Minecraft-Beast101** [comment]
They rolled back the update to fix login issues.

**Comment by Developer-XYZ** [comment]
Basically it doesnt allow extesnions
