### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by RaptorsMaster140** [IceHacks/SurvivCheatInjector#436]
Just keeps laoding and loading on homepage. Does not work at all.

**Comment by gautamgxtv** [comment]
well duh they have an anti-cheat now but humpy is fixing

**Comment by SenseiKat** [comment]
yeah

**Comment by TheSatanicAngeI** [comment]
https://github.com/IceHacks/SurvivCheatInjector/issues/433#issue-612890359
