### ISSUE TITLE
Hacks have stopped working

### ISSUE THREAD

**Issue by TheArtsyOne** [IceHacks/SurvivCheatInjector#438]
I have been trying to log onto Surviv.io except it won't load, so I tried turning off the extension and it automatically loaded. I can't get Surviv to load while the hacks are enabled, and I really want it to load because I LOVE this hack, it's AMAZING.

It should load normally and allow me to join a game.

version 2.0.9

chrome version 81.0.4044.129

**Comment by TheSatanicAngeI** [comment]
https://github.com/IceHacks/SurvivCheatInjector/issues/433#issue-612890359
