### ISSUE TITLE
When I load up surviv.io with icehacks on it will not load because of the update on 5/5/2020. 

### ISSUE THREAD

**Issue by Camden23** [IceHacks/SurvivCheatInjector#442]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by gautamgxtv** [comment]
anti cheat is here ohno

**Comment by Camden23** [comment]
> anti cheat is here ohno

Can we fix it so it will work

**Comment by TheSatanicAngeI** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Cheat version**
> (ex: 1.1.0)
> 
> **Chromium version**
> (go to chrome://version/)

https://github.com/IceHacks/SurvivCheatInjector/issues/440#issue-613519558

**Comment by StabbyAlbert** [comment]
still works, releasing when features are finished
