### ISSUE TITLE
Hack doesn't work anymore, How can I help

### ISSUE THREAD

**Issue by shayans66** [IceHacks/SurvivCheatInjector#443]
Is this repo/project open source? I'd love to help out. Im a CS student

**Comment by magikol** [comment]
You have to have JavaScript and JSON knowledge.

**Comment by shayans66** [comment]
Yea I know that stuff

**Comment by TheSatanicAngeI** [comment]
@humphreygaming

**Comment by StabbyAlbert** [comment]
join the discord server

**Comment by TheSatanicAngeI** [comment]
@StabbyAlbert Give invite link

**Comment by NotLima** [comment]
https://discord.gg/At9pVb7
