### ISSUE TITLE
Aimbot is broken, works like 45% of the time, and also need autoswitch back

### ISSUE THREAD

**Issue by beanjackn** [IceHacks/SurvivCheatInjector#444]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by StabbyAlbert** [comment]
adding some code optimization too in the next update

**Comment by StabbyAlbert** [comment]
going to be a superfast cheat when done

**Comment by SurvivPro** [comment]
When I fire it like barely goes to the taget Im wanting to shoot at and manly 70% of the time the aimbot doesnt work.
