### ISSUE TITLE
How can i reset

### ISSUE THREAD

**Issue by RaptorsMaster140** [IceHacks/SurvivCheatInjector#446]
how can i reset these ahacks. it does not auto shoot anymore

**Comment by TheSatanicAngeI** [comment]
Does anyone fucking read the update info

AAAAAAAAND after a couple debugging and some magical fixing the cheat has been brought to a working state, plus, we added some stuff in. Some things that don't work are:

Autoswitch
Autoshoot
Grenade Timer
but im sure you can live without those, right?
right...?
