### ISSUE TITLE
[Problem] Aimbot after 7 May update!!! 

### ISSUE THREAD

**Issue by FileView69** [IceHacks/SurvivCheatInjector#449]
### **Describe the bug**

So basically the Aimbot aims automatically **all the time**, even when binds are set for _when_ to activate it, this has led to several situations, where you are constantly looking at enemies instead of: _being able to loot, move properly, hide,_ and it does make you look very obvious,

It has also led to me dying in 2 games..

### **Expected behavior**
The aimbot doesn't move **at all** unless you press the bound key (eg: Mouse:2)

### **Cheat version**
2.1.0

**Comment by humphreygaming** [comment]
use inverted aim or aim on shoot
