### ISSUE TITLE
aim bot is not aiming

### ISSUE THREAD

**Issue by zerodark088888** [IceHacks/SurvivCheatInjector#450]
i try to use aim bot after may 7 update but its not working at all
like well it just dont aim while i shoot or while i try to aim at enemy i use binding key enter to start aim bot as it was in info but it not worked too even after i try everything aim bot still dont aim
i m using aim bot v2

**Comment by Avatar-Kyoshi-Roku** [comment]
> i try to use aim bot after may 7 update but its not working at all
> like well it just dont aim while i shoot or while i try to aim at enemy i use binding key enter to start aim bot as it was in info but it not worked too even after i try everything aim bot still dont aim
> i m using aim bot v2

use v1 under aimbot try false everything except autoattack 
auto loot doors
bumpfire
esp
flashlight: true
blast radius:true
transparency obstacles:1
                      Roofs:0
should work fine cause autoswitch and autoshoot and grenade timer currently dont work
so when you have auto aim you have to shoot yourself
