### ISSUE TITLE
Issues with Starting the Cheat.

### ISSUE THREAD

**Issue by Surviv-ior** [IceHacks/SurvivCheatInjector#451]
I am unable to Get the extension working in my browser. I am choosing the right file but it says there 
 is no manifest that is able to be loaded.

I hoped to go in and have fun with these and I did before the update.

![Screenshot 2020-05-08 at 1 51 19 AM](https://user-images.githubusercontent.com/65008327/81379371-a094f200-90ce-11ea-9954-8bf89985d99a.png)

**Cheat version**
I believe this is 2.1.0.

**Comment by humphreygaming** [comment]
looks like you downloaded the wrong file
