### ISSUE TITLE
[Problem] Aimbot with the May 7 update!!!

### ISSUE THREAD

**Issue by FileView69** [IceHacks/SurvivCheatInjector#452]
### **Describe the bug**

So basically the Aimbot aims automatically **all the time**, even when binds are set for _when_ to activate it, this has led to several situations where you are constantly looking at enemies instead of: _being able to loot, move properly, hide,_ and it does make you look very obvious,

It has also led to me dying in 2 games..

### **Expected behavior**
The aimbot doesn't move **at all** unless you press the bound key (eg: Mouse:2)

### **Cheat version**
2.1.0

--------------------------------------------------------------------------------------------------------------

Now, the author replied to me saying;

Use On-Shoot or Inverted aim....

**Now two things:**

- Inverted Aim does a whole lot of... nothing

- On shoot is not the 100 % solution to this, no only you miss a lot shots, but it's not that convenient either. Also the shotgun is pretty much useless since you only have 2 rounds there.

This problem goes on to: V1 and V2, so...

Now what I expected with the Aimbot binds is:

It doesn't shoot until you press the bound key.
Isn't that what's supposed to happen?

If not please add it immediately (:

Every aimbot has an activation key, why should this be an exception?

Should it be an exception?

Should it?

Why is this an exception??

--------------------------------------------------------------------------------------------------------------

Anyway you can copy-paste the OnShoot, except you can replace the **shooting action** with **pressing the bound key**

I can provide the source code from a previous cheat in effort to save time!

**Comment by FileView69** [comment]
This is another post btw, not the first one.

**Comment by humphreygaming** [comment]
turn off aimbot and try to switch aimbot modes. Same thing happened to me and that seemed to fix it
