### ISSUE TITLE
[Problem #2] AutoAttack!!!

### ISSUE THREAD

**Issue by FileView69** [IceHacks/SurvivCheatInjector#455]
### **Describe the bug**
Basically what AutoAttack does is that it gets you stuck in _walls, trees, obstacles in general..._
when a close enemy is behind one of those things, then you can't move yourself out or away, 

- especially bad when someone is on the others side of the house, and it tries to attack them **through the windows with fists(!)** (your fists can't reach) and they kill you with a gun.

- or it gets u caught on an indestructible wall and ur stuck there basically forever.

### **Expected behavior**
The AutoAttack should detect walls/obstacles, and **not** try to reach enemies **directly through them.**

### **Screenshots**

![sn](https://i.imgur.com/fln9E1x.png)

**Note that you can't move

**Comment by humphreygaming** [comment]
try right clicking when this happens
