### ISSUE TITLE
[Problem #3] PanHero with the May 7 update!!!

### ISSUE THREAD

**Issue by FileView69** [IceHacks/SurvivCheatInjector#456]
### **Describe the bug**
Pan Hero doesn't work, it doesn't rotate the pan towards incoming enemy bullets to block them, regardless of the settings and the Aimbot being enabled / disabled.

### **Expected behavior**
The pan should rotate towards the bullets to block them...

### **Cheat version**
2.1.0

### **Important note**

The Pan thing **_should have a Bind key_**, so that you can choose when to block the bullets and when not to, you know... so that you can Aimbot...

sigh...

**Comment by humphreygaming** [comment]
currently, it only works with player-inputed aimbot
