### ISSUE TITLE
Help meeee

### ISSUE THREAD

**Issue by TheArtsyOne** [IceHacks/SurvivCheatInjector#458]
So idk if this really is a bug but i have no clue how to download the 2.1 update... it's not working, I've done every single thing with the ZIP file and it will. not. work. How do I get the manifest file???

2.1

81.0.4044.129

**Comment by humphreygaming** [comment]
make sure you are downloading **Surviv.io Cheat Injector 2.1.1.zip** and not the source code or anything. If you have manifest file missing, try redownloading or make sure that manifest.json exists
