### ISSUE TITLE
[Really?] Nothing was fixed!!!

### ISSUE THREAD

**Issue by FileView69** [IceHacks/SurvivCheatInjector#459]
So after 3 updates, adding the chat oven virus, and adding the piss color unchangable armor...

You still haven't made the aimbot stoppable or toggleable...

What makes it worst is that you suggested pressing right click to the window attacking auto attack of doom that gets you stuck all the time, attacks knife dudes and gets u engaged with other cheaters even though using a gun would be wiser, it and the unstoppable aimbot got me killed at least 50 times...

Alot of featues don't work:

Pan hero
Spinbot
Binds
....

you want a full Bug report? ok
With a checklist as well.
--------------------------------------------------------------------------------------------------------------

### **The Aimbot:**
AutoAim: Cannot be controlled, Cannot be stopped, cannot be toggled... Bindless basically..
InvertedAim: Nice menu item, mind hooking it to anything?

### **AutoAttack:**
**_Tries to punch people through windows, gets you stuck everywhere, punches instead of using a gun which is much better, gets you stall fighting other cheater, and loosing on lower health even though you have a gun..._**
Main cause of fucking death... Bitch.

### **The ESP:**
Completely disappears when you unexpectedally disconnect, (not quitting the game or pressing "X")
if your internet times out for even 1 second you have to refresh, or the ESP won't be there next game,.

### **Binds:**
lol

### **SpinBot:**
Doesn't work

### **PanHero:**
Sounds great; but doesn't do anything

Doesn't work...

--------------------------------------------------------------------------------------------------------------

Are you fucking serious???
Are you having fuck you cunt????

Cunt ass bitch, also remove the virus or else, 

I'm reporting it to Github if the malware persists, you fucking idiot
We do not endorse malware here you fucking kid, piss off.

**Comment by FileView69** [comment]
Maaan, fuck this kid.



He probably fat as well..

**Comment by NotLima** [comment]
yeah fat fuck

**Comment by NotLima** [comment]
also 
Pan hero - works
Spinbot - works 
Binds - works 

....

**Comment by StabbyAlbert** [comment]
Faggot dumbass kid lol

**Comment by humphreygaming** [comment]
chat oven isn't a virus, dumbfucks. It was always there. https://youtu.be/ehfiuIEPiTo

**Comment by Nihilistics** [comment]
Er, wtf is "chat oven"?

**Comment by humphreygaming** [comment]
the integrated chat in the cheat (click the icon where the updates would usually be)
