### ISSUE TITLE
TWO THINGS STILL DON'T WORK

### ISSUE THREAD

**Issue by AlessioSwire** [IceHacks/SurvivCheatInjector#460]
1. Autoshoot doesn't work and you always need to left click.
2. It always tries to automatically use adrenaline items even though the adrenaline bar is already full or close to being; for example, it endlessly tries to use pills even when the bar is full and it's kinda annoying.

**YES,** the settings are as they should be.
**YES**, I'm using the latest release (2.1.2)
**YES**, I've never had issues of any kind with the older releases

**Comment by shayans66** [comment]
All characters (including mine) and all items appear invisible when I play. has this happened to anyone else

**Comment by magikol** [comment]
Yeah but you just need to refresh the page unless you wanna be invisible.

**Comment by magikol** [comment]
> All characters (including mine) and all items appear invisible when I play. has this happened to anyone else
 
Yeah but you just need to refresh the page unless you wanna be invisible.

**Comment by NotLima** [comment]
> All characters (including mine) and all items appear invisible when I play. has this happened to anyone else

u have to wait for your game to fully load

**Comment by RaptorsMaster140** [comment]
how do i reset my settingS?

**Comment by AlessioSwire** [comment]
So no one is going to asnwer my issue lol ok

**Comment by shayans66** [comment]
hey genius, the guy clearly said in the latest release that auto-shoot isn't working for now

**Comment by shayans66** [comment]
> So no one is going to asnwer my issue lol ok

humphrey said in the latest release that auto-shoot isn't working for now

**Comment by 068scar** [comment]
we dont need autoshoot but we need autoswitch thats more important + autoheal doesnt work either

**Comment by DamienVesper** [comment]
you need no hacks in general @068scar

**Comment by AlessioSwire** [comment]
> > So no one is going to asnwer my issue lol ok
> 
> humphrey said in the latest release that auto-shoot isn't working for now

Ok but at least the adrenaline thing which is more annoying lol

**Comment by solara322** [comment]
aimbot-autoshoot doesnt work in last version

**Comment by DAMIENVESPERISAFUCKTARD** [comment]
> you need no hacks in general @068scar

DUDE DAMIEN NIGGER JUST DIE IN A HOLE FUCKING SON OF A BITCH
