### ISSUE TITLE
Colored Armor Suggestions

### ISSUE THREAD

**Issue by magikol** [IceHacks/SurvivCheatInjector#462]
I saw an issue request to remove the colored armor feature and  I've been wondering if any customization options could be made.

 **Suggested Features:**

- An on and off toggle.
- A color randomizer feature? (Every game a new color gets put on the armor)
- Changing the colors manually. (Via color picker)

**Comment by humphreygaming** [comment]
color armor is currently a test to see what color parsing can actually do
