### ISSUE TITLE
What does SniperSwitch and Aim FOV and Use Collisions do?

### ISSUE THREAD

**Issue by Caioz10** [IceHacks/SurvivCheatInjector#466]
Actually, I installed the **IceHack**surviv hack. so I looked to the three things called: SniperSwitch, Aim FOV, and Use Collisions, and I wanna know what does that do. there is the images of them -->

![AIM FOV](https://user-images.githubusercontent.com/65035375/81479366-1f864980-91f9-11ea-9f99-2776d803d815.png)
![Mode](https://user-images.githubusercontent.com/65035375/81479372-29a84800-91f9-11ea-9e9d-8363bc1b7626.png) (wait it's on smartswitch it's sniperswitch tho)
![Use Collisions](https://user-images.githubusercontent.com/65035375/81479390-45135300-91f9-11ea-82c3-b6295b482a4f.png)

**and** follow bot keeps following one key, the left button

thanks for asking so

um bye

uh

**Comment by FileView69** [comment]
Aim FOV: fuck your mom

SmartSwitch: fucks ur dad

Use collisions: Fucks the rest of your family, don't use these 3...

**Comment by Caioz10** [comment]
wat

**Comment by humphreygaming** [comment]
@Caioz10 
Aim FOV sets the aimbot to only aim at a certain triangle angle (FOV) and will not aim outside of that
Sniperswitch quickswitches snipers 
Use Collisions will not shoot at people inside houses
