### ISSUE TITLE
new discord

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#467]
https://discord.gg/XJzaDWr

**Comment by FileView69** [comment]
You just don't get it do you?

It's not firing, it won't fire, something with your script is not letting guns fire, it's like something with a spam-click that keeps reaching its limit, but it can't be disabled..

Don't you see when you grab a pistol, smg or rifle it just is choppy af, it fires a round or two then freezes and you have to manually spam click it to fire.

FIX IT!!!

faggot...

**Comment by humphreygaming** [comment]
that is your own problem, it works for everyone else

**Comment by FileView69** [comment]
> that is your own problem, it works for everyone else

Ur lying fat fuck

Get it fixed or I will fuck ur mom.
She's busty and horny and ur dad not enough

**Comment by oofgangcrypin** [comment]
DUDE SHUT THE FUCK YOU, MY AUTISTIC BROTHER IS SMARTER THAN YOU, YOUR PC IS ASS, THE HACK WORKS, GET YOUR BRAIN FIXED DUMBASS

**Comment by Avatar-Kyoshi-Roku** [comment]
but the Autoshoot and Autoswitch and pan hero does not work  and what is pan hero suppose to do anyway?

**Comment by DAMIENVESPERISAFUCKTARD** [comment]
FILEFUCKTARD 69 go fucking die in a hole nigger. Such a faggoty ass nigger

**Comment by NotLima** [comment]
> FILEFUCKTARD 69 go fucking die in a hole nigger. Such a faggoty ass nigger
^ when u learn the bad words for the first time

**Comment by huhuhuhuhhu** [comment]
With the new hack 2.1.2, the loot pan automatically does not work. Can u fix this?

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201803/29/2475086/2475086_180_87dd.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://images.pornpics.com/1280/201807/27/8326231/8326231_009_15fb.jpg)
