### ISSUE TITLE
Give an option to set the range at which melee-lock triggers and/or don't disable fire when approaching

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#470]
One major problem with the script is that the approach for melee lock triggers from a far too large distance and, what's worse, you cannot continue firing your weapon with the aimbot active, meaning that the aimbot will just blindly lead you into the enemy fire from a distance where it could have popped off another mosin shot just fine (especially noticeable in water). I think it would be really useful to be able to reduce this trigger distance.

**Comment by AlessioSwire** [comment]
> One major problem with the script is that the approach for melee lock triggers from a far too large distance and, what's worse, you cannot continue firing your weapon with the aimbot active, meaning that the aimbot will just blindly lead you into the enemy fire at a distance when it could have popped off another mosin shot just fine. I think it would be really useful to be able to reduce this trigger distance.

Totally agreed.

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://images.pornpics.com/1280/201807/27/8326231/8326231_009_15fb.jpg)
