### ISSUE TITLE
PAN

### ISSUE THREAD

**Issue by huhuhuhuhhu** [IceHacks/SurvivCheatInjector#471]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by huhuhuhuhhu** [comment]
the loot pan actomaticly does not work

**Comment by kirillovmr** [comment]
make sure that you are using the latest version of the cheat. It should be working on 2.1.2

**Comment by huhuhuhuhhu** [comment]
i am and my pan does not loot actomatilly
