### ISSUE TITLE
bug with the aimbot

### ISSUE THREAD

**Issue by junepark2005** [IceHacks/SurvivCheatInjector#475]
**Describe the bug*
when i start to shoot, the aimbot keeps on swithing weapons because of this, when i shoot a single bullet, it turns into another gun. i can't play this game fun.. please help me! 

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by huhuhuhuhhu** [comment]
The pan thing loot pan automatically  does not work either.
