### ISSUE TITLE
Add an option to automatically stop spinning when you fire

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#476]
When you are spinning on dem salty noobs and want to attack something not targetable by the aimbot or throw something, it's kinda inconvenient having to disable the spinbot, select the gun you want, fire and then re-enable the spinbot, _for every shot_. It's like you're back in the time of manual quickswitching \*shudder\*. I would really like to see an option to automatically stop spinning whenever the user _releases_ the fire button (specifically releases to make sure that you are still spinning when cooking the grenade).

**Comment by huhuhuhuhhu** [comment]
put your you autoaim to on shoot
and put on aim at objects so u never stop spinning.

**Comment by Nihilistics** [comment]
I don't like aim at objects, it's far too unreliable in my experience, and I don't want autoaim on shoot, since I won't always be throwing grenades/mines directly at the enemy

**Comment by humphreygaming** [comment]
mk, will consider
