### ISSUE TITLE
Different hacks

### ISSUE THREAD

**Issue by TheArtsyOne** [IceHacks/SurvivCheatInjector#481]
So I don't really know how else to ask you this, but I'd like to see you set up a hack for a game called Mope.io... like se it so that you have infinite health and faster speed and faster leveling up. Please try this, it'd be awesome if you could

**Comment by Avatar-Kyoshi-Roku** [comment]
do floor.io

**Comment by Nihilistics** [comment]
Do you dumb kids really not understand the difference between client-side and server-side code? :-/

And that's leaving aside the fact that you're asking someone to commit probably 100+ hours to analyzing a game they have no interest in and making a cheat for it. Pull your head out of your ass for just a second and think how idiotic that is.

**Comment by strikingforce909** [comment]
ffs thats not possible all user data is stored in the server side he can only edit the client
