### ISSUE TITLE
Aimbot is worse with new version

### ISSUE THREAD

**Issue by BlTWISE** [IceHacks/SurvivCheatInjector#488]
**Describe the bug**
Aimbot doesn't aim at the person correctly. It's not accurate and seems to be aiming a little bit away from the player instead of directly at the player. This did not happen on 2.0.9. 
**Expected behavior**
Like on version 2.0.9, it should aim at the center of the person.

**Cheat version**
2.1.3

**Chromium version**
81.0.4044.138

Is there a way we can just choose between the different aimbot versions?

**Comment by bruh-moment24** [comment]
Yes, i do agree, the aimbot does seem to be off. Although this is true, i still like the new update(2.1.3).

**Comment by TheSatanicAngeI** [comment]
Idk man I feel like the aimbot is much better for me since update

**Comment by humphreygaming** [comment]
read pinned messages
