### ISSUE TITLE
AutoAttack: Add an option to toggle auto switch to melee

### ISSUE THREAD

**Issue by DleanJeans** [IceHacks/SurvivCheatInjector#489]
Same vibe with #470 but gives you more control over your weapons handling.

**Current State**: The cheat automatically switches to melee within a certain range with an enemy.

**Enhancement**: This option allows players to switch between weapons and melee at any time and any range near enemies (the cheat only follows a target enemy) thus enables more fine grain control.

**Comment by magikol** [comment]
Heck yeah. This would prevent most of my deaths.

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by StabbyAlbert** [comment]
Fucking faggot fileview. Keep wasting your time posting this shit its fun removing it

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)
