### ISSUE TITLE
Auto Heal Bug: Adrenaline 

### ISSUE THREAD

**Issue by ghost** [IceHacks/SurvivCheatInjector#492]
Everything else is fine except for the adrenaline healing. It keeps trying to heal you even after the adrenaline bar is full. I'm not sure if another person even mentioned this issue but they probably got ignored since no else really talked very much about this.

**I'll get an image later.**

**Comment by AlessioSwire** [comment]
> Everything else is fine except for the adrenaline healing. It keeps trying to heal you even after the adrenaline bar is full. I'm not sure if another person even mentioned this issue but they probably got ignored since no else really talked much about this issue.
> 
> **I'll get an image later.**

Yep, I mentioned it but got completely ignored lol

**Comment by magikol** [comment]
-  Yep, I mentioned it but got completely ignored lol
Well that's not cool.

**Comment by magikol** [comment]
> -Yep, I mentioned it but got completely ignored lol
Well that's not cool.

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://cdni.pornpics.com/1280/7/78/53574437/53574437_101_9333.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)
