### ISSUE TITLE
[SEX REQUEST] Hook me up with you moms!!!

### ISSUE THREAD

**Issue by FileView69** [IceHacks/SurvivCheatInjector#494]
Juicy anus Humph

So there should be in the ESP a unique color for the mines them selves, their detection range, whether or not they're friendly on top of their fucking blast radium, and whether or not it is fucking armed, understand me? Lol, BangBros

Per say, friendly mine, appears Blue, with no blast radius do reduce confusion, fucking idiot

Enemy mine, The mine itself is Green (or ur mom's pussy pink) so you can see it, the blast radium is Sperm White, and the blast radius is Blue like a good nut.

Mine that is not active (like ur mom's sexuaity) (before 5 seconds pass) just appears black with a timer until they are enabled?

Sounds good?

So
Green for Mine, White for it's detection radius, Red for blast radium
Friednly mine doesn't appear so you don't confuse with sex
Unactive mine before 5 sickond appear black porn with timer

So you actually see the mine, know where not to step, and will be able to remove the blast radius for it if you want to reduce confusion,
you will know if a mine is not enabled yet
and you wont sexually confuse on ally mine

I saw you legal mother in Brazzers the other day...

**Comment by FileView69** [comment]
[Lol](Xhamster.com)

**Comment by magikol** [comment]
I bet you're the one on that site.

**Comment by FileView69** [comment]
![alt text](https://images.pornpics.com/1280/201804/16/4265856/4265856_039_ce70.jpg)

**Comment by oofgangcrypin** [comment]
CAN YOU SHUT THE FUCK UP YOU IGNORANT FAILED ABORTION PIECE OF SHIT, SOME PEOPLE HAVE LIVES YOU KNOW? YOU UGLY ASS BITCH SHUT UP

**Comment by humphreygaming** [comment]
nah don't pay attention to him. He can't help how he is an autistic fuck. @FileView69 good luck with the pornography report to github
