### ISSUE TITLE
Pan Hero incorrectly turns your back to the bullets when you have the pan equipped (in your hands)

### ISSUE THREAD

**Issue by Nihilistics** [IceHacks/SurvivCheatInjector#498]

**Comment by humphreygaming** [comment]
it is supposed to reflect bullets when its on your back, hence the turning around

**Comment by Nihilistics** [comment]
I know; but when it's in your hand, turning your back is useless. It should either correctly rotate to block with the pan held in your right hand, or at least do nothing.

**Comment by kirillovmr** [comment]
True. will fix

**Comment by AccountHelp** [comment]
![alt text](https://images.pornpics.com/1280/201812/02/1311211/1311211_019_1a36.jpg)

**Comment by HelpAccount420** [comment]
![alt text](https://images.pornpics.com/1280/201907/27/9802234/9802234_030_09f9.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201907/05/2787406/2787406_074_d514.jpg)

**Comment by FuckingFuckingham** [comment]
![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)
