### ISSUE TITLE
Incjector Removes itself when reloading page.

### ISSUE THREAD

**Issue by dakillet** [IceHacks/SurvivCheatInjector#499]
**Describe the bug**
When i Reload the page, the incjector removes itself and i have to put it back in, is something wrong with the hack or is it just me?
**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by humphreygaming** [comment]
it could be just you. Nobody has reported this issue yet
