### ISSUE TITLE
No-Roofs option

### ISSUE THREAD

**Issue by Natan1982** [IceHacks/SurvivCheatInjector#5]
Could you add an option for showing roofs normally?
Btw, thanks for you hack dude, no freezing and does all what its made for!

**Comment by IceHacks** [comment]
Ok. I will try to add later today.

**Comment by humphreygaming** [comment]
@IceHacks Might be for a "streamer mode" type thing

**Comment by Natan1982** [comment]
Thats basically what @humphreygaming said.
I prefer not beeing too obvious when playing with friends. XD

**Comment by IceHacks** [comment]
@Natan1982 Ok I see xD. I'll work on adding this with the next update.

**Comment by IceHacks** [comment]
@Natan1982 should streamer mode also disable esp?
