### ISSUE TITLE
aimbot is not working

### ISSUE THREAD

**Issue by Mosyeetos** [IceHacks/SurvivCheatInjector#50]
Guys how do you get th aimbot to work teh red line is appearing and everything but it just wont lock one. Can you please help?

**Comment by IceHacks** [comment]
Make sure aimbot is enabled and that "aim collisions" is off. Also, right-click disables/enables it.

**Comment by Mosyeetos** [comment]
oh thank you so much

**Comment by Mosyeetos** [comment]
aprreciate it

**Comment by Mosyeetos** [comment]
what is aim collisions

**Comment by Mosyeetos** [comment]
i dotn see it in the settings.

**Comment by Mosyeetos** [comment]
i gtg put ill be back in like an hour. thx

**Comment by IceHacks** [comment]
Ok

**Comment by IceHacks** [comment]
It's a setting under "aimbot"

**Comment by Mosyeetos** [comment]
also it keeps freezing

**Comment by Mosyeetos** [comment]
for some reason idk why what settings should i change it too thx.

**Comment by Mosyeetos** [comment]
nvm i fixed it
