### ISSUE TITLE
DO NOT VISIT ANY POST BY ACCOUNT HELP. HE HAS PORNOGRAPHY ON ALL HIS POSTS. UNLESS YOU WANT TO SEE HIGHLY INNAPROPRIATE MATERIAL DO NOT VISIT

### ISSUE THREAD

**Issue by e45d6rtfuvyig** [IceHacks/SurvivCheatInjector#507]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by yarkoval** [comment]
Thanks for warning. for me problem is annoing stupid useless issues, not photo:)   I just reported to github to block this asshole. My advice for everyone is also to report about this user

**Comment by e45d6rtfuvyig** [comment]
Yeah welcome. This pile of shit exposes pornography to kids like 9 year
olds.

**Comment by humphreygaming** [comment]
link to acc?

**Comment by HelpAccount420** [comment]
![alt text](https://images.pornpics.com/1280/201907/27/9802234/9802234_030_09f9.jpg)

**Comment by WaterBottle420** [comment]
https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)
