### ISSUE TITLE
DO NOT VISIT ANY POST BY HELPACCOUNT420. HE HAS PORNOGRAPHY ON ALL HIS POSTS. UNLESS YOU WANT TO SEE HIGHLY INNAPROPRIATE MATERIAL DO NOT VISIT

### ISSUE THREAD

**Issue by DAMIENVESPERISAFUCKTARD** [IceHacks/SurvivCheatInjector#518]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by WaterBottle420** [comment]
![alt text](https://images.pornpics.com/1280/201908/05/5708206/5708206_089_314a.jpg)
