### ISSUE TITLE
POLL : Blacklist WaterBottle420 from this repository ?

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#532]
### React with 👍 or 👎 

_This user has been making new threads to spam NSFW content._

@humphreygaming Can't you just remove his perms from making new threads/issues/suggestions ?

**Comment by WaterBottle420** [comment]
![alt text](https://cdn.pornpics.com/pics1/2020-03-29/631653_18big.jpg)
![alt text](https://cdn.pornpics.com/pics1/2020-03-30/631689_14big.jpg)
![alt text](https://images.pornpics.com/1280/201907/05/2787406/2787406_074_d514.jpg)

**Comment by yarkoval** [comment]
> ### React with 👍 or 👎
> _This user has been making new threads to spam NSFW content._
> 
> @humphreygaming Can't you just remove his perms from making new threads/issues/suggestions ?

It's difficult cause he/she just change account for new one. I reported to Github support. Maybe they have some tools to block forever by ip

also i suppose this is  that asshole that created issue about  malware week ago

**Comment by FuckingFuckingham** [comment]
![Alt text](https://cdn.pornpics.com/pics1/2019-03-09/595314_12big.jpg)
