### ISSUE TITLE
New Discord 

### ISSUE THREAD

**Issue by NotLima** [IceHacks/SurvivCheatInjector#548]
https://discordapp.com/invites/sKSBXuE

if u report ur auto gay

**Comment by NotLima** [comment]
if u fucking spam porn i will eat ur ass

**Comment by ILOVECHEATING** [comment]
Hey Lima, I cant join :(

**Comment by ILOVECHEATING** [comment]
can u give me your discord

**Comment by humphreygaming** [comment]
@ILOVECHEATING fixed

**Comment by SniperXKiller** [comment]
yeah can you guys give me your discord?
