### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by Mosyeetos** [IceHacks/SurvivCheatInjector#55]
it seems to freeze in the first 30 seconds of the game

**Comment by IceHacks** [comment]
Really?

**Comment by Mosyeetos** [comment]
wiat i think it auto lloot i disabled it and its owking

**Comment by IceHacks** [comment]
Oh! Try upgrading/disabling autodoors.

**Comment by Mosyeetos** [comment]
oh. And for some reason i cant join lobbys and stugg. Any tips on that?

**Comment by Mosyeetos** [comment]
DUde u kileld me ina game. I was S1mple. GG lol iw as poopping off tho
