### ISSUE TITLE
Does not work. Green screen.

### ISSUE THREAD

**Issue by RaptorsMaster140** [IceHacks/SurvivCheatInjector#550]
**Describe the bug**

After clicking battle, it just brings me to this green page and nothing happens. Can it be fixed?

**Expected behavior**
![Screenshot 2020-07-28 at 4 53 42 PM](https://user-images.githubusercontent.com/64698965/88751203-1e442900-d125-11ea-9b17-414fc870372d.png)

**Screenshots**

**Cheat version**
(ex: 2.1.4)

**Comment by lolwithguns** [comment]
Yeah same 👍:(

**Comment by lolwithguns** [comment]
![image](https://user-images.githubusercontent.com/68938446/88758271-e638e800-d11c-11ea-9c6f-f58a72fdb809.png)

**Comment by humphreygaming** [comment]
kinda sad, ain't it
