### ISSUE TITLE
Green Screen

### ISSUE THREAD

**Issue by oofgangcrypin** [IceHacks/SurvivCheatInjector#551]
Doesnt load when i start the game

**Comment by lolwithguns** [comment]
yeah same 
![image](https://user-images.githubusercontent.com/68938446/88758254-d4efdb80-d11c-11ea-82ac-6e10cf481938.png)like this

**Comment by lolwithguns** [comment]
is there any way to fix this?

**Comment by dinhanhx** [comment]
Hmmm they updated their anti cheat system

**Comment by dinhanhx** [comment]
Also should close other two issues #550 & #549 because of duplications

**Comment by LocoPETRAx47** [comment]
same
