### ISSUE TITLE
Do not work on 0.9.7 surviv version. NEEDS UPDATE

### ISSUE THREAD

**Issue by SURBEFAN** [IceHacks/SurvivCheatInjector#552]
**Describe the bug**
Update it!!! It doesn't work on 0.9.7 surviv version!(

**Expected behavior**
Dont start the game(((

**Screenshots**
There is some screens below

**Cheat version**
Last

**Chromium version**
Last

**Comment by FREAKINGFROZENBRACKETS** [comment]
Yeah lmao doesn't work now, needs an update

**Comment by humphreygaming** [comment]
it sure does need an update
