### ISSUE TITLE
Green screen

### ISSUE THREAD

**Issue by codergautam** [IceHacks/SurvivCheatInjector#553]
**Describe the bug**
green screen when playing game it is stuck on green screen num of ppl alive is showing and more gui features but actual game and canvas is green

**Expected behavior**
no gren screen

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by RaptorsMaster140** [comment]
Same here. Bro. Ur not alone. Pls update
