### ISSUE TITLE
Bug and not clear on MACOS download

### ISSUE THREAD

**Issue by Slasher707** [IceHacks/SurvivCheatInjector#556]
The bug is that the screen just turns green and im not clear on how to install it again on my MAC OS

I expected to have good hacks since it was from ICEHACKS

Its just a green screen 

The latest version

84.0.4147.105 is the chrome version

**Comment by codergautam** [comment]
it doesnt work anymore the hack patched

**Comment by Slasher707** [comment]
oh ;-; will you be making a newer version of it?

**Comment by codergautam** [comment]
sure i am trying to fix it but idk if i will be able too.... see icehacks and humphrey gaming stopped updating hacks and its now open soource... so the only way these hacks will work if someone like me actually fixes it. i am new to js programming and i will be able to fix soon... no guarantees :D

**Comment by humphreygaming** [comment]
simple solution: don't use mac
