### ISSUE TITLE
Greenscreen + Discord

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#557]
Greenscreen is a thing, and that is too bad.

Discord (for SCI unrelated stuff, fuck that shit): https://discord.gg/sKSBXuE

**Comment by humphreygaming** [comment]
This means that we are aware of it.
No we aren't fixing it.
Yes you fix it yourself.

Time to close some issues regarding this...

**Comment by survivhackerlol** [comment]
Why arn't you guys going to fix it yourself. You guys are the ones who know how to. We dont

**Comment by codergautam** [comment]
@humphreygaming what a bot

**Comment by Caioz10** [comment]
**_Imagine switching to Epic Hacks_**

**Comment by fire-and-ice582** [comment]
um epic hacks doesnt work too lol

**Comment by codergautam** [comment]
Lol yea
