### ISSUE TITLE
The hack isnt working

### ISSUE THREAD

**Issue by survivhackerlol** [IceHacks/SurvivCheatInjector#558]
It will not allow me to play the game. It will only allow me to press battle and then it won't let me play against people or move, It doesn't even let me see my own person.

I expected that it would let me play and let me do everything that it let me do last time. Your hacks are amazing and if you could fix it in your next update I would gladly appreciate it.

https://user-images.githubusercontent.com/69086152/89106486-3ef7d180-d3f8-11ea-9409-e891a8525a92.png

Surviv.io.Cheat.Injector.2.1.4.1.zip

83.0.4103.119 (Official Build) (64-bit)

**Comment by elijahduplessis2003** [comment]
Plz we all understand how frustrating it must be to you bt please fix it for us anyone that pisses you off again is gonna catch these hands bro

**Comment by elijahduplessis2003** [comment]
@humphreygaming

**Comment by elijahduplessis2003** [comment]
@survivhackerlol can u please add me on discord GAMEPLAY#5088 I need to desgus some really imported with you my friend 😊🙏🙏

**Comment by humphreygaming** [comment]
#557

**Comment by Naharchamp** [comment]
Pls tell how do I make this cheat work again

**Comment by russyboy1** [comment]
> Pls tell how do I make this cheat work again

dont necropost this post is too old bro
