### ISSUE TITLE
HOW CAN WE FIX A GREEN SCREEN? lmao we're not coders. GG cheat is dead

### ISSUE THREAD

**Issue by SURBEFAN** [IceHacks/SurvivCheatInjector#559]
Cool, so you are just not gonna work on it???

**Comment by elijahduplessis2003** [comment]
Plz fix

**Comment by elijahduplessis2003** [comment]
@SURBEFAN please add me on discord I need you help if you get this I hope u do ad me GAMEPLAY#5088 immediately please 🙏🙏🙏🙏😊

**Comment by humphreygaming** [comment]
#557
