### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by Mosyeetos** [IceHacks/SurvivCheatInjector#56]
so its freezing again and i got the updated version and for some reason it is not working. Also did you know that u killed me ina one game? I was unarmed but GG brotha

**Comment by Mosyeetos** [comment]
yeah i dont know why it keeps freezing

**Comment by IceHacks** [comment]
ok

**Comment by IceHacks** [comment]
I'll check it out later today

**Comment by Mosyeetos** [comment]
ok thank u so much dude.

**Comment by IceHacks** [comment]
are you using 1.1.3? https://github.com/IceHacks/SurvivCheatInjector/releases/latest

**Comment by Mosyeetos** [comment]
i did it think it works

**Comment by IceHacks** [comment]
good :0
