### ISSUE TITLE
i dont think melee hack part is working poperly

### ISSUE THREAD

**Issue by SkullSocks** [IceHacks/SurvivCheatInjector#562]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by humphreygaming** [comment]
more info?

**Comment by elijahduplessis2003** [comment]
Yes the melee lock doesn't work properly..it locks bt don't lock acutely its spins in a circle

**Comment by StabbyAlbert** [comment]
it works fine for me
