### ISSUE TITLE
Its not working 

### ISSUE THREAD

**Issue by Slasher707** [IceHacks/SurvivCheatInjector#564]
The bug or patch caused it to not show alot of features such as The surviv.io battle pass, the gamemode and team select, The ads, My character loadout, basically everything.

As expected from ICEHACKS they have really good surviv.io cheats and i would choose these out of every other hack.

https://docs.google.com/document/d/14J-Pb_FVOoIpQR13AyydzFy4V3B0xH3vUOGLxLVC4AI/edit?ts=5f330e39

2.1.5.1

84.0.4147.105

**Comment by sofuncheung** [comment]
I've found this not working too. On the Chrome Extension page it can be seen that some "Error" is there with this version of injector.

**Comment by SURBEFAN** [comment]
https://github.com/IceHacks/SurvivCheatInjector/issues/567
