### ISSUE TITLE
Client Code Obfuscation

### ISSUE THREAD

**Issue by bobcena777** [IceHacks/SurvivCheatInjector#565]
**Describe the bug**
Hack is completely ded

**Expected behavior**
For it actually hack, esp and all that jazz
**Screenshots**
dont have

**Cheat version**
0.97b

**Chromium version**
(go to chrome://version/)
84.0.4147.105 (Official Build) (64-bit)

**Comment by FarTooJunior** [comment]
Bro this hack is discontinued, so fix it yourself or don't play Surviv.io.

**Comment by bobcena777** [comment]
yes discontinued
![image](https://user-images.githubusercontent.com/69545617/89961853-e5618500-dbf7-11ea-937c-f8b09316f4b3.png)

**Comment by Slasher707** [comment]
Bro the newest version is 2.1.5.1 tf u doing over there LMAO

**Comment by BigQuantumMan** [comment]
There are many tools that make the code readable...

**Comment by bobcena777** [comment]
Slasher707 going strong SINCE... never stopped smh

**Comment by Slasher707** [comment]
kk i thought u meant the version of the hack lel

**Comment by SURBEFAN** [comment]
https://github.com/IceHacks/SurvivCheatInjector/issues/567

**Comment by StabbyAlbert** [comment]
fixed
