### ISSUE TITLE
Aim and esp hack stopped working 

### ISSUE THREAD

**Issue by VorTekx** [IceHacks/SurvivCheatInjector#571]
**Describe the bug**
I played legit 1 game and on the 2ed one the aimbot and esp stopped working

**Expected behavior**
On the first game the aim wasnt working 100% like  it woulnt lock on but the esp worked fine then on the 2ed they both were no existent 

**Screenshots**
https://imgur.com/ABnwAR3

**Cheat version**
V2.1.6

**Chromium version**
84.0.4147.110 (Official Build) (32-bit)

**Comment by paulo27ms** [comment]
Suck it

**Comment by gittyniggy** [comment]
Nobody asked you fucking nigger
