### ISSUE TITLE
The Surviv doesn't load

### ISSUE THREAD

**Issue by Daniel-Xiao98** [IceHacks/SurvivCheatInjector#573]
[**Describe]([url]([url](url))) the bug**

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screen Shot 2020-08-18 at 3 00 48 PM" src="https://user-images.githubusercontent.com/68244438/90569986-b43b0480-e163-11ea-8f57-82b93d79c100.png">

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by FarTooJunior** [comment]
Im having this issue too, seems like the reverted patch.
