### ISSUE TITLE
Hack

### ISSUE THREAD

**Issue by boo-tanki** [IceHacks/SurvivCheatInjector#575]
**Describe the bug**

Before, My spin bot and everything else was much better, now it is so bad I cant even get a kill

**Expected behavior**
The spinbot is so bad, the melee follow bot is terrible, and the aimbot sucks

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by BestContributor402** [comment]
It works fine for me. Sounds like your computer is so bad, your internet is terrible, and your lag sucks.

**Comment by WYLDYR** [comment]
The cheat is completely functional. This is your problem.

**Comment by WYLDYR** [comment]
Hi, I think I might know the issue.

The only time I've had problems with the spinbot/melee bot/aimbot is under intense lag. Make sure you are using the closest region to you when you matchmake.
