### ISSUE TITLE
Broken again 

### ISSUE THREAD

**Issue by bobcena777** [IceHacks/SurvivCheatInjector#576]
**Describe the bug**
Broken

**Expected behavior**
For it to work
**Screenshots**
![image](https://user-images.githubusercontent.com/69545617/90681107-b8285e80-e217-11ea-8385-adfbbdc9a98b.png)

**Cheat version**
(2.1.6)

**Chromium version**
84.0.4147.125

**Comment by WYLDYR** [comment]
Hi! I have a few guesses on how to fix this.

First, try to reload the cheat.
Head to your search bar, and type in "chrome://extensions". This will lead you to the extensions page.
Click the small circular arrow button in the bottom right of the cheat to reload it, or just turn it off and on again.

Second, try to delete your cookies. This may cause an issue.

Third, make sure your cheat is fully updated. New patches come all the time.

- WYLDYR

**Comment by BestContributor402** [comment]
Version 2.1.6.1 fixed this issue.
