### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by SuperMinh2008** [IceHacks/SurvivCheatInjector#577]
The gun and the player keeps shaking when it shoots another player with aimbot on

I expected It to be smoothly like version 2.1.5.2 and before

version:2.1.6.1

Google Chrome | 84.0.4147.135 (Official Build)
-- | --

**Comment by dinhanhx** [comment]
It's the feature

**Comment by Avatar-Kyoshi-Roku** [comment]
im having this same problem

**Comment by Gurwinder399** [comment]
When shooting moving toooo much
-_-

**Comment by Gurwinder399** [comment]
So always im using melee
