### ISSUE TITLE
There should be a keybind to toggle on/off aimbot

### ISSUE THREAD

**Issue by SniperXKiller** [IceHacks/SurvivCheatInjector#585]
I suggested this so people can try to do a 360 no scope, and turn aimbot back on and destroy the other player. This way, people probably will not suspect that you are hacking because usually, aimbot users can NOT turn around near enemies. Also, if you open the cheat menu to do this, it is pretty slow, and it covers up a quarter of your screen.

**Comment by bobcena777** [comment]
It's already there... you can toggle it off 
You just have to scroll down, it has keys that you can change by yourself like space, x, 1, 2, 3, stuff like that

**Comment by humphreygaming** [comment]
Its called inverted aim
