### ISSUE TITLE
Regarding new update

### ISSUE THREAD

**Issue by agransh** [IceHacks/SurvivCheatInjector#587]
Please update the hacks, a new update to the game is out right now and these hacks are not working

**Comment by humphreygaming** [comment]
consider fixing it yourself, then coming back

**Comment by bobcena777** [comment]
@agransh it works, dunno why it doesnt for u -- try reinstalling it

**Comment by LocoPETRAx47** [comment]
> @agransh it works, dunno why it doesnt for u -- try reinstalling it

same for me,it work but something is wrong however :d

**Comment by JIAJIAPNXA** [comment]
the cheat is broken, ESP sometimes breaks,you can fix it by reinstalling the cheat. but then it will break again. sometimes the auto-aim reacts to allies.

**Comment by bobcena777** [comment]
@humphreygaming the hack is fixable right?
