### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by WinterCf** [IceHacks/SurvivCheatInjector#590]
After the new update, cheats work great other than after a game is won or ended by death you will need to close the browser and reopen, other than that keep it up boys

**Comment by yeeter2003** [comment]
i had the same problem bro i dunnoh how to fix do u think update wil come i hope so

**Comment by WinterCf** [comment]
probably but its not too too serious

**Comment by yeeter2003** [comment]
but it is still a lil annoying that u cant hop on the next game really fast
