### ISSUE TITLE
2.1.6.2

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#596]
Redownload

Thats it

**Comment by Avatar-Kyoshi-Roku** [comment]
is it really?

**Comment by Avatar-Kyoshi-Roku** [comment]
nvm this works way better

**Comment by hahahshs972** [comment]
humphreygaming can you put suriv,io private server hacks out i whould apprieseat it

**Comment by russyboy** [comment]
Nice hack for my pc, but for potato mode,can't auto fire the potato cannon and the potato gun,I could  just auto aim but no auto fire, and need to use mouse to manually fire.
Please fix

**Comment by Madmax61** [comment]
It really works bad in low end pcs

**Comment by russyboy** [comment]
@Madmax61 what pc do you use?

**Comment by Madmax61** [comment]
A very low end old days pcc with 4gb ram

**Comment by russyboy** [comment]
@Madmax61 GG
