### ISSUE TITLE
can u put out surv private server hacks man whould appresate it

### ISSUE THREAD

**Issue by hahahshs972** [IceHacks/SurvivCheatInjector#597]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by availablenow** [comment]
You can't really, private servers are basically someone running Surviv.io on their own server (Or rented). So either it's going to cost money, or you could program your own one, it'll take a lot of time, and you can always just use the twitch server (Almost the same as private servers)

**Comment by humphreygaming** [comment]
already asked vinny, idk about it
