### ISSUE TITLE
What's inverted aim and how to use it?

### ISSUE THREAD

**Issue by fire-and-ice582** [IceHacks/SurvivCheatInjector#599]
What is inverted aim? I'm not sure wut it does. How does it work in game?

**Comment by humphreygaming** [comment]
hold right click to aim, release to turn off aimbot

**Comment by fire-and-ice582** [comment]
woah inverted aim op its rlly good

**Comment by Madmax61** [comment]
The aim sometime works and someone doesn't why idk. Even other features like auto Sniper switch doesn't work! Please help me?!
