### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by Natan1982** [IceHacks/SurvivCheatInjector#6]
Hey ice, just to you know, i'm getting freezes on this lasted .rar file.

**Comment by vietguy64225** [comment]
Hey ice, it's still freezing most of the time. I press Ctrl+F5 or refresh the browsers and it still freezes. I had everything on except auto loot. I also turned off auto aim and auto loot and it still freezes. Happened 7PM PST when it started freezing consistently.

**Comment by reflexin** [comment]
3rd this. Freezing for me and a friend.

**Comment by system123786** [comment]
Yeah I have been experiencing freezes aswell

**Comment by IceHacks** [comment]
Hmm. I as well experienced this for a short period of time yesterday. However, nothing on the frontend (client-side) seems to have changed. Only the backend (server-side) might've changed. I'll do some tests.

**Comment by IceHacks** [comment]
I haven't had a freeze in a few hours so I can not fix it. When it happened it only did it in full-screen mode.

**Comment by IceHacks** [comment]
Try reverting to an older one if it still is freezing. If that fixes it tell me.

@Natan1982 @vietguy64225 @reflexin @system123786

**Comment by Natan1982** [comment]
I'll try @IceHacks

**Comment by vietguy64225** [comment]
@IceHacks i used 2019-JUN-1_10-38.zip then updated to  	2019-JUN-3_18-24.zip when it froze. I did play full screen mode and also full windowed mode. I'll try again today with full screen/full windowed/not full window mode.

**Comment by IceHacks** [comment]
@vietguy64225 @Natan1982 thank you very much. You are both being very helpful.

**Comment by Natan1982** [comment]
Reversed from lasted to 2019-JUN-3_12-1, played 5 games without any freeze.
on lasted as lasting 1 or 2 games max.

@IceHacks

**Comment by IceHacks** [comment]
Ok, did you freeze today on the latest? Right now I am using a custom build.

**Comment by Natan1982** [comment]
Yeah, just used last right before reverse it, and freezes on first game.
If this 2019jun3121 freezes, i'll report here.

**Comment by IceHacks** [comment]
Ok, good to know. I will have a nearly duplicate release published later today.

**Comment by IceHacks** [comment]
It seems to only freeze if the first match you played in was fullscreen. I still don't know why.

**Comment by Natan1982** [comment]
@IceHacks I dont use fullscreen btw.

**Comment by IceHacks** [comment]
@Natan1982 Ok, I will look into it. Currently, only one game has frozen for me in the last 2 hours.

**Comment by vietguy64225** [comment]
@IceHacks I tried the last 3 updates and it freezes for me in windowed full screen/full screen/and not full screen. Happened 3 times in a row for each. Played 9 times.

**Comment by IceHacks** [comment]
Ok, thank you.

**Comment by Natan1982** [comment]
@IceHacks Yeah, freezing even with JUN update btw.

**Comment by vietguy64225** [comment]
@IceHacks Been playing the past few hours and it freezes almost every game. 1 or 2 is playable. any ETA update?

**Comment by IceHacks** [comment]
@vietguy64225 No ETA right now. Sorry about the freezes. Still, I have only had two today which is enough for me to find out why.

**Comment by herbieLoaded** [comment]
I am trying all of listed builds. "2019-MAY-31_15-41.zip" experiences no freezes so far.

**Comment by IceHacks** [comment]
Ok thank you @herbieLoaded

**Comment by IceHacks** [comment]
@Natan1982 @vietguy64225 @reflexin @system123786 @herbieLoaded Found source of the freeze patching.

**Comment by vietguy64225** [comment]
@IceHacks I just downloaded the June 4 Build... so far it froze once

**Comment by IceHacks** [comment]
Thank you. I have not yet released the patch still testing

**Comment by IceHacks** [comment]
If this hasn't been fixed please reopen. But for the time being, I think it has.

**Comment by IceHacks** [comment]
Thanks for all your help @vietguy64225 @Natan1982 @reflexin @system123786 should be fixed
