### ISSUE TITLE
how to get the bot

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/SurvivCheatInjector#60]
HOw to get the bot

**Comment by eimonpakzad** [comment]
when the bot update will come

**Comment by u1qqlv** [comment]
he showed demo using some terminal in linux I think, 
but he said he will deliver some executables that will do that job, my idea is to make the hack work in separate browser window or maybe other device on browser..,
just keep it simple not need for .exe or terminal XD

**Comment by IceHacks** [comment]
@u1qqlv The thing about that is it does work in another browser window. However, surviv only runs if the tab is active.
