### ISSUE TITLE
Help me?!

### ISSUE THREAD

**Issue by Madmax61** [IceHacks/SurvivCheatInjector#600]
The aim sometime works and someone doesn't why idk. Even other features like auto Sniper switch doesn't work! Please help me?!

**Comment by russyboy** [comment]
@Madmax61 please press Ctrl+F5(force reload)

**Comment by Madmax61** [comment]
It's much better but still not the experience which we used to have earlier

**Comment by availablenow** [comment]
Actually, the auto-aimer doesn't guarantee you a hit, but it does increase your chance a lot more than regular aiming

**Comment by me505** [comment]
i have potato LAPTOP with intel hd graphic 400 and intel n3060 celeron with 2 sticks of ddr3 2gb

**Comment by russyboy** [comment]
@me505 GG
