### ISSUE TITLE
LOL need new version of surviv hack

### ISSUE THREAD

**Issue by AsiaGuy** [IceHacks/SurvivCheatInjector#602]
**Describe the bug**
Aimbot sometimes work and sometime doesn't, EPS doesn't work any more and Pan hero is dead too.

**Expected behavior**
I don't know.

**Screenshots**
Hmmmmmmmmmmmmmmm.

**Cheat version**
2.1.6.2

**Chromium version**
85.0.4183.102

**Comment by Madmax61** [comment]
Hmm, ik same thing occurs with me. Though I use opera.

**Comment by AsiaGuy** [comment]
I think we need new hack. What do u think?

**Comment by AsiaGuy** [comment]
HI

**Comment by AsiaGuy** [comment]
Fuck you
