### ISSUE TITLE
Latest.zip

### ISSUE THREAD

**Issue by animedragon350** [IceHacks/SurvivCheatInjector#603]
Latest.zip isn't there.

**Comment by AsiaGuy** [comment]
What? Are you watch the old video of surviv.io hack?

**Comment by AsiaGuy** [comment]
https://github.com/IceHacks/SurvivCheatInjector/releases/download/2.1.6.2/Surviv.io.Cheat.Injector.2.1.6.2.zip

**Comment by russyboy** [comment]
always look on https://github.com/IceHacks/SurvivCheatInjector/releases
