### ISSUE TITLE
help

### ISSUE THREAD

**Issue by skylerholter** [IceHacks/SurvivCheatInjector#604]
**Describe the bug**
after the first game esp will stop working

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
I use Opera but the bug happens in chrome to

**Comment by AsiaGuy** [comment]
Just press CTRL+F5(force reload) or go to the new website of surviv.io

**Comment by russyboy** [comment]
@skylerholter redownload the cheat

**Comment by russyboy** [comment]
delete the cheat first

**Comment by russyboy** [comment]
and always look on https://github.com/IceHacks/SurvivCheatInjector/releases
