### ISSUE TITLE
Doesn't have manifest so not loading

### ISSUE THREAD

**Issue by Gurwinder399** [IceHacks/SurvivCheatInjector#606]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by bobcena777** [comment]
redownload, it works for me.

**Comment by AsiaGuy** [comment]
Yeah just reload it, press CTRL+F5.

**Comment by russyboy** [comment]
ya redownload the cheat

**Comment by russyboy** [comment]
and just like @AsiaGuy press CTRL+F5
