### ISSUE TITLE
Not aiming on enemy

### ISSUE THREAD

**Issue by prospecx** [IceHacks/SurvivCheatInjector#607]
**Describe the bug**
When I use the hacks its all over the place. It keeps going all around the enemy and im lucky if the bullets even hit.
**Expected behavior**
I thought the hacks would just lock on 
**Screenshots**
Sorry but I have no screenshots cause I cant screenshot aimbot going off a person
**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by codergautam** [comment]
same happening to me. i can aim better without the aimbot lol

**Comment by AsiaGuy** [comment]
Aimbot is going to destroy lol

**Comment by russyboy** [comment]
@prospecx delete the cheat and try downloading it again
