### ISSUE TITLE
I can do it!!!

### ISSUE THREAD

**Issue by AsiaGuy** [IceHacks/SurvivCheatInjector#609]
Can I help you improve the hack? I'm the new programmer. Can you help me?

**Comment by hahahshs972** [comment]
> Can I help you improve the hack? I'm the new programmer. Can you help me?

hey what u gonna make maybe customs hacks

**Comment by hahahshs972** [comment]
tell me ur discord asia guy

**Comment by humphreygaming** [comment]
go over to the source code and do stuff there
