### ISSUE TITLE
when are you going let us get bot

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/SurvivCheatInjector#61]
when are you going let us get bot

**Comment by IceHacks** [comment]
that's not a feature request or a bug please stop opening issues. Check my YouTube.

**Comment by u1qqlv** [comment]
you better create your own bot then asking from someone, I remember features not going public for months XD you will wait till horse Easter (this is how it is said in my country, I don't there is a translation for this) XD

**Comment by IceHacks** [comment]
No @u1qqlv it will be released tomorrow. As my YouTube says. If everything goes right.
