### ISSUE TITLE
TwitchTV Surviv.io Cheat Extension 

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#610]
https://cdn.discordapp.com/attachments/733735595532353616/770107742018076672/Twitch_Cheat.zip
^While the link lasts. Basically surviv plus. Aimbot is trash just like the people who stole it.

**Comment by hahahshs972** [comment]
btw this is my hack and u know this is a ip logger :)

**Comment by hahahshs972** [comment]
u know u chould of put spinbot lmafo to show its urs the aimbot is broken ask vinny to fix it and also vinny did nothing to 2.17

**Comment by AsiaGuy** [comment]
How to ???

**Comment by hahahshs972** [comment]
asia guy whats ur discord

**Comment by AsiaGuy** [comment]
Hey how to use it and how it work?
