### ISSUE TITLE
Reoccuring bug

### ISSUE THREAD

**Issue by SuperNova05** [IceHacks/SurvivCheatInjector#614]
When using the hack my player sometimes will move randomly without me pressing any keys. And this is with autoattack and autoshoot on false. Sometimes it'll be just for a second that ill move without pressing keys but sometimes its for up to 30 seconds and there's nothing I can do besides reload the page

V 2.1.7

86.0.4240.183

**Comment by russyboy** [comment]
hi @SuperNova05 ,you can click on the settings button on the starting page on surviv.io , and you can find a toolbox for the cheat on left hand side( just config on them)

**Comment by russyboy** [comment]
if it wont work, just deleted the cheat and redownload again
