### ISSUE TITLE
Quickswitch

### ISSUE THREAD

**Issue by InstantNo0dle** [IceHacks/SurvivCheatInjector#615]
**Describe the feature you'd like**
Add smart switch to quickswitch for shotguns, snipers, etc

Also does anyone know what happened to Epic-Hacks, the icehacks skid? xD it has been down for 3 months now, but it did have some good features, like this quickswitch

**Comment by russyboy** [comment]
@InstantNo0dle just click on the settings button and you'll see the tool box for the cheat (left hand side)

**Comment by russyboy** [comment]
inncludes sniper switch and smart switch

**Comment by russyboy** [comment]
sniper switch switches between the shotgun and the sniper gun( after one shot of either one)
