### ISSUE TITLE
Aimbot broken

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#618]
**Describe the bug**
Aimbot always cant shoot to enemy i always need to fight with enemy on close range ah yes... esp broken. when this will be fixed

**Expected behavior**

**Screenshots**

**Cheat version**
(ex: 1.1.0)

**Chromium version**
(go to chrome://version/)

**Comment by AsiaGuy** [comment]
Use CTRL+F5 or Zoom the surviv.io page

**Comment by AsiaGuy** [comment]
Also turn off the high resolution, screen shake and quest notification

**Comment by JIAJIAPNXA** [comment]
that fixed it but anyway sometimes that shoot bad

**Comment by russyboy** [comment]
@JIAJIAPNXA ok good
