### ISSUE TITLE
ESP Flashlight Bug

### ISSUE THREAD

**Issue by Nerdskillz** [IceHacks/SurvivCheatInjector#619]
**Describe the bug**
The ESP "Flashlight" Jitters around when moving, because there is a moving state and a non moving state of the "Flashlight"

**Expected behavior**
No Jittering-around Flashlight.

**Screenshots**

**Cheat version**
2.1.7

**Chromium version**
86.0.4240.183 (64 bit)
(doesnt matter in this case)

**Comment by AsiaGuy** [comment]
It doesn't matter, when you shoot it flash

**Comment by russyboy** [comment]
not a problem

**Comment by russyboy** [comment]
it doesnt affect the performance of the cheat
