### ISSUE TITLE
Not loading. Endless loading screen

### ISSUE THREAD

**Issue by Tofufish0705** [IceHacks/SurvivCheatInjector#620]
**Describe the bug**
Won't load whenever I open up surviv.io in my browser. I just see an endless loading screen for the missions tab and account login tab.

**Expected behavior**
Quick start up and login when surviv.io opened in browser

**Screenshots**

**Cheat version**
2.17

**Comment by ay232** [comment]
+1 with the same problem

**Comment by ay232** [comment]
writing: waiting analitycs.kongcreate.io

**Comment by AsiaGuy** [comment]
It's lagger than u don't install hack

**Comment by russyboy** [comment]
click on ctrl+f5

**Comment by russyboy** [comment]
try

**Comment by AsiaGuy** [comment]
I tried but it still loadddddddd and lagggggggg

**Comment by russyboy** [comment]
@AsiaGuy what browser are you using

**Comment by AsiaGuy** [comment]
chrome
