### ISSUE TITLE
A melee range added

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#623]
**Describe the feature you'd like**
when using melee weapons, I want to know how far the range it covers.

**Describe alternatives you've considered**
add a clear range of the melee weapon( like the other weapon range like AK-47, m870 etc.)

**Additional context**

**Comment by AsiaGuy** [comment]
The same idea as me

**Comment by russyboy** [comment]
@humphreygaming can you add it?

**Comment by humphreygaming** [comment]
if i knew how to code I would

**Comment by russyboy** [comment]
lol this would be "melee flashlight"
