### ISSUE TITLE
Get fucked, seriously

### ISSUE THREAD

**Issue by btyler** [IceHacks/SurvivCheatInjector#626]
**Describe the feature you'd like**
1. Fuck yourselfs. Jump off a cliff, or do something more useful with your lives.
**Describe alternatives you've considered**

**Additional context**

**Comment by russyboy** [comment]
this is useful

**Comment by russyboy** [comment]
if you don't like hackers then quit

**Comment by JIAJIAPNXA** [comment]
Seems like he told about hack is broken

**Comment by btyler** [comment]
> if you don't like hackers then quit

Suck a dick.

**Comment by russyboy** [comment]
> Seems like he told about hack is broken

no

**Comment by russyboy** [comment]
he hate hackers

**Comment by russyboy** [comment]
> > if you don't like hackers then quit
> 
> Suck a dick.

then fuck off

**Comment by russyboy** [comment]
and quit surviv.io

**Comment by JIAJIAPNXA** [comment]
maybe he do not know surviv io do not have hackers more because hacks is destabilished by autoaim bug

**Comment by btyler** [comment]
> and quit surviv.io

I would shit in your face given the chance.

**Comment by russyboy** [comment]
> > and quit surviv.io
> 
> I would shit in your face given the chance.

fuck you bitch fuck off

**Comment by JIAJIAPNXA** [comment]
он реально не догадывается о том что в игре нет читеров... разве что отчаянные но они не опасны поскольку без аимбота они мало на что способны

**Comment by humphreygaming** [comment]
done
