### ISSUE TITLE
What is Bumpfire?

### ISSUE THREAD

**Issue by WindexSniper** [IceHacks/SurvivCheatInjector#627]
What is bumpfire? and Why does it have 3 orange exclamation marks on it in the hack menu? Thank you so much for the amazing hacks! keep developing!

**Comment by russyboy** [comment]
Hi @WindexSniper ,thanks for your great comment!

Bump fire in real life is using the recoil of a semi-automatic firearm to fire ammunition cartridges in rapid succession, but with a loss of accuracy.

That means it changes semi-auto guns in surviv.io to full auto! ( like a rapid clicker turning a semi-auto pistol like m9 like a full auto pistol! )

When you are in a normal game without hack, you need to click your mouse multiple times to make a semi-auto gun shoot faster. (but too slow and will make your hands tired like in real life too )

With this hack, the hack auto clicks when using a semi-auto gun to shoot, making it into a "full auto" gun!

Secondly, the three orange exclamation marks is a reminder, to remind you to open this option to make a semi auto gun change to a "full auto" gun!

@WindexSniper , thank you for commenting on this page! If you have any questions, feel free to ask! 

Russyboy

**Comment by russyboy** [comment]
you're new to github?
