### ISSUE TITLE
Confused Aimbot

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#628]
when will aimbot be repaired? it just shoots anywhere and sometimes does not work (very rarely works as it should but 3 seconds) while this bug was a very long time ago. ah yes anti smoke doesn't work.

ver 2.1.7(cheat)

**Comment by russyboy** [comment]
me too I cant fix this

**Comment by russyboy** [comment]
P.S. I am not the maker of the hack
