### ISSUE TITLE
Code is obfusicated

### ISSUE THREAD

**Issue by SHA-01** [IceHacks/SurvivCheatInjector#629]
I have experience in making various hacks including agar.io private server bot script. If for security reasons you can't leak the original code, could you personally give it to me? Also I want to join the project. If needed I want to see the code and fix or add come features.

**Comment by russyboy** [comment]
Hi @SHA-01 go to this link
 
1.
https://github.com/humphreygaming/IceHacksGP-Product-Pack

2.
https://github.com/humphreygaming/surviv-cheat-source

**Comment by StabbyAlbert** [comment]
https://discord.gg/pFmgVnTkX2
Icehacks is here

**Comment by russyboy** [comment]
> https://discord.gg/pFmgVnTkX2
> Icehacks is here

nothing happens when I click on it
