### ISSUE TITLE
Request: Custom Skins

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#63]
Bored with the current skins but got interested when they updated the loadout options, and I was wondering if you can change the skins to something else you want (like the smoke custom texture thing). I tried intersecting http://surviv.io/api/user/profile and replacing it with something (didn't work)

**Comment by Sam1370** [comment]
@IceHacks dude it's an enhancement label, the point is for you to add it to your hack. you shouldn't close it...
