### ISSUE TITLE
the reason iBLiSSIN disappeared and did not return

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#633]
Hey everyone, do you know why the iBLiSSIN quit? All reason is here!!! Link: https://github.com/iBLiSSINonYT/survivio-plus/issues/2 

NOTE: i am a fan of iBLiSSIN, not iBLiSSIN

**Comment by IceHacks** [comment]
and what does this have to do with me or the cheat?

**Comment by iBLiSSIN** [comment]
I did think you care to iBLiSSIN lol
