### ISSUE TITLE
Zoom with scroll wheel

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#634]
The ice hacks need have the aimbot with customizable prediction with speed settings 
and custom zooming control with scroll wheel

**Comment by iBLiSSIN** [comment]
I think my idea will be difficult for you for a long time

**Comment by iBLiSSIN** [comment]
Or you can’t do it

**Comment by iBLiSSIN** [comment]
Sorry for bringing your important archive as a place for me to post news. I'M SO SORRY

**Comment by JIAJIAPNXA** [comment]
Did you mean that i can zoom my camera,even if i do not have any zoom or this just scrolls all zooms what I got?

**Comment by iBLiSSIN** [comment]
You not have the scope but you can zoom your visual

**Comment by iBLiSSIN** [comment]
with scroll wheels

**Comment by JIAJIAPNXA** [comment]
well okay then

**Comment by iBLiSSIN** [comment]
Easy to understand my idea
