### ISSUE TITLE
How to fix aimbot

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#636]
**Describe the bug**
Aimbot is broken that always  miss and work only when u use closerange weapon(knife,axe) how to fix that

**Comment by iBLiSSIN** [comment]
Do you broken the hack?

**Comment by iBLiSSIN** [comment]
If you keep the original hack as before and don't interfere with it, aimbot will not break as you said

**Comment by russyboy** [comment]
Don't worry, surviv cheatinjector 3.0 is coming soon

**Comment by JIAJIAPNXA** [comment]
i am never redacted the hack (i cant do that) surviv io with its updates are brokened this.

**Comment by JIAJIAPNXA** [comment]
and i really do not know how to fix this

**Comment by JIAJIAPNXA** [comment]
about 3.0... icehacks do flaslight for 10 days and this still not finished and you really sure that will be "soon" -_-
