### ISSUE TITLE
Avoid AutoShoot at reflectable materials

### ISSUE THREAD

**Issue by RocketNinja15** [IceHacks/SurvivCheatInjector#637]
**Describe the bug**
Well, the aimbot will shoot at metal doors, therefore killing you
**Expected behavior**
It to wait until door is open
**Screenshots**

**Cheat version**
2.1.7

**Opera version**
(go to chrome://version/)
72.0.3815.487

**Comment by AsiaGuy** [comment]
I think it think that the original door is breakable and also for the metal door -_-

**Comment by IceHacks** [comment]
did they make doors not destroyable?

**Comment by russyboy** [comment]
@IceHacks no

**Comment by russyboy** [comment]
original doors are made with wood, bullets can break it, metal doors reflect bullets therefore killing players.(metal doors are not destroyable even for grenades)

**Comment by IceHacks** [comment]
ok
