### ISSUE TITLE
Make AimBot Prioritize the More Dangerous Player

### ISSUE THREAD

**Issue by RocketNinja15** [IceHacks/SurvivCheatInjector#638]
**Describe the feature you'd like**
What would happen is aimbot would prioritize depending on your setting. Ex: Health vs Distance
**Describe alternatives you've considered**
Nope :)
**Additional context**
Recently I lost a game because there were 4 people different distances from me, and it couldn't decide

**Comment by IceHacks** [comment]
The enemies health is unknown

**Comment by russyboy** [comment]
yes

**Comment by russyboy** [comment]
with this hack you will only know what is the enemies name

**Comment by 068scar** [comment]
N00b
