### ISSUE TITLE
Project 3.0

### ISSUE THREAD

**Issue by AsiaGuy** [IceHacks/SurvivCheatInjector#642]
Umm...Can i just help you to do the project 3.0? I want to help you guy!!

**Comment by JIAJIAPNXA** [comment]
yeah help him he cant do flashlight in 12 days

**Comment by AsiaGuy** [comment]
ohhhh i will help him
The info about flashlight is in the surviv.io wiki :D

**Comment by IceHacks** [comment]
I haven't worked on it. I finished flashlight the day I put it up as in progress,
