### ISSUE TITLE
Please let me contribute the hack.

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#643]
Please allow me access to the hacks.

**Comment by AsiaGuy** [comment]
Yeah he is very tired about the flashlight XDDD!

**Comment by iBLiSSIN** [comment]
Yep. But I did fix the flashlight, change aimbot 2.0 be aimbot 1.0 and make a Bot Sender TM

**Comment by iBLiSSIN** [comment]
And I want contribute it :)

**Comment by JIAJIAPNXA** [comment]
i am not sure 3.0 will soon,

**Comment by JIAJIAPNXA** [comment]
but if he will agree this message i think this will be faster

**Comment by iBLiSSIN** [comment]
Do you want it? The aimbot 1.0. I have a link!

**Comment by AsiaGuy** [comment]
really?

**Comment by iBLiSSIN** [comment]
Yes

**Comment by iBLiSSIN** [comment]
And it have new features need use to know

**Comment by JIAJIAPNXA** [comment]
yeah i want it 2.0 is fatal destabilished

**Comment by iBLiSSIN** [comment]
Here: https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1

**Comment by JIAJIAPNXA** [comment]
thanks

**Comment by iBLiSSIN** [comment]
Ha ha
