### ISSUE TITLE
The hack is not boost "frame per second" and some idea

### ISSUE THREAD

**Issue by AsiaGuy** [IceHacks/SurvivCheatInjector#644]
I think we should boost fps by disable some effect, can you do it?
Also, we should add the trickshot aimbot make it more dangerous >:) 
Oh i forgot, we better add the flashlight for the potato guns and melee hit range

**Comment by iBLiSSIN** [comment]
This potato gun always has no range because its projectile is always straight even when you move. As for a melee weapon, its range should be displayed, but are you so bad that you can't determine the range of a melee weapon? And I accept the rest of your ideas.

**Comment by iBLiSSIN** [comment]
Ô Việt Nam à? YouTube đây à : https://m.youtube.com/channel/UCu9QqrqPeaFFOsXtP1xrKRg

**Comment by iBLiSSIN** [comment]
Làm thế nào để aimbot tính toán ít đi thế?

**Comment by AsiaGuy** [comment]
I think lag is the cause of the problem. I tested in my old and new pc and the new one work pretty good :)

**Comment by iBLiSSIN** [comment]
Do you understand Vietnamese?

**Comment by AsiaGuy** [comment]
yes but i prefer talking English than talking Vietnamese :)

**Comment by IceHacks** [comment]
Already done
