### ISSUE TITLE
***OFFICIAL ICEHACKS SUPPORT SERVER***

### ISSUE THREAD

**Issue by StabbyAlbert** [IceHacks/SurvivCheatInjector#647]
Greetings, Albert here. Bellow you can find the support server for icehacks (Yay). Now instead of wondering why your issue was closed, you can spam ping us questions.
[Our useless server (join if you want)](https://discord.gg/RbjuAPvrwc)

**Comment by russyboy** [comment]
Thanks mate I finally can join the discord server

**Comment by IceHacks** [comment]
It will stay pinned even when closed, don't worry.
