### ISSUE TITLE
HELLO AIMBOT?

### ISSUE THREAD

**Issue by ImORllEA** [IceHacks/SurvivCheatInjector#648]
AIMBOT ON SURVIV IS BROKEN?!?!?!

**Comment by JIAJIAPNXA** [comment]
yep,i hope IceHacks will fix that

**Comment by IceHacks** [comment]
eh

**Comment by russyboy** [comment]
not broken

**Comment by russyboy** [comment]
I can still use it properly and I can get 20 kills in surviv

**Comment by IceHacks** [comment]
so is it broke or not? Either way, I don't want to work on 2.0 code.

**Comment by ImORllEA** [comment]
> so is it broke or not? Either way, I don't want to work on 2.0 code.

YES ITS BROKEN
pls release 3.0 i need it also when DO you plan on realising 3.0

**Comment by IceHacks** [comment]
idk, releasing a video on it today tho

**Comment by JIAJIAPNXA** [comment]
Aimbot 2.0 is broken it shoots with a giant pre-emption sometimes it just doesn't work and insanely rarely works correctly ( and then not for long). (i used tranlslator)

**Comment by JIAJIAPNXA** [comment]
Icehacks can you fix 2.0? this is really broken for some players like me and i do not know how to fix this (reinstalling doesn't help i tried to install this on other browser)

**Comment by JIAJIAPNXA** [comment]
will you fix that?

**Comment by russyboy** [comment]
eh

**Comment by russyboy** [comment]
or you try to update your browser?

**Comment by russyboy** [comment]
I think it will work?

**Comment by russyboy** [comment]
> so is it broke or not? Either way, I don't want to work on 2.0 code.

ok just dont work on 2.0

**Comment by russyboy** [comment]
or it will be not fair for players who want to play surviv hacks

**Comment by JIAJIAPNXA** [comment]
i tried to play with this hack on opera gx and it still dont work

**Comment by DEPRESED333** [comment]
idk how do u get free gp?

**Comment by JIAJIAPNXA** [comment]
Offtop?

**Comment by JIAJIAPNXA** [comment]
well, will this fixed?

**Comment by humphreygaming** [comment]
wait for 3.0, somewhere in the near future
