### ISSUE TITLE
Aimbot 2.0 Destabilished...

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#649]
Aimbot 2.0 is broken that works only when i use melee. Aimbot 2.0 shoots in all directions but not at the enemy. I Tried reinstall this hack on other browser (Opera) but aimbot still destabilished. I tried to change settings but that dont helped me.
Aimbot 2.0 does not work ONLY for some players. 
Can you fix that?

**Comment by IceHacks** [comment]
#648
