### ISSUE TITLE
Auto Loot Toggle Key Bind/Message

### ISSUE THREAD

**Issue by SmoothKen** [IceHacks/SurvivCheatInjector#65]
In Duos, Squads and 50v50, players may want to toggle auto loot frequently to give teammates items. It will be nice if there is a customizable keybind for it (as long as it does not conflict with 'N'). And when user toggle it on/off using that keybind, an autoloot status message can be shown on the upper left corner.

**Comment by IceHacks** [comment]
Hey kid. There is an autoloot drop delay switch.

**Comment by SmoothKen** [comment]
Ohhh...I see...Sorry
