### ISSUE TITLE
Proper DPS with Pan addition

### ISSUE THREAD

**Issue by ImOsaym** [IceHacks/SurvivCheatInjector#651]
**Describe the bug**
If I'm using the pan and have a long-range gun equipped, the survivr will attempt to block each incoming bullet instead of prioritizing shooting, 

**Expected behavior**
I thought it would block a few and then shoot back

**Screenshots**
did not take any.

**Cheat version**
2.1.7
**Chromium version**
89.0.4389.82 MacOS Intel Chrome running over Rosetta 2 on M1 Mac

**Comment by IceHacks** [comment]
hmm

**Comment by IceHacks** [comment]
I didn't create the Pan addon. That was after my time. I'll look into it for v3.

**Comment by OzZVidz** [comment]
Cool!

**Comment by IceHacks** [comment]
Bring this back up after I add pan aim, if it isn't already implemented by then.

**Comment by ImOsaym** [comment]
Gotchu
