### ISSUE TITLE
Discord account nuked, please make new server humpy

### ISSUE THREAD

**Issue by StabbyAlbert** [IceHacks/SurvivCheatInjector#654]
Message for Humpy and Icey only, discord decided to kill my account cuz I was too cool for discord. I think they took our dead server along with it, anyways make a new server and get on with your day. And P.S leave some cookies out for me when I get back into the groupchat.

![Untitled](https://user-images.githubusercontent.com/46134756/111672871-c4e25480-87f0-11eb-93b5-f633bf27d684.png)

**Comment by humphreygaming** [comment]
https://discord.gg/MCtzrWW7BA
