### ISSUE TITLE
==AIMBOT 3.0== BETA CODE LEAKED!!! NEW OP AIMBOT HACK SURVIV.IO

### ISSUE THREAD

**Issue by codersalty** [IceHacks/SurvivCheatInjector#659]
**How to use?** 
Go to https://github.com/humphreygaming/surviv-cheat-source/
Download the code as zip
Extract Zip
Go to src/content.js
Add the code from pastebin at the top of the file
https://pastebin.com/cQWsE1yd
Save and press compiler.bat to compile the updated aimbot into a webpacked folder that can be understood by chrome
Compress the "out" folder
Drag the compressed zip into extensions like you normally do
Enjoy the newly updated beta 3.0 aimbot!
(you can enable by just enabling aimbot 2.0, the script overrides the default aimbot)

(make sure to leave a thumbs up if it worked!)

**Comment by JIAJIAPNXA** [comment]
i cant open js file and compiler bat opens and momentally closes. can u make vidio about this?

**Comment by azlmsxkn102** [comment]
can't run compiler.bat bro =D

**Comment by iBLiSSIN** [comment]
Wow why u know the code of aimbot 3.0?

**Comment by JIAJIAPNXA** [comment]
can u just make this hack with 3.0 aim and share with us.

**Comment by Caioz10** [comment]
![image](https://user-images.githubusercontent.com/65035375/113768248-00888400-96f6-11eb-977f-ad71b7bd12be.png)
I'm basically getting this error

**Comment by Caioz10** [comment]
Can anyone help me

**Comment by JIAJIAPNXA** [comment]
just re make this hack with 3.0 aim pls

**Comment by codersalty** [comment]
Make sure you have npm installed https://www.npmjs.com/ you need that to compile i belive

**Comment by codersalty** [comment]
and i cant remake the hack because i would get banned then oprobably

**Comment by codergautam** [comment]
OMG IT WORKED!!! YOOOO the new aimbots so insane theres like a few bugs where it glitches but I think ice will fix them before production but anyway nice job and for the people who cant get it to work your a noob lol

**Comment by russyboy** [comment]
wtf this is not beta ok?

**Comment by russyboy** [comment]
> **How to use?**
> Go to https://github.com/humphreygaming/surviv-cheat-source/
> Download the code as zip
> Extract Zip
> Go to src/content.js
> Add the code from pastebin at the top of the file
> https://pastebin.com/cQWsE1yd
> Save and press compiler.bat to compile the updated aimbot into a webpacked folder that can be understood by chrome
> Compress the "out" folder
> Drag the compressed zip into extensions like you normally do
> Enjoy the newly updated beta 3.0 aimbot!
> (you can enable by just enabling aimbot 2.0, the script overrides the default aimbot)
> 
> (make sure to leave a thumbs up if it worked!)

the cheat source is updated 8 months ago

**Comment by russyboy** [comment]
the pastebin one dont work?

**Comment by russyboy** [comment]
https://pastebin.com/cQWsE1yd    

is this official?

**Comment by azlmsxkn102** [comment]
![image](https://user-images.githubusercontent.com/59362729/113855791-a3123700-97ca-11eb-912a-c16a218d2ab1.png)

**Comment by codersalty** [comment]
> https://pastebin.com/cQWsE1yd
> 
> is this official?

no but its a leak fromicehacks

**Comment by codersalty** [comment]
> > **How to use?**
> > Go to https://github.com/humphreygaming/surviv-cheat-source/
> > Download the code as zip
> > Extract Zip
> > Go to src/content.js
> > Add the code from pastebin at the top of the file
> > https://pastebin.com/cQWsE1yd
> > Save and press compiler.bat to compile the updated aimbot into a webpacked folder that can be understood by chrome
> > Compress the "out" folder
> > Drag the compressed zip into extensions like you normally do
> > Enjoy the newly updated beta 3.0 aimbot!
> > (you can enable by just enabling aimbot 2.0, the script overrides the default aimbot)
> > (make sure to leave a thumbs up if it worked!)
> 
> the cheat source is updated 8 months ago

yes i could only leak the aimbot script idk about the other stuff from v3.0

**Comment by Caioz10** [comment]
dude I CANT INSTALL NODE JS I HAVE WINDOWS 7 IT DOESNT SUPPORT WINDOWS 7

**Comment by JIAJIAPNXA** [comment]
me too using windows 7

**Comment by russyboy** [comment]
> me too using windows 7

gggggg

**Comment by russyboy** [comment]
> > https://pastebin.com/cQWsE1yd
> > is this official?
> 
> no but its a leak fromicehacks

ok i trust you

**Comment by russyboy** [comment]
> Make sure you have npm installed https://www.npmjs.com/ you need that to compile i belive

is npm or node js???

**Comment by russyboy** [comment]
i am trying node js first

**Comment by JIAJIAPNXA** [comment]
windows 7 cant work on js files idk how to release aim3.0 to the surviv io

**Comment by Caioz10** [comment]
bruh I have windows 7 and I can basically open js files as txts and its working

**Comment by russyboy** [comment]
> bruh I have windows 7 and I can basically open js files as txts and its working

lol

**Comment by JIAJIAPNXA** [comment]
can you make a vidio how to do that with txt files and without compiler.bat

**Comment by IceHacks** [comment]
This is not v3.0, it's the public 2.0 code

**Comment by codersalty** [comment]
it isnt the whole 3.0 cheat itself, just the aimbot of 3.0...

**Comment by Caioz10** [comment]
> it isnt the whole 3.0 cheat itself, just the aimbot of 3.0...

Probably the title says It is the 3.0 aimbot

**Comment by IceHacks** [comment]
@codersalty no it isn't

**Comment by codersalty** [comment]
lol i got people to belive my random js code

**Comment by codersalty** [comment]
next time: make a script that downloads a virus onto your pc lol how to destroy the hackwrs

**Comment by JIAJIAPNXA** [comment]
u are just one of n00bs who very hates the hackers -_-

**Comment by Caioz10** [comment]
^
