### ISSUE TITLE
Auto loot picks up weapons that are worse than one in hand, please add more options for auto loot

### ISSUE THREAD

**Issue by Sam1370** [IceHacks/SurvivCheatInjector#66]
Auto loot randomly picks up weapons, please add option to disable picking up of weapons but not loot

**Comment by IceHacks** [comment]
It's just that if you are moving at a high velocity and your looting radius is wide it will pick up **anything** around what it wants to pick up, even if you disable guns. No way to stop it atm.

**Comment by Sam1370** [comment]
@IceHacks It's still an issue, whether you can stop it or not, please leave this issue open.

**Comment by u1qqlv** [comment]
but how mobile version uploads things? maybe you need to use a specific function that is used by mobile version, instead of stimulation F press key? I played on the mobile in browser mode and I loot automatically... with no hack...
