### ISSUE TITLE
Idea how to fix AimBot 2.0

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#660]
I played with aimbot 2.0... (and it still broken). i have Seen this aim sometimes shooting to trees and rocks. I think he see hostile in objects. Maybe if DELETE aim at objects this aim will work? (i disabled aim at objects and this aim still broken).

**Comment by JIAJIAPNXA** [comment]
exactly DELETE

**Comment by Caioz10** [comment]
I'm using Iblissin's SurvivCheatInjector fork and I get the same bug, but in this one (original) it doesn't shoot thee trees and rocks.. Strange

**Comment by iBLiSSIN** [comment]
> I'm using Iblissin's SurvivCheatInjector fork and I get the same bug, but in this one (original) it doesn't shoot thee trees and rocks.. Strange
What is your bug?

**Comment by iBLiSSIN** [comment]
> I'm using Iblissin's SurvivCheatInjector fork and I get the same bug, but in this one (original) it doesn't shoot thee trees and rocks.. Strange

What is your bug?

**Comment by Caioz10** [comment]
> > I'm using Iblissin's SurvivCheatInjector fork and I get the same bug, but in this one (original) it doesn't shoot thee trees and rocks.. Strange
> 
> What is your bug?

"The aim shoots to trees and rocks"

**Comment by russyboy** [comment]
eh

**Comment by russyboy** [comment]
or you try updating your browser?

**Comment by iBLiSSIN** [comment]
> > > I'm using Iblissin's SurvivCheatInjector fork and I get the same bug, but in this one (original) it doesn't shoot thee trees and rocks.. Strange
> > 
> > 
> > What is your bug?
> 
> "The aim shoots to trees and rocks"

Do u enable the “aim at object”

**Comment by humphreygaming** [comment]
Disable aim at object
