### ISSUE TITLE
Hey from where can I the latest verison

### ISSUE THREAD

**Issue by Madmax61** [IceHacks/SurvivCheatInjector#662]
Umm how to download the latest version?

**Comment by iBLiSSIN** [comment]
here https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1%2B or https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1

**Comment by Caioz10** [comment]
> here https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1%2B or https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1

That's your surviv cheat injector but I like it though

**Comment by humphreygaming** [comment]
> here https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1%2B or https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1

No self promotion please
