### ISSUE TITLE
Legit Cheats

### ISSUE THREAD

**Issue by NotAtic** [IceHacks/SurvivCheatInjector#663]
Hello, What if there were legit cheater in surviv.io like an legit aimbot that's not like those rage cheaters, I enjoy rage cheating in surviv.io but a legit one would be nice, legit aimbot that's not obvious, i'm good at quick switching so when im reloading it wont swap to another gun. This would be nice, dont know if you have added this or not or if you dont want it keep it in mind

Regards - Atic

**Comment by humphreygaming** [comment]
Custom LERP was somewhere in the cheat a while ago, and as of now LegitMode is a thing in the cheat, not sure if it works
