### ISSUE TITLE
codersalty rage kid

### ISSUE THREAD

**Issue by NotAtic** [IceHacks/SurvivCheatInjector#665]
Yall know the codersalty kid, reported him for spam yesterday didn't expect he will get banned that quick, https://github.com/codersalty

**Comment by JIAJIAPNXA** [comment]
Is he Banned now?

**Comment by Caioz10** [comment]
Yeah he is now

**Comment by NotAtic** [comment]
Yup he's banned reported him yesterday and he got banned today.
