### ISSUE TITLE
Super laggy hack needs to be updated

### ISSUE THREAD

**Issue by gstrk** [IceHacks/SurvivCheatInjector#67]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by IceHacks** [comment]
@gstrk Does not significantly change the frame rate of surviv.io, the most damage you would see is maybe a 20ms delay for calculations, but overall doesn't affect the game performance. The last update was only 10 days ago (1.1.4). Do you have an idea of something for me to add or are you just saying I should make an update that doesn't change anything?

**Comment by u1qqlv** [comment]
try restart browser, it works for me...
