### ISSUE TITLE
does not work with microsoft edge developer

### ISSUE THREAD

**Issue by joe-musashi9999** [IceHacks/SurvivCheatInjector#670]
**Describe the bug**
when one tries to import, it says, "Error: Manifest file is missing or unreadable"

**Expected behavior**
should work

**Screenshots**
![Extensions and 3 more pages - Personal - Microsoft​ Edge 5_3_2021 3_04_22 PM](https://user-images.githubusercontent.com/83614879/116939518-53842700-ac21-11eb-8b7e-c2f3530bb0da.png)

**Cheat version**
current

**Chromium version**
Microsoft Edge
Search result match: Version 90.0.818.51 (Official build) (64-bit)Version 90.0.818.51 (Official build) (64-bit)

**Comment by joe-musashi9999** [comment]
I would appreciate it if someone gave me info on why it doesn't work, is it different open source or what?

**Comment by iBLiSSIN** [comment]
U not download right hack file

**Comment by iBLiSSIN** [comment]
Download here: https://github.com/IceHacks/SurvivCheatInjector/releases/tag/2.1.7 by humphrey gaming  or https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1%2B by me lol

**Comment by joe-musashi9999** [comment]
thx

**Comment by iBLiSSIN** [comment]
> thx

Nothing XD
