### ISSUE TITLE
Add Smoke Transparency to the Cheat

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#671]
**Describe the bug**
The game fix your smoke not be transparent. (Be the IceHacks smoke)
**Expected behavior**
Fix it on 3.0 please.

**Screenshots**
Not have but everyone know it.

**Cheat version**
2.1.7

**Chromium version**
All versions 

the Humphrey gaming fastidious and close all problems lol

**Comment by iBLiSSIN** [comment]
Lol no one care this issue

**Comment by tripleD1999** [comment]
I do care :D

**Comment by NotAtic** [comment]
Whats your discord vn bpm

**Comment by iBLiSSIN** [comment]
I not have discord:( . I can’t sign up

**Comment by iBLiSSIN** [comment]
> Where can i get in contact with you???

email: nam12344567890asm@gmail.com

youtube: https://bit.ly/VNBPMchannel

**Comment by tripleD1999** [comment]
> > Where can i get in contact with you???
> 
> email: [nam12344567890asm@gmail.com](mailto:nam12344567890asm@gmail.com)
> 
> youtube: https://bit.ly/VNBPMchannel

I just subcribed your YT channel lol, https://www.facebook.com/katty.camile.3/ here my FB, we can add friend and play together :D

**Comment by iBLiSSIN** [comment]
> > > Tôi có thể liên hệ với bạn ở đâu ???
> > 
> > 
> > email: [nam12344567890asm@gmail.com](mailto:nam12344567890asm@gmail.com)
> > youtube: https://bit.ly/VNBPMchannel
> 
> Tôi vừa subcribe kênh YT của bạn lol, https://www.facebook.com/katty.camile.3/ đây FB của tôi, chúng ta có thể kết bạn và chơi cùng nhau: D

Ok my friends!

**Comment by NotAtic** [comment]
> > > > Tôi có thể liên hệ với bạn ở đâu ???
> > > 
> > > 
> > > email: [nam12344567890asm@gmail.com](mailto:nam12344567890asm@gmail.com)
> > > youtube: https://bit.ly/VNBPMchannel
> > 
> > 
> > Tôi vừa subcribe kênh YT của bạn lol, https://www.facebook.com/katty.camile.3/ đây FB của tôi, chúng ta có thể kết bạn và chơi cùng nhau: D
> 
> Ok my friends!
> 
> My facebook: https://www.facebook.com/profile.php?id=100058581720001&sk=about&section=bio

I will email you!

**Comment by russyboy** [comment]
I wanna play with you guys

**Comment by russyboy** [comment]
> > > Where can i get in contact with you???
> > 
> > 
> > email: [nam12344567890asm@gmail.com](mailto:nam12344567890asm@gmail.com)
> > youtube: https://bit.ly/VNBPMchannel
> 
> I just subcribed your YT channel lol, https://www.facebook.com/katty.camile.3/ here my FB, we can add friend and play together :D

me too

**Comment by iBLiSSIN** [comment]
> > > > Where can i get in contact with you???
> > > 
> > > 
> > > email: [nam12344567890asm@gmail.com](mailto:nam12344567890asm@gmail.com)
> > > youtube: https://bit.ly/VNBPMchannel
> > 
> > 
> > I just subcribed your YT channel lol, https://www.facebook.com/katty.camile.3/ here my FB, we can add friend and play together :D
> 
> me too

your fb pls
