### ISSUE TITLE
Send me 3.0 test version

### ISSUE THREAD

**Issue by NotAtic** [IceHacks/SurvivCheatInjector#672]
Hey can someone send me icehacks 3.0 test version ion have telegram

**Comment by JIAJIAPNXA** [comment]
will 3.0 private version? or u just want test 3.0 ver

**Comment by NotAtic** [comment]
3.0 test version is shit i use 1.0

**Comment by iBLiSSIN** [comment]
> 3.0 test version is shit i use 1.0

U make IceHacks hate u
