### ISSUE TITLE
Fix AimBot on Stairs; Add Distance Option to AutoAttack

### ISSUE THREAD

**Issue by tripleD1999** [IceHacks/SurvivCheatInjector#674]
**Describe the feature you'd like**
How about Fast reload, fast heal, fast adrenaline. If it work , there is no way to defeat (except another hacker)
Since it really impacted the game, Cheater has to pay to use. There are too many hacker nowaday, so a little cost may improve The Cheat

Other ideas:
no recoil
increase chance find a good gun when destroy crates or furnitures, like SV 98, Spas 12...
Also increase chance to be leader in 50v50 :D
Show other survivors on map
Show enemy's weapons holding

**Some issues**
When air strike coming, my FPS go low and laggy, so i think just disable blast radius on air strike... 
USAS-12 -> idk why an auto gun can quickswitch like Spas-12 :D  .Can it be fixed ?
The Aimbot won't work when enemy on the stair -_-
The Aimbot also won't work when holding a sniper near enemy, a survivr try to chase and use melee to atttack, i always die by this bug T.T

Hope my ideas work on Ice cheat v3.0 :D
Also i want to contribute my best to it but don't know where to start, hope you guys teach me how to :D

**Comment by NotAtic** [comment]
Does surviv.io even have recoil?
And the chance to increase leader in 50v50 is not possible, its random
Chance to find a good gun its random no one can do that its surviv.io

**Comment by tripleD1999** [comment]
> Does surviv.io even have recoil?
> And the chance to increase leader in 50v50 is not possible, its random
> Chance to find a good gun its random no one can do that its surviv.io

I think without recoil, the gun like MAC-10 will fire away as same as P30L :D

**Comment by IceHacks** [comment]
You cannot change the spread of the bullets. As for aimbot not working on the stairs, I will see about fixing that. For auto switching, you have to figure it out as of now. It is a placeholder crappy feature that has several timing options for you to play with. Turn off the auto attack if you don't want it to auto attack, I will add a feature for distance change if you want. I could make something to show other cheaters and allow collaboration, but I don't feel like that atm. Thanks.

**Comment by tripleD1999** [comment]
> I could make something to show other cheaters and allow collaboration, but I don't feel like that atm. Thanks.

Yay, I'm glad my idea has been noted :D

**Comment by IceHacks** [comment]
Distance option added. Others are in progress.
