### ISSUE TITLE
Melee aim range

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#675]
Make Hackers can control range on melee aimbot. Sometimes Melee aim not effective in some situations(fight on shotguns and other close range fights) my enemy can have more adrenaline than me and he can deffeat me when i running with melee aim,i am just will not too fast to kill him.

**Comment by iBLiSSIN** [comment]
Disable aimbot for a far range than u can kill him by a gun

**Comment by JIAJIAPNXA** [comment]
i am not scripter i cant disable aimbot for far range and im talking exactly about MELEE aimbot

**Comment by iBLiSSIN** [comment]
Disable it by press key u set in ‘binds’. Do u understand?

**Comment by IceHacks** [comment]
#674
