### ISSUE TITLE
flood with shell casings

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#677]
I noticed that if you take a discharged weapon like Revolvers or double barreled guns when you quickly press the x key the shell casings will quickly fall out why not make a cheat that automates this. That would be fun.

**Comment by IceHacks** [comment]
I'll have to check this bug out, is this client sided or can others see the shells?

**Comment by JIAJIAPNXA** [comment]
i saw player who reloaded revolver he dropped shells
and i just spammed X button with discharged revolver and some guy used "laugh" smile

**Comment by JIAJIAPNXA** [comment]
so what
