### ISSUE TITLE
Can you please put this on greasy fork?

### ISSUE THREAD

**Issue by WVVEY** [IceHacks/SurvivCheatInjector#68]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IceHacksSupport** [comment]
WVVEY This is not a userscript
greasyfork for userscripts
not extensions

**Comment by WVVEY** [comment]
ok then how can i get this thing when my developer tools is disabled by my school administrator??

**Comment by IceHacks** [comment]
@WVVEY It doesn't work like that. To my knowledge, you cannot. I might make a client, what is your system?
