### ISSUE TITLE
How to download sci 3.0 on telegram ?

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#681]
My stupid question and you can close it anytime as long as you answer me :)

**Comment by NotAtic** [comment]
Ugh, 3.0 test version is so shitty, you wouldn't like it tried its so bugged, eh i knew there were gonna be lots of bugs, but didn't expect that much bugs, since its a test version

**Comment by IceHacks** [comment]
> Ugh, 3.0 test version is so shitty, you wouldn't like it tried its so bugged, eh i knew there were gonna be lots of bugs, but didn't expect that much bugs, since its a test version

Ok fin.

@iBLiSSIN, simply join the TG. It is for the TG only, so if you can't figure it out, don't do it.

**Comment by IceHacks** [comment]
@iBLiSSIN do you have a telegram account?
