### ISSUE TITLE
KeyBinds

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#683]
**Describe the feature you'd like**
 Have more key binds to disable aimbot and spinbot (more than 2 binds instead 1 binds now ). And player show name should bigger (for more visible).

**Describe alternatives you've considered**
 Provide at 3.0.0 :)

**Additional context**
 not have

**Comment by IceHacks** [comment]
So, the ability to have multiple binds for one action?

**Comment by iBLiSSIN** [comment]
Yes and the bigger name

**Comment by iBLiSSIN** [comment]
My friend said can you provide follow bot lol

**Comment by russyboy** [comment]
> My friend said can you provide follow bot lol

lol
