### ISSUE TITLE
Make the cheat more undetectable 

### ISSUE THREAD

**Issue by AsiaGuy** [IceHacks/SurvivCheatInjector#687]
Today, I was banned for cheater. I think the developer updated the cheat dectect so I think we should also update the cheat so we can play without being banned. This is my snapshot about this:

![image](https://user-images.githubusercontent.com/69104195/118296275-fc2a6480-b506-11eb-867c-131edf532eca.png)

***Translated by Google***

**Comment by JIAJIAPNXA** [comment]
xd i got -50 prestiges and still alive

**Comment by IceHacks** [comment]
They probably implemented some reporting feature, as it is just an account ban. This looks like the 2.X cheat anyway, which all support for has been dropped.
