### ISSUE TITLE
Stop autoreload from interfering with auto crate breaker

### ISSUE THREAD

**Issue by siknite** [IceHacks/SurvivCheatInjector#689]
Auto reload will swap to the weapon it decides it wants to reload, auto crate breaker switches to your melee slot to break the crate you are next to. Aka creating a loop.

https://user-images.githubusercontent.com/84289166/118410347-41799e00-b68f-11eb-972d-54d70308d653.mp4

**Comment by siknite** [comment]
for 3.0

**Comment by iBLiSSIN** [comment]
Funny time lol

**Comment by russyboy** [comment]
gg

**Comment by IWasAPerson-1123** [comment]
It would be nice to be fixed but one way to solve this is to set auto reload to one keybind and auto crate breaker for a different keybind. If the loop occurs just click one of them to disable.

**Comment by IceHacks** [comment]
Some way to pause auto reload if standing near a destructible is needed.
