### ISSUE TITLE
Stop switching from gun to knife or hands when close to someone.

### ISSUE THREAD

**Issue by kaden-tech** [IceHacks/SurvivCheatInjector#690]
I have best gun enabled and it changes to a knife or my hands. When I switch back to gun manually it tries to reload and then in the middle of it it switches back to hands.

Perhaps you could make best gun not check for amount of ammo but have something else do that and continue auto-reload.

**Comment by siknite** [comment]
Do you mind sharing your settings? Since I'm having a hard time reproducing this issue

**Comment by iBLiSSIN** [comment]
Disable the “eqip melee “ in auto switch settings boy. It is ez to change and you can. And remember to set

**Comment by siknite** [comment]
Well by the way he's talking I'm assuming that he is talking about 3.0 which has no called auto-switch nor does "useBestGun" which is what he is using. but we could be sure if he shared his settings 'boy'.

**Comment by siknite** [comment]
Well, by the way he's talking I'm assuming that he is talking about 3.0 which has no option called auto-switch, also "useBestGun"  which is what he is using does not have "eqip melee". But we could be sure if he shared his settings 'boy'.

**Comment by kaden-tech** [comment]
I have the latest from telegram that download

**Comment by kaden-tech** [comment]
![image](https://user-images.githubusercontent.com/78925970/118872733-e4603100-b8b6-11eb-9faa-49ed80ba0cd7.png)
other than that I have sniperswitch enabled.

**Comment by siknite** [comment]
could you upload that screenshot again with all options expanded?

**Comment by IceHacks** [comment]
AutoChase would be the category this is under. Disable AutoChase to remove this effect.

**Comment by kaden-tech** [comment]
Im going to upload a screenshot

**Comment by kaden-tech** [comment]
![image](https://user-images.githubusercontent.com/78925970/119023261-9ce9ab80-b96f-11eb-82be-314b73a07ebe.png)
![image](https://user-images.githubusercontent.com/78925970/119023347-bdb20100-b96f-11eb-88d9-09cdc0be461f.png)

**Comment by siknite** [comment]
As @IceHacks suggested try turning off autochase see if that fixes your issue

**Comment by kaden-tech** [comment]
ok worked
