### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by xirokif** [IceHacks/SurvivCheatInjector#691]
bruh your logo is literally domino's pizza
![Screenshot_2021-05-18 Editor FreeLogoDesign](https://user-images.githubusercontent.com/65466024/118749466-29d31e80-b823-11eb-85f4-57027ede16e0.png)
![b5ad412ce9b54e3e960b88dfe6468a37](https://user-images.githubusercontent.com/65466024/118749468-2b9ce200-b823-11eb-888b-b6e6dc97b4ae.png)

**Comment by iBLiSSIN** [comment]
1 block not 3 block pls

**Comment by xirokif** [comment]
> 1 block not 3 block pls

Sure ill try :/

**Comment by xirokif** [comment]
> 1 block not 3 block pls
@iBLiSSIN I legit got the logo from a logo website but ill try to replicate it lol

**Comment by xirokif** [comment]
![ICEHACKS-LOGO](https://user-images.githubusercontent.com/65466024/118765427-acb6a200-b840-11eb-8f34-5939f809a2c5.JPG)
i used the "Bungee Layers Regular" font
![LogoMakr-6xUj3w](https://user-images.githubusercontent.com/65466024/118765522-cfe15180-b840-11eb-85fb-04d771c19085.jpg)
[Bungee-Layers-Regular-Regular.zip](https://github.com/IceHacks/SurvivCheatInjector/files/6506312/Bungee-Layers-Regular-Regular.zip)

**Comment by iBLiSSIN** [comment]
Nice

**Comment by xirokif** [comment]
> Nice

thx i hope icehacks will implement this logo soon

**Comment by IceHacks** [comment]
Are logos contain a sense of nostalgia, they have not changed the whole lifetime of this group. We are not looking to change them right now, but good work.
