### ISSUE TITLE
Free test sci 3.0.4

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#692]
Link download: https://mega.nz/file/SNpD0ShD#CgaKZ8jKCZBuaxgcZtsCmmOijoE793yakTN6ue9ao-I

How to use: https://youtu.be/lUNbu_eFcQY

Hope IceHacks will pin this isue until sci 3.0 is officially released.

**Comment by xirokif** [comment]
You don't know how much I've been wanting to have that. Thanks man!

**Comment by xirokif** [comment]
@iBLiSSIN Yo, the cheat doesn't work for me :(. It just shows a black screen.

**Comment by iBLiSSIN** [comment]
My computer can’t download this (trash computer)

**Comment by xirokif** [comment]
> My computer can’t download this (trash computer)

It can't???

**Comment by iBLiSSIN** [comment]
I think it need a lòng time to load

**Comment by xirokif** [comment]
ok

**Comment by JIAJIAPNXA** [comment]
Make this like extension,not application

**Comment by xirokif** [comment]
> Make this like extension,not application

I wish...

**Comment by russyboy** [comment]
does not work

**Comment by xirokif** [comment]
> does not work

How? Does it not launch? Is the screen black?

**Comment by russyboy** [comment]
no

**Comment by russyboy** [comment]
it worked

**Comment by russyboy** [comment]
just right click on the sci 3.0.2.exe and select "check compatibility", select the run with windows 8 , and it will fix the problem

**Comment by xirokif** [comment]
> just right click on the sci 3.0.2.exe and select "check compatibility", select the run with windows 8 , and it will fix the problem

I don't use windows. Are you talking about wine?

**Comment by russyboy** [comment]
> > just right click on the sci 3.0.2.exe and select "check compatibility", select the run with windows 8 , and it will fix the problem
> 
> I don't use windows. Are you talking about wine?

no i am using windows 10

**Comment by russyboy** [comment]
> > just right click on the sci 3.0.2.exe and select "check compatibility", select the run with windows 8 , and it will fix the problem
> 
> I don't use windows. Are you talking about wine?

sorry but i really cant help you

**Comment by xirokif** [comment]
> > > just right click on the sci 3.0.2.exe and select "check compatibility", select the run with windows 8 , and it will fix the problem
> > 
> > 
> > I don't use windows. Are you talking about wine?
> 
> sorry but i really cant help you

It's okay, I'm sure Ice will release a web or linux version soon.

**Comment by iBLiSSIN** [comment]
> > > > just right click on the sci 3.0.2.exe and select "check compatibility", select the run with windows 8 , and it will fix the problem
> > > 
> > > 
> > > I don't use windows. Are you talking about wine?
> > 
> > 
> > sorry but i really cant help you
> 
> It's okay, I'm sure Ice will release a web or linux version eventually.

Hey i use the window 7 and it is work very well. Check it in here: https://www.youtube.com/watch?v=deAziHkxU8I

**Comment by russyboy** [comment]
hey iBLiSSIN your youtube channel is really good

**Comment by russyboy** [comment]
hope you can get 1k subs soon

**Comment by russyboy** [comment]
i am rushing up too, lets work toghther

**Comment by xirokif** [comment]
> hey iBLiSSIN your youtube channel is really good

That's a fan account :/

**Comment by iBLiSSIN** [comment]
Why closed this issuel?
