### ISSUE TITLE
Create Linux/Mac Builds

### ISSUE THREAD

**Issue by lillabell** [IceHacks/SurvivCheatInjector#693]
**Describe the bug**
When I launch the application the screen is black. The weird thing is everything works like it isn't. I can still hear audio, the links work, and I can even go in game (but I'm blind of course). Also it always prompts me to update the program to version 3.0.4 even though it hasn't been released yet.

**Expected behavior**
I should be able to see the UI.

**Screenshots**
![black-screen](https://user-images.githubusercontent.com/65466024/118902006-57c76a00-b8da-11eb-8917-a0ab32e455b9.png)
![annoying-update-window](https://user-images.githubusercontent.com/65466024/118902093-86454500-b8da-11eb-9525-dbdf518ed26f.png)

**Cheat version**
3.0.2

**Comment by IceHacks** [comment]
What OS are you using. It looks like some type of linux. There is no linux app right now, I wouldn't trust wine.

**Comment by xirokif** [comment]
> What OS are you using? It looks like some type of linux. There is no linux app right now, I wouldn't trust wine.
> 
> 3.0.4 has been released. I just didn't post a message in the chat, because AutoUpdate.

I'm using Ubuntu 20.04. I hope you can make a linux application in the future! If not, then you could still try updating the chrome extension.

**Comment by russyboy** [comment]
I think ice hacks had forgotten the compatibility function of the cheat

**Comment by russyboy** [comment]
> What OS are you using? It looks like some type of linux. There is no linux app right now, I wouldn't trust wine.
> 
> 3.0.4 has been released. I just didn't post a message in the chat, because AutoUpdate.

yes i had updated 3.0.4 successfully

**Comment by xirokif** [comment]
> > 3.0.4 has been released. I just didn't post a message in the chat, because AutoUpdate.
> 
> yes i had updated 3.0.4 successfully
Good to know.

**Comment by xirokif** [comment]
@IceHacks I have both good and bad news. Good news is that I was able the cheat working by changing the windows version in wine to 10, the bad news is that there's no audio.

**Comment by iBLiSSIN** [comment]
> @IceHacks Tôi có cả tin tốt và tin xấu. Tin tốt là tôi đã có thể gian lận hoạt động bằng cách thay đổi phiên bản windows trong wine thành 10, tin xấu là không có âm thanh.

I not have Money to buy window 10

**Comment by xirokif** [comment]
> > @IceHacks Tôi có cả tin tốt và tin xấu. Tin tốt là tôi đã có thể gian lận hoạt động bằng cách thay đổi phiên bản windows trong wine thành 10, tin xấu là không có âm thanh.
> 
> I not have Money to buy window 10

I'm using linux so I have to use an application that runs executable files. I was able to change the windows version that wine (the application) used. Apparently Windows 8 isn't supported.

**Comment by russyboy** [comment]
gg

**Comment by IceHacks** [comment]
> I think ice hacks had forgotten the compatibility function of the cheat

I rarely forget anything. The reason this does not have good compatibility is because this is supposed to be a test release, not a production version. It isn't my fault that the file gets spread and people download it thinking it is "3.0" when, in reality, it is just a test file. I am fine with lots of people testing it, but they do need to understand that they are testing.

**Comment by xirokif** [comment]
> > I think ice hacks had forgotten the compatibility function of the cheat
> 
> I rarely forget anything. The reason this does not have good compatibility is because this is supposed to be a test release, not a production version. It isn't my fault that the file gets spread and people download it thinking it is "3.0" when, in reality, it is just a test file. I am fine with lots of people testing it, but they do need to understand that they are testing.

Not sure if you use Node.js. This might help: https://stackoverflow.com/questions/13388108/standalone-node-js-application

**Comment by humphreygaming** [comment]
What he said^
Won't close because this is (hopefully) an upcoming feature

**Comment by IceHacks** [comment]
Here you go:

https://gofile.io/d/tgH6Uw

Test Mac and Linux builds. Lemme know if they work or how they work.

**Comment by lillabell** [comment]
@Icehacks thank you!
