### ISSUE TITLE
aimbot is even more accurate with m79 & potato cannon 

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#694]
**Describe the feature you'd like**
Better aimbot for special weapons like m79, potato cannon. Should be predict more to the left and less to the right because of the way this weapon is held

**Describe alternatives you've considered**
Add in 3.0 

**Additional 
![1657D9C8-ADFB-4753-842E-BA65A17DA1B7](https://user-images.githubusercontent.com/77667370/119288911-c35f5d80-bc73-11eb-85e4-af53aadcc133.jpeg)
![5C60E258-599F-4619-AE27-9472CA38F209](https://user-images.githubusercontent.com/77667370/119288916-c5c1b780-bc73-11eb-96e5-2e308cc97106.jpeg)

**Comment by russyboy** [comment]
> **Describe the feature you'd like**
> Better aimbot for special weapons like m79, potato cannon. Should be predict more to the left and less to the right because of the way this weapon is held
> 
> **Describe alternatives you've considered**
> Add in 3.0
> 
> **Additional
> ![1657D9C8-ADFB-4753-842E-BA65A17DA1B7](https://user-images.githubusercontent.com/77667370/119288911-c35f5d80-bc73-11eb-85e4-af53aadcc133.jpeg)
> ![5C60E258-599F-4619-AE27-9472CA38F209](https://user-images.githubusercontent.com/77667370/119288916-c5c1b780-bc73-11eb-96e5-2e308cc97106.jpeg)

gud idea

**Comment by IceHacks** [comment]
Hmm, don't those guns fire explosives?

**Comment by IceHacks** [comment]
Then they don't need to be too accurate? But I will still take this into consideration, as dual weapons and other guns have a small offset.
