### ISSUE TITLE
Ability to disable AutoAttack

### ISSUE THREAD

**Issue by xirokif** [IceHacks/SurvivCheatInjector#696]
An enable and disable button for the AutoAttack ability.

**Comment by ImOsaym** [comment]
Yeah this would be good mainly because sometime you get trapped between a wall and another player and have to left click to be able to walk away

**Comment by xirokif** [comment]
> Yeah this would be good mainly because sometime you get trapped between a wall and another player and have to left click to be able to walk away

Yup exactly.

**Comment by humphreygaming** [comment]
#683
