### ISSUE TITLE
aimbot kinda bad

### ISSUE THREAD

**Issue by krunkerhackman** [IceHacks/SurvivCheatInjector#698]
aimbot kinda badaimbot kinda badaimbot kinda badaimbot kinda badaimbot kinda badaimbot kinda bad

**Comment by xirokif** [comment]
> aimbot kinda badaimbot kinda badaimbot kinda badaimbot kinda badaimbot kinda badaimbot kinda bad

It would be nice if you were more specific about your issue.

**Comment by iBLiSSIN** [comment]
Such guy

**Comment by krunkerhackman** [comment]
THE aim bot is bad
