### ISSUE TITLE
Players can Outrun/Dodge the AimBot

### ISSUE THREAD

**Issue by krunkerhackman** [IceHacks/SurvivCheatInjector#699]
The v3 AimBot is easy to dodge with certain guns.

**Comment by xirokif** [comment]
> please add better aimbot in V3 because the shots are ez to do age they just have to move around.

Fix your grammar and stop spamming the same issue please.

**Comment by IceHacks** [comment]
What weapon and what mode are you using when this happens?

**Comment by IceHacks** [comment]
You can try adjusting the multiplier in the AimBot settings. Thank you for your assistance testing the cheat by opening issues. Please remember, this is just a test version.
