### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by StabbyAlbert** [IceHacks/SurvivCheatInjector#7]
Still freezes, enough said

**Comment by StabbyAlbert** [comment]
when bump is turned off, its much bettr

**Comment by StabbyAlbert** [comment]
btw gimme dev to ur repo

**Comment by Natan1982** [comment]
@IceHacks Yeah, started freezing today. 
Btw, Surviv updated their .js, maybe its that.

**Comment by IceHacks** [comment]
I noticed that they updated it. I will check.

**Comment by IceHacks** [comment]
Although @StabbyAlbert "still freezes" is not what you should've said as I did fix it. So instead of "still freezes" try "started freezing again". Also, you don't need dev roles as you probably wouldn't contribute much my un-faithful admin.

**Comment by IceHacks** [comment]
@Natan1982 @StabbyAlbert pushing a fix for the freeze :)
