### ISSUE TITLE
Free test SCI 3.0.0 (not require 64 bit - I tested)

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#700]
Link download: https://mega.nz/file/WuABRCaS#T2-_W1kVPjqB62rwl6ni7RN8AeVtKkU4nSJqqv0RtdI

How to install in [telegram of IceHacks](https://t.me/ice_updates)

**Comment by IceHacks** [comment]
I don't know how it is possible for a 64-bit app to not require a 64-bit computer.

**Comment by iBLiSSIN** [comment]
> I don't know how it is possible for a 64-bit app to not require a 64-bit computer.

I successful
