### ISSUE TITLE
AimOnClick doesn't work well; Zoom is not working

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#701]
**Describe the feature you'd like**
* Hmm, the aimbot new is nice but collision detection is always enable so i cant shoot enemy through the window. And aimonclick is not aimbot in first shoot, very hard to use a shot gun or sniper.
* Hack zoom with scroll wheel not work so pls fix it.

**Describe alternatives you've considered**
Make aimonclick better (have in project but not work) ,sure to can disable collision detection and fix hack zoom.

**Comment by russyboy** [comment]
agree

**Comment by IceHacks** [comment]
I don't use the AimOnClick. I thought I had fixed it, but if that is not the case, I will look at it again. As for zoom, it should work. Make sure to hold shift when scrolling.

**Comment by IWasAPerson-1123** [comment]
I haven't seen the zoom feature yet. I wonder if its because I'm pressing the wrong buttons or because it was used in an earlier version.

**Comment by iBLiSSIN** [comment]
> I haven't seen the zoom feature yet. I wonder if its because I'm pressing the wrong buttons or because it was used in an earlier version.
Press shift key then use scroll wheel to zoom.

**Comment by humphreygaming** [comment]
Shift zoom works, AimOnClick works
