### ISSUE TITLE
more ez test

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#704]
This is not a issues
I want have a sci 3.0 test as a extension not a exe file (my computer alway get error with it).
Hope you make it soon!

**Comment by iBLiSSIN** [comment]
> This is not a issues
> I want have a sci 3.0 test as a extension not a exe file (because my computer alway get error with it).
> Hope you make it soon!

**Comment by russyboy** [comment]
> This is not a issues
> I want have a sci 3.0 test as a extension not a exe file (my computer alway get error with it).
> Hope you make it soon!

oof

**Comment by krunkerhackman** [comment]
Yes i need the extension version too (bad computer)

**Comment by IceHacks** [comment]
Exe should run smoother than any extension.

**Comment by IceHacks** [comment]
> This is not a issues
> I want have a sci 3.0 test as a extension not a exe file (my computer alway get error with it).
> Hope you make it soon!

What is the error?

**Comment by JIAJIAPNXA** [comment]
just... exe file works like on chrome and some players gets this game laggy too much so aimbot going crazy but this works on yandex browser correctly
