### ISSUE TITLE
making the big map a little bit transparent or enabling attack when opening big map

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#705]
anyone experienced this react:

when opening the big map by pressing "G" key, you may be blocked and somewhere a enemy jumps out, but the map blocked your view so it will make you unready to fight back.

so if the auto Attack mode still be enabled when opening big map ,or making the big map more transparent will help a lot.

hope you can accept my idea

thanks

PS: i am not forcing, IceHacks has the last decide

**Comment by FreezeFlameKill** [comment]
Just click "G" again. Not an issue. 

Anyone with basic surviv.io knowledge should know that this is not an issue. You shouldn't be looking at the map when moving, and only look at it for a few seconds to see where to go.

**Comment by iBLiSSIN** [comment]
should learn some basic skills in surviv.io (i can dogle 56% of bullet with aimbot)

**Comment by russyboy** [comment]
ok sorry guys my bad
