### ISSUE TITLE
Can't shoot auto weapons or throw any type of grenade

### ISSUE THREAD

**Issue by IWasAPerson-1123** [IceHacks/SurvivCheatInjector#706]
**Bug**
When I have an auto weapon (weapons like MP5, MAC-10, AK-47, FAMAS, or M93R), it does nothing when I left click. On other weapons like snipers (Mosin-Nagant, AWM-S, SV-98) or shotguns (like M870, MP220, or M1100), I can fire it normally.

**Settings**
The current settings I have right now are:

_Type: autoaim
Use Collisions: False
Aim with mouse: true
AutoAttack: true
AutoShoot: true
Aim at Downed: false
Aim at Objects: false
MobileMovement: false
LegitMode: false
AimFOV: 0
AutoLoot/Doors: true
AutoHeal: false
AutoReload: false
AutoSwitch: true
  Mode: SniperSwitch
  Ignore Auto Weapons: false
  Equip Melee: true
  Min. Fire Delay: 1
Binds
  Aimbot: ShiftLeft (toggle)
  Spinbot: Space (toggle)
  AutoSwitch: ShiftRight (toggle)
  AutoHeal: KeyX (toggle)
Bumpfire: true
Dark Theme: true
ESP: true
  Flashlight: true
  Blast Radius: true
  Tracer Width: 1
Grenade Timer: true
Pan Hero: true
  Bullet Detection Radius: 16
  Display Detection Radius: false
  "Reflect" bullets w/o pan : true
  Loot pan auto: false
Spinbot: true
  Spin Angle: 116
Transparency
  Obstacles: 0.3
  Roofs: 0_

I'm asking about this because I had the hacks before, but I had to uninstall it. The bug didn't happen before, and it is the same version. Now that I've reinstalled it, I can't remember my past settings but its still the same version, and the bug happens now. If you can please tell me which setting is affecting it or fix the bug it would be very much appreciated.

**Comment by IceHacks** [comment]
This is 2.1.7, we no longer support this version.
