### ISSUE TITLE
add keybind for auto throw grenade

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#708]
**Describe the feature you'd like**
keybind for throwing a grenade in just one click

**Describe alternatives you've considered**
like pressing "m" key, auto throwing the grenade out

**Additional context**
i think it is a good idea?

And infinite grenades are fun tho

**Comment by IceHacks** [comment]
Grenades need to "bake" to be used effectively, but other than that this might be fun

**Comment by russyboy** [comment]
gud

**Comment by humphreygaming** [comment]
#683
