### ISSUE TITLE
make a cheat as an extension

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#709]
the cheat 3.0 application based at chrome but... for some players (like me) on chrome this game laggy. so i want it to use in yandex browser(there it works correctly for me). and there and also the weapon icons look a little different. https://imgur.com/a/q7gzcxj
and the plane has a yellow outline (I'm too lazy to chase planes to make a screenshot)

**Comment by russyboy** [comment]
yes making as an extention is better for low-end PCs, we play surviv is because of our bad PC

**Comment by iBLiSSIN** [comment]
IceHacks will close this issues soon. Because i have open a issues like this.

**Comment by JIAJIAPNXA** [comment]
my computer isn't bad (but i want to update it) maybe it because windows 7

**Comment by JIAJIAPNXA** [comment]
in this issue i just said what's problem with application and why extension is better

**Comment by IceHacks** [comment]
Yandex Browser uses Chromium as a base, as does this project. As for the plane having a yellow outline, I have not experienced this. If you experience graphical issues make sure you have updated graphics drivers. Also, if you are on an older version of windows, try changing the compatibility settings. There are no plans to <ins>port</ins> this into an extension.

**Comment by JIAJIAPNXA** [comment]
but my game dont working on chrome but working on yandex
sadly i cant make a vidio when i use 3.0 and yandex browser
