### ISSUE TITLE
Full cheat menu not showing

### ISSUE THREAD

**Issue by BobTheFish1238** [IceHacks/SurvivCheatInjector#71]
When I open the cheat menu it only shows "Edit Binds" and "Reset Settings"

It used to show the full cheat menu and stuff

![Screenshot 2019-09-14 at 2 01 53 PM](https://user-images.githubusercontent.com/52727742/64913635-c19c7300-d6f8-11e9-93ac-14c02bc0e3f0.png)

**Version**
1.0.4

**Comment by IceHacks** [comment]
@BobTheFish1238 Update your cheat. The current version is 1.1.5
