### ISSUE TITLE
battle pass + whole season unlocked( will it work?)

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#711]
**Describe the feature you'd like**
whole season unlocked

**Describe alternatives you've considered**
all levels unlocked by default

**Additional context**
will it work? lol

**Comment by iBLiSSIN** [comment]
Never can do

**Comment by xirokif** [comment]
> Never can do

How?

**Comment by iBLiSSIN** [comment]
> > Never can do
> 
> How?

can't is can’t don’t ask to anymore.

**Comment by FreezeFlameKill** [comment]
Impossible. Close this thread.

**Comment by russyboy** [comment]
oof just imagine
