### ISSUE TITLE
Smooth Aimbot Would Be Nice

### ISSUE THREAD

**Issue by NotAtic** [IceHacks/SurvivCheatInjector#712]
**Describe the feature you'd like**
The feature i would like is a smooth aimbot, one that doesn't lock on and it looks legit, and doesnt mostly track players, like a smooth or legit aimbot

*

**Comment by iBLiSSIN** [comment]
Lol

**Comment by NotAtic** [comment]
Lmfao?

**Comment by IceHacks** [comment]
Use the aim fov thing
