### ISSUE TITLE
Ban Bypass

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#713]
can you make ban bypass? ban is dialog window where have button what makes you to out from accout. so i think if you disable this dialog window this will bypass ban?

**Comment by FreezeFlameKill** [comment]
https://github.com/IceHacks/SurvivCheatInjector/issues/687 

Impossible.

**Comment by JIAJIAPNXA** [comment]
maybe yes maybe no

**Comment by JIAJIAPNXA** [comment]
in 687 issue no one said its impossible
