### ISSUE TITLE
just a little tool

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#714]
**Describe the feature you'd like**
show the fps of the game

**Describe alternatives you've considered**
can choose where to put; what color; what size of the font; 

**Additional context**
hope you guys won't say it is unreachable, trust me I am not bad people

**Comment by NotAtic** [comment]
Possible

**Comment by FreezeFlameKill** [comment]
Yeah it is def possible I have used in in another mod before.

**Comment by iBLiSSIN** [comment]
> FrezeFlameKill

You have ask me what is my discord 

It ‘s here: https://discord.com/invite/zrtxKHS7

**Comment by IceHacks** [comment]
possible, but not urgent for the test
