### ISSUE TITLE
melee range? lol

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#715]
**Describe the feature you'd like**
like other weapons' flashlight, could melee add flashlight to it?

**Describe alternatives you've considered**
just a melee flashlight is ok

**Additional context**
hope icehacks can do it( I don't know if they knew how to)

**Comment by iBLiSSIN** [comment]
Did have one issues like this

**Comment by russyboy** [comment]
but Humphrey gaming said he dont know how to code

**Comment by russyboy** [comment]
#623

**Comment by russyboy** [comment]
in this new update i hope he will make changes on this

**Comment by IceHacks** [comment]
I am aware of this.
