### ISSUE TITLE
Fix some few.

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#716]
**Describe the bug**
* Till i disable autoshoot, it just enable.
* Auto disable spinbot is not well, because it not disable in my first shoot.
* AutoChase is follow nearest enemy but not aimbot at they. Some time it aim at other player.

**Expected behavior**
Pls fix it.

**Screenshots**
Not have.

**Cheat version**
3.0.4

**Chromium version**
exe

**Comment by IceHacks** [comment]
All these have been reported previously.
