### ISSUE TITLE
How do you open it...

### ISSUE THREAD

**Issue by The-Owner-is-epic** [IceHacks/SurvivCheatInjector#722]
### **Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**

**Chromium version**

**Comment by FreezeFlameKill** [comment]
1. Install the cheat file.
2. Go to chrome extensions and drag the file into the extensions.
3. Go to surviv.io

If you did this correctly, instead of the SURVIV.IO banner on the top of the screen, you should see ICEHACKS banner.

Press escape to open cheat menu.

Your welcome!
