### ISSUE TITLE
Aimbot not working

### ISSUE THREAD

**Issue by paulo27ms** [IceHacks/SurvivCheatInjector#723]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**

**Chromium version**

**Comment by FreezeFlameKill** [comment]
Will you be more specific?

**Comment by iBLiSSIN** [comment]
;)

**Comment by IceHacks** [comment]
Is there a real problem here? Can someone confirm?

**Comment by JIAJIAPNXA** [comment]
maybe...ME, aimbot broken for some players who playing on chrome with this cheat.surviv io just laggy and have some features. this glitch happening on cheat app too.

**Comment by iBLiSSIN** [comment]
> Is there a real problem here? Can someone confirm?

No complete the cheat but error is happened so soon

**Comment by iBLiSSIN** [comment]
But i see the aimbot is working in 3.0

**Comment by iBLiSSIN** [comment]
https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/3.0.0

**Comment by humphreygaming** [comment]
No specifications provided, closed
