### ISSUE TITLE
Heads Up!

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#726]
All suggestions posted in the issues tab will be redirected to V3, as V2 will no longer receive any further updates and consequently you will not see them for the time being.

Remember, if you have V3 installed thinking it's an actual product / release, _you are mistaken_. V3, at its current stage, is not a final version nor an actual IceHacksGP completed product. It is in its testing phase, with testing features, with testing bugs, and will be treated as such. Please do not complain over incompatibility with 32bit systems, if V3 is available as an extension, if V3 runs on Linux / Mac, etc. These are features that **will be added**, just not for the time being. Knowing that downloading a test product might yield unexpected results should be common knowledge by now.

Are you weird? Do you want to continue V2 at your own pace? We won't judge (ironic). [Here](https://github.com/humphreygaming/surviv-cheat-source) is the little known source code for V2 in all its glory. Bet you didn't know V2 was open source, eh? Now you can write, compile it, and use it (hopefully not stealing the credits in the process)

Just brought to my attention, we are [popular!](https://survivio.fandom.com/wiki/User_blog:JABUSER321/About_IceHacks) It seems wannabe phycologists are studying our behavior for some odd reason but publicity is nice I guess.

Now, in an act of desperate shilling, do you want us to _not be silent_ like they said? Join the [telegram group](https://t.me/ice_updates). If that is too sketchy, join the [Discord hangout server](https://discord.gg/MCtzrWW7BA). It might not be specifically for IceHacks related things, but ask and you shall receive. And if you felt offended for the past experiences of this server, we are sorry. The new rules prevent banning, excessive racism, excessive homophobia, etc. This isn't a guarantee with Albert and Fin in the server **but we can try**.

Thanks

**Comment by iBLiSSIN** [comment]
Yea i get a error but i feed very good because this eror help me acess pretiges island :) (v3.0.0)

**Comment by IceHacks** [comment]
> Yea i get a error but i feed very good because this eror help me acess pretiges island :) (v3.0.0)

What error?

**Comment by IceHacks** [comment]
> Just brought to my attention, we are [popular!](https://survivio.fandom.com/wiki/User_blog:JABUSER321/About_IceHacks) 

What NSFW link?

**Comment by Onacona-BG** [comment]
Why does the link always expire? :(
