### ISSUE TITLE
Surviv Cheat Injector Dead

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#727]
**Describe the bug**
Cheat not load.

**Expected behavior**
Please fix and don't close this problem till you can fix it.

**Cheat version**
3.0.0

**Chromium version**
Not Found

**Screenshots**
![bandicam 2021-07-12 10-12-11-176](https://user-images.githubusercontent.com/77667370/125225718-f203c700-e2f9-11eb-8384-ebacca6392e2.jpg)

**Comment by humphreygaming** [comment]
I said **very clearly** to not post issues regarding V3. Pay attention next time

**Comment by iBLiSSIN** [comment]
> I said **very clearly** to not post issues regarding V3. Pay attention next time

Ok, sorry
