### ISSUE TITLE
v. 2.1.7: Can't throw grenade, can't shoot through objects

### ISSUE THREAD

**Issue by Lavasplash** [IceHacks/SurvivCheatInjector#729]
Hello there,

I cannot use throwables even when I click on the square. Also, I cannot shoot through objects (during battle). I was able to do these things before I cleared cache on my browser. Is there a setting I should tweak? Thanks.

**Comment by iBLiSSIN** [comment]
U noob if you can ‘t do it

**Comment by iBLiSSIN** [comment]
Close because no any support for v2.0
