### ISSUE TITLE
How to activate hack after unpacking as extension?

### ISSUE THREAD

**Issue by fahrennheit** [IceHacks/SurvivCheatInjector#73]
I downloaded latest.zip and unpacked, then added to chrome as an extension. Hack logo popped up on extension bar, however when I played on surviv2.io nothing happened. How do you activate this hack?

**Comment by fahrennheit** [comment]
P/s: my school blocked surviv.io so I have to use the proxy site. I think this is where the problem is. Can people confirm?

**Comment by potatotomato7** [comment]
u have to go open the manifest file and add surviv2.io to the list of sites then save and add to chrome again

**Comment by IceHacks** [comment]
@fahrennheit Which proxy?

**Comment by fahrennheit** [comment]
editing manifest file works perfect, thanks a lot!

**Comment by IceHacks** [comment]
Glad it works!
