### ISSUE TITLE
Will this feature is important (not a issues, a question by me)

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#731]
https://github.com/IceHacks/SurvivCheatInjector/projects/5#card-55555342

 I don’t think this feature is useful when I have it. If I was you, I would remove this feature

**Comment by iBLiSSIN** [comment]
Why we need suicide?

**Comment by IceHacks** [comment]
What it would do is: pull the pin of a grenade right when you are about to die, to kill the attacker

**Comment by iBLiSSIN** [comment]
> What it would do is: pull the pin of a grenade right when you are about to die, to kill the attacker

when I are about to die, I still can kill they. Or if you add it, pls sure to can disable it. So now I will closed this issues when you view this comment

**Comment by iBLiSSIN** [comment]
Closed

**Comment by iBLiSSIN** [comment]
Closed
