### ISSUE TITLE
Surviv.io Doesn't Load

### ISSUE THREAD

**Issue by KOOOOGASA** [IceHacks/SurvivCheatInjector#733]
**Describe the bug**
Surviv.io will be stuck loading when this extension is enabled.

**Expected behavior**
The game should load and allow you to interact with the menu screen.

**Cheat version**
2.1.7

**Chromium version**
92.0.4515.159

**Comment by iBLiSSIN** [comment]
No more support for v2, and you should disable other extensions and script to game can load
