### ISSUE TITLE
Chrome web store

### ISSUE THREAD

**Issue by xXShadowXxGaming** [IceHacks/SurvivCheatInjector#734]
Can you re-add the icehacks to Chrome web store please? It got taken off. Please fix this.

**Comment by iBLiSSIN** [comment]
May no because it need money

**Comment by humphreygaming** [comment]
Are you willing to pay the $5.00 fee for registration to the Chrome Web Store?

**Comment by iBLiSSIN** [comment]
> Are you willing to pay the $5.00 fee for registration to the Chrome Web Store?

Not need to do because it free if follow your tutorial

**Comment by IceHacks** [comment]
Last time it was free because it was unlisted. But why host an extension that isn't being worked on. Also, Google banned the last one because it violates some policy.
