### ISSUE TITLE
Speacial items on map.

### ISSUE THREAD

**Issue by Longchauuuisme** [IceHacks/SurvivCheatInjector#735]
Note: I'm using SCI.exe
I once used IceHacks as a google chorme extension and I found that Black-eye block and Mosin-nagant tree are highlighted with white and pink color on map. I really love it but now I don't find it anymore:(
Some small issues:
Attack knocked players shoud be optional, I can't get rid of confirming kills with melee weapons while his teamates start shooting at me:(
Auto-breaking the bullet package is noisy, espeacially combating in the storage when I stand next to the package and I cannot equip guns.
Hope that Icehacks neva die!
P/s: I cannot use team ping menu on SCI 3.0.5:)

**Comment by iBLiSSIN** [comment]
Lmao, the map is not important (with IceHacks) also 3.0 is testing version, Humphrey Gaming said don’t open anh issues about v3 :(( . And auto breaking fix is in the progress, don’t worry about this. You can’t use the ping, I think this is a problem with auto emote (in 3.0 project) . With the melee lock, it is not good, you should disable it; IceHacks will do it soon!
