### ISSUE TITLE
Cheat isnt working against other cheater=)

### ISSUE THREAD

**Issue by pilgrimoflight** [IceHacks/SurvivCheatInjector#74]
**Describe the bug**
 I meet other player, that is totally using hack ( not sure if this one really) and aim and other stuff simply not working on him. So we did that old way shooting. Just want to point that situation for you. Its not a big problem, more fun though,

 **Screenshots**
I wasnt ready to   screenshot, also that player with cheat has like some transparent bubble around him as i see it. So you can clearly knew its cheater and our tricks wont work at him till you get close and cheat stop working,
 
Any idea? Who has the same?

**Comment by IceHacks** [comment]
@pilgrimoflight This "bug" was a feature. It doesn't exist in the latest cheat though,
