### ISSUE TITLE
Chrome (v92.0.4515.131) slow load

### ISSUE THREAD

**Issue by flancast90** [IceHacks/SurvivCheatInjector#740]
**Describe the bug**
On my chrome version (v92.0.4515.131), I experience extremely slow (5+ minutes) loading time for surviv.io. Looking into your code, it seems as if you are using a synchronous request, which blocks all processes until finally completed. (I can't get much more than this because of heavy obsfuscation). 

Everything works great after the wait, but still I feel like this could be fixed rather easily (perhaps async/await as opposed to sync call) 

**Expected behavior**
Quicker Loading

**Cheat version**
Latest

**Chromium version**
92.0.4515.131

**Comment by lillabell** [comment]
wats this i see? a proffesionall/????

**Comment by lillabell** [comment]
@flancast90 Unfortunately, they don't wanna be bothered with the web extension anymore. You gotta use the Windows client now.

**Comment by flancast90** [comment]
:(. I use Linux. If they don't work on the web client anymore, maybe I'll reach out to them about allowing me to create/continue work on a clone of the extension. The license on it does not permit that as of right now, and I don't want to be sued.

**Comment by ViridianMoon** [comment]
@lillabell  how do i use/get the windows client? is it just the steam version? sorry, i am new to github :P

**Comment by flancast90** [comment]
> @flancast90 Unfortunately, they don't wanna be bothered with the web extension anymore. You gotta use the Windows client now.

Update: I just emailed them about me continuing work on web client under their terms. Waiting to hear back from them now :crossed_fingers:

**Comment by humphreygaming** [comment]
(Just to clear up any misconceptions) No, IceHacks is **not** abandoning the web client / extension release method. The Windows client is just a test, not a full release; It does not represent the final product. Yes, versions regarding 2.1.7 and below are to remain officially featureless and as legacy versions with no guarantee of fixing if it ever goes broke. 

Now, if you want to continue under a "Community Release", which seems what you intend to do @flancast90, you may do so using the source code (https://github.com/humphreygaming/surviv-cheat-source) and then sending the zip file for review under one of the issues, forks, etc., once done. You may also do it privately if you want, your choice.

**Comment by lillabell** [comment]
@humphreygaming sorry :p

**Comment by lillabell** [comment]
@ViridianMoon you have to go to their telegram to get the windows client.

**Comment by flancast90** [comment]
> (Just to clear up any misconceptions) No, IceHacks is **not** abandoning the web client / extension release method. The Windows client is just a test, not a full release; It does not represent the final product. Yes, versions regarding 2.1.7 and below are to remain officially featureless and as legacy versions with no guarantee of fixing if it ever goes broke.
> 
> Now, if you want to continue under a "Community Release", which seems what you intend to do @flancast90, you may do so using the source code (https://github.com/humphreygaming/surviv-cheat-source) and then sending the zip file for review under one of the issues, forks, etc., once done. You may also do it privately if you want, your choice.

Awesome! Think I found the error in the code. Testing then-request package instead of sync-request. Per sync-request docs:
> You should not be using this in a production application. In a node.js application you will find that you are completely unable to
> scale your server. In a client application you will find that sync-request causes the app to hang/freeze. Synchronous web 
> requests are the number one cause of browser crashes. For production apps, you should use then-request, which is exactly
> the same except that it is asynchronous.

**Comment by lillabell** [comment]
bruh i wish i knew how to code

**Comment by humphreygaming** [comment]
I'm assuming either IceHacks or Vinny were in a hurry when they did this or it was the easiest way of doing it, I'm not sure. Interesting find though, would explain the 15+ seconds load time.

**Comment by flancast90** [comment]
Well, even the normal source won't compile in Chrome. Says ```required is not defined```

**Comment by humphreygaming** [comment]
Nice. Issue Resolved.

**Comment by iBLiSSIN** [comment]
> Well, even the normal source won't compile in Chrome. Says `required is not defined`
> 
> EDIT: re-downloading and trying webpack and npm i
> 
> EDIT 2: Works as expected (changed a bit for linux)

Give me the zip file pls :((

**Comment by flancast90** [comment]
Sure! My PR and changes are now part of the main repo. Just go to
Archive/2021-SEP-30.zip and download, and you can use that as the extension
as normal.

To build it yourself, you can navigate to the leaked source files of the
repo (Humphreygaming/surviv-cheat-source)

Unzip the folder, cd into it, and then do

npm i

, and then finally do

npx webpack

Then, you can use the out folder as the load unpacked as the extension.


Sorry for the bad formatting btw, I’m on mobile right now :)

**Comment by iBLiSSIN** [comment]
Hmm, it is old version, can it work?

**Comment by flancast90** [comment]
What is an old version? My update? It’s the latest I found from the leaked
code.

**Comment by lillabell** [comment]
> Sure! My PR and changes are now part of the main repo. Just go to Archive/2021-SEP-30.zip and download, and you can use that as the extension as normal. To build it yourself, you can navigate to the leaked source files of the repo (Humphreygaming/surviv-cheat-source) Unzip the folder, cd into it, and then do
> npm i
> , and then finally do
> npx webpack
> Then, you can use the out folder as the load unpacked as the extension. Sorry for the bad formatting btw, I’m on mobile right now, and the code blocks won’t render grin

@flancast90 Thank you! (even though i have no idea what im even gonna do with it)

**Comment by flancast90** [comment]
Sure, no problem! Feel free to ask me anything you’re confused about still!
