### ISSUE TITLE
Make source code open source

### ISSUE THREAD

**Issue by martinGITHUBER** [IceHacks/SurvivCheatInjector#743]
Perhaps make the source code of this plugin/extension open source? I think this would:
1. Make this used by more people because people will start contributing, and when software is made by a team, its always better
2. Many people(Including me) are just kinda interested how this works. I am a programmer, and I'm really interested in hacking/understanding how games work, and I also really am curious how this plugin works
3. This will also *probably* make the project more active, and also I bet some other geniuses will add their own cool features

Also, I do realize that technically the source code is in the .zip files... but like what kind of open source project stores their code in a list of zip files ON github?

**Comment by lillabell** [comment]
@martinGITHUBER, it already is: https://github.com/humphreygaming/surviv-cheat-source/issues.
They just need to publicize it more.

**Comment by IceHacks** [comment]
Yeah, Humphrey released it on GitHub. The zip files in the archive are just there for historical value. The reason we used zips instead of just releasing the source is that surviv was actually actively trying to block the cheat back then.
