### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by SeekNDstroy565** [IceHacks/SurvivCheatInjector#75]
the game is lagging a bit. auto-aim does not work when it is lagging

fix it

**Comment by IceHacks** [comment]
lmao. I can not fix your internet.

**Comment by SeekNDstroy565** [comment]
it's not like that while I am playing it is freezing like a second then it continues

**Comment by IceHacks** [comment]
Disable auto everything features. The cheat shouldn't be doing that.
