### ISSUE TITLE
create autoscope 

### ISSUE THREAD

**Issue by TylerWhat** [IceHacks/SurvivCheatInjector#752]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TylerWhat** [comment]
System will help you turn the scope, depend where the enemy was

**Comment by humphreygaming** [comment]
I'm assuming this is something like variable scope changing?

**Comment by iBLiSSIN** [comment]
Not important

**Comment by IceHacks** [comment]
Zooming in just enough to see enemy?

**Comment by AsiaGuy** [comment]
auto scope mean it will auto zoom enough to see the enemy, right?
and it will zoom back if the enemy is too close :/
