### ISSUE TITLE
flashlight bug

### ISSUE THREAD

**Issue by criticalguy24234** [IceHacks/SurvivCheatInjector#753]
**Describe the bug**
so i played and my flashlight got broke

**Expected behavior**
i thinked flashlight is going to be there forever

**Screenshots**

**Cheat version**
(v3.0.6) 

**Chromium version**

**Comment by criticalguy24234** [comment]
![skribbl io-ss](https://user-images.githubusercontent.com/91802231/135745110-0cbad6fb-012e-4036-8ac1-957eefbb217e.jpg)

**Comment by iBLiSSIN** [comment]
It is only work in the first game when u run the Surviv Cheat , then it broken

**Comment by IceHacks** [comment]
Hey, thanks for the tip. I hadn't tested it through multiple games. Will work on a fix asap.

**Comment by IceHacks** [comment]
Fixed, it will be working in 3.0.7
