### ISSUE TITLE
Turn it into a script for tampermonkey

### ISSUE THREAD

**Issue by dotshoo** [IceHacks/SurvivCheatInjector#760]
Turn it into a script for tampermonkey my laptop does not allow it to work as an extension I was wondering if you could put it in tampermonkey And then users across the world could use the hack It would make your hack easier to use And if you do do that you can also make it so auto updates I could say a million features Please make it work for tampermonkey.

**Comment by AsiaGuy** [comment]
no, this work for only a client. If you make it for extension, it may cause lag and you will be banned. Close this issue because it's not possible to do >:(
