### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by CYPH3R-7** [IceHacks/SurvivCheatInjector#763]
I am ICEHACKSISBACK after The original ICEHACKS left surviv. I then changed to HACKER[AINT]LEAVIN. Can you update the chrome hack extension? Also possibly fix the loading problem. When I load the page the survive guy houses and buildings are missing.

**Comment by iBLiSSIN** [comment]
It fixed, just download from here: https://github.com/IceHacks/SurvivCheatInjector/raw/master/archive/2021-SEP-30.zip

**Comment by humphreygaming** [comment]
#754
