### ISSUE TITLE
i find a problem for 3.0, if your enemies are chasing you, you cannot switch your weapon. Also, when i fire the gun, the weapon is keep changing by itself, it is quite annoying

### ISSUE THREAD

**Issue by TylerWhat** [IceHacks/SurvivCheatInjector#765]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**

**Chromium version**

**Comment by humphreygaming** [comment]
Have you tried turning off the AutoSwitch tree?

**Comment by IceHacks** [comment]
Simply disable AutoSwitch.

**Comment by TylerWhat** [comment]
Thanks

My problem, sorry

**Comment by TylerWhat** [comment]
when can i disable the autoswitch?
