### ISSUE TITLE
can u remove the annoying popups

### ISSUE THREAD

**Issue by humphreygaming** [IceHacks/SurvivCheatInjector#766]
can u remove the annoying popups
![image](https://user-images.githubusercontent.com/91803184/135753020-356bb458-b399-40b3-8b0e-4ab3c6b4acd5.png)

_Originally posted by @Person441 in https://github.com/IceHacks/SurvivCheatInjector/discussions/746#discussioncomment-1420735_

**Comment by humphreygaming** [comment]
Will be fixed soon, look for it in "archives"

**Comment by iBLiSSIN** [comment]
fix this is ez :))
just find the "https://github.com/IceHacks/SurvivCheatInjector....." and delete this link, completed

**Comment by humphreygaming** [comment]
Finished, under archives
