### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ItzHectic** [IceHacks/SurvivCheatInjector#77]
**Describe the bug**
~\Downloads\h1Z1\gay
Error
Manifest file is missing or unreadable
Could not load manifest.

**Expected behavior**

**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by IceHacks** [comment]
https://github.com/IceHacks/SurvivCheatInjector#installation "If you get any errors while installing make sure to have the right folder selected."
