### ISSUE TITLE
Some small improve for auto chase 

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#771]
* If the move keys are pressing (arrows keys, WASD keys) auto chase won’t enable. (This thing should be in the keybind)
* auto chase still follow the enemy when u are downed;-;.

**Comment by TylerWhat** [comment]
what is auto chase

**Comment by iBLiSSIN** [comment]
> There should be an option to disable aim at downed players. I think autoattack disables when you press right click. I personally like the keep pressing wasd while it is working.


yea maybe press right mouse is can but I interact with right mouse. And disable auto chase is should be can enable or disable (follow the user)

**Comment by iBLiSSIN** [comment]
And don’t follow more if the distance is smaller than 3, continues follow if distance more than 4

**Comment by IceHacks** [comment]
I think there is a distance slider for this setting

**Comment by iBLiSSIN** [comment]
> A minimum distance interests me

But it better for naginata

**Comment by sealvessel** [comment]
I want to stop attacking downed players, in team games I keep dying because I melee locked onto a dead player.
