### ISSUE TITLE
Grenade Dodge corners you.

### ISSUE THREAD

**Issue by kaden-tech** [IceHacks/SurvivCheatInjector#772]
**Describe the bug**
If you are in a corner and someone throws a mine or gas bomb you get trapped in the corner and can't move. Also if someone below or above you throws something it shows it and wont let you near thats spot even if it is not on your level.

**Expected behavior**
This should allow you to walk near not on mines when you are cornered and it should let you walk through grenades that are not on your level.

**Cheat version**
Latest version

This is for the app.

**Comment by IceHacks** [comment]
I will add a keybind for this when I make the keybind system
