### ISSUE TITLE
Doesn't want to use grenade launcher.

### ISSUE THREAD

**Issue by NopeProsOnly** [IceHacks/SurvivCheatInjector#773]
Version is the latest one on the app

**Comment by humphreygaming** [comment]
Yes, I'm pretty sure this was also an issue with V2, or at the very least was very buggy.

**Comment by IceHacks** [comment]
It's because Surviv doesn't treat this item the same as it does a gun. It's fixable, but I don't typically find one in a game so I wouldn't be able to test.

**Comment by kaden-tech** [comment]
Well, you could just make sure its ready for when you do get the chance to play. Last time I used a Grenade Launcher I died because the game kept switching the gun to a mp3

**Comment by lillabell** [comment]
It also doesn't want to use the potato cannon. Basically cannons and the like don't work.
