### ISSUE TITLE
Twitch.tv [FEATURE] Add extension to work on twitch (popout)

### ISSUE THREAD

**Issue by SinnedGaxses** [IceHacks/SurvivCheatInjector#78]
I was wondering if you could make the hack work on  twitch game extensions? 
Specifically links like this, if you'd like to talk about it more, I've already added you. Exentric#1337
Thanks.
Twitch Link Example: https://www.twitch.tv/popout/not_mercu/extensions/c79geyxwmp1zpas3qxbddzrtytffta/panel

**Comment by zbot473** [comment]
It runs on a lower version, and unless you can maintain that other branch, it probably won't happen.

**Comment by SinnedGaxses** [comment]
zbot, so it's been done? if so could you send me the file/release for it?

**Comment by IceHacks** [comment]
[survivio-plus-d22966b0c23fd386dec5b4e87e307454e10fbbac.zip](https://github.com/IceHacks/SurvivCheatInjector/files/3639144/survivio-plus-d22966b0c23fd386dec5b4e87e307454e10fbbac.zip)

@SinnedGaxses IceHacks is no longer compatible with that version of surviv, but this modified older cheat is.

**Comment by leoorantes08** [comment]
it doesn't have aimbot

**Comment by IceHacks** [comment]
@leoorantes08 use this https://c79geyxwmp1zpas3qxbddzrtytffta.ext-twitch.tv/c79geyxwmp1zpas3qxbddzrtytffta/1.0.2/ce940530af57d2615ac39c266fe9679d/index_twitch.html
