### ISSUE TITLE
Change the color of the map 

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#780]
**Describe the feature you'd like**
Change the color of the map 
**Describe alternatives you've considered**
This is the third time I open this isue, hope it not get close :D

**Additional context** (the code to add to background.js)
                {
                name: "Grass fix", //Makes grass a darker green, easier on eyes.
                from: /,grass:([0-9]*),/g,
                to: ',grass:5606656,'
                },

**Comment by humphreygaming** [comment]
I don't see this benefiting the majority
