### ISSUE TITLE
Improve the bullet dodge

### ISSUE THREAD

**Issue by AsiaGuy** [IceHacks/SurvivCheatInjector#782]
**Describe the feature you'd like**
As I calculated, when you play in duo, squad or even in ffa, they will corner you by using this method. First, two of them will try to shoot and you will go to their trap. Then, they will form a triangle using bullets and you are stucked in that triangle. After that, they will slowly make that triangle smaller and slowly kill you. You can still shoot them but they can corner you to a barrel and kill you

**Describe alternatives you've considered**
You should fix this before release new version of hacks

**Additional context**
![improve bullets dogde](https://user-images.githubusercontent.com/69104195/139162384-415facba-7df5-43a5-81e2-78132fe72e45.png)

**Comment by IceHacks** [comment]
But it hasn't been implemented. So this post is just theoretical?

**Comment by AsiaGuy** [comment]
yes it is >:)

**Comment by IceHacks** [comment]
Ok
