### ISSUE TITLE
Not able to load to chrome...

### ISSUE THREAD

**Issue by huh-uh** [IceHacks/SurvivCheatInjector#788]
**Describe the bug**
It doesnt let me even load the extension. The error message is saying either that its not able to unzip or that the file is not readable. 

**Expected behavior**
Gets loaded properly

**Screenshots**

**Cheat version**
3.0.6

**Chromium version**
Newest

**Comment by TylerWhat** [comment]
i believe that 3.06 is an app, not an document

**Comment by TylerWhat** [comment]
u should download the 3.06 like this br
![截屏2021-11-04 20 30 19](https://user-images.githubusercontent.com/91678967/140313659-3b41f038-2fe1-4971-b2a6-e1b86cc6aca8.png)



o

**Comment by TylerWhat** [comment]
It is a application, not extensions
bro

**Comment by AsiaGuy** [comment]
close this issue (non-sense)
also watch my videos for full tutorial
https://youtu.be/dGLlLckL2sc

**Comment by russyboy** [comment]
lol using this discussion for advertising

**Comment by russyboy** [comment]
but I like your videos bro
