### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by TheDasani** [IceHacks/SurvivCheatInjector#789]
**Describe the bug**
I have been stuck on the loading screen for about 20 mins now. This is the second time this has happened. I had hoped that by quitting the application, and even redownloading it would fix it. But nope.

**Expected behavior**
I should be able to play through the app

**Screenshots**
![Screenshot from 2021-11-06 23-14-03](https://user-images.githubusercontent.com/93852305/140632144-168816a2-f04d-42f3-818f-b1caf99240f6.png)

*dont hate me if the screenshot doesnt load, this is my first time doing this*

**Cheat version**
3.0.6 Linux

**Comment by AsiaGuy** [comment]
re-install it

**Comment by IceHacks** [comment]
Hey there. That is interesting. I know what type of error is causing that, but sadly I haven't added an error log to that area of the cheat yet. Has this always been happening with 3.0.6 or is it just recently? I suspect it may be the auto-update, as I just published a Linux release 3.0.8. 

Here is that AppImage release, see if this fixes your problems:
https://bit.ly/3qbGuV2

**Comment by TheDasani** [comment]
Yeah, I tried the new AppImage, and that does not work either. I remember that everything worked until restarted the application for the new auto-update. 

Also thanks for getting back with me!

**Comment by IceHacks** [comment]
Ok, thanks for the information. I will look into it further.

**Comment by IceHacks** [comment]
Try clearing the `./config/surviv-cheat/cache` folder

**Comment by IceHacks** [comment]
That should be the fix (I tried to reproduce and that seemed to fix it). If not, let me know. Closing for now.
