### ISSUE TITLE
WHERE THE GOLD (yellow??) MARK OF THE HOUSES WITH P30L FFUUUUUUUU

### ISSUE THREAD

**Issue by muWander** [IceHacks/SurvivCheatInjector#79]
**Describe the bug**
I SEE IT IN PREVIOS VERSIONS AND ITS SOOOOO HELPFUL

**Expected behavior**
idk

**Screenshots**
SHOT IT BY YOUSELF

**Version**
1.1.5

**Comment by IceHacks** [comment]
"shot it by youself" lol Update to 1.1.6
