### ISSUE TITLE
Add enemy laserpointers, useBestGun bug, aimBot being goofy

### ISSUE THREAD

**Issue by Hawkins009** [IceHacks/SurvivCheatInjector#790]
UseBestGun rapidly switches between guns rather than choosing the best. This makes it hard to shoot. I have been forced to play with only one gun to prevent this.

**Comment by IceHacks** [comment]
Woah. Longe title.

**Comment by IceHacks** [comment]
1. Okay, I will see about that getting added back.
2. Try disabling SniperSwitch, this is a known bug that currently won't fix.
3. Any additional details? Try setting the aim multiplier to a lower value (.8 for example)

**Comment by Kithmal123** [comment]
hey guys in icehacks client i cant see loadout button.also the aimbot doesnt work.when i try to shoot with rifle i cant shoot at least a one bullet.idk why .should i chnage seeting to the default?

**Comment by IceHacks** [comment]
> hey guys in icehacks client i cant see loadout button.also the aimbot doesnt work.when i try to shoot with rifle i cant shoot at least a one bullet.idk why .should i chnage seeting to the default?

What are your current settings?

**Comment by minhtq3-a11y** [comment]
my aimbot is goofy, can you help me fix this error and make my aimbot better?
