### ISSUE TITLE
where did Pan hero go + a way to edit my skins in the launcher

### ISSUE THREAD

**Issue by ViridianMoon** [IceHacks/SurvivCheatInjector#792]
i honestly feel like pan hero was really cool, but now if I see a pan I wont pick it up simply because I know its useless, especially as a lategame weapon cuz auto target will just lock onto whatever player there is and wont let me deflect bullets, even if I'm being shot at. i know I can just turn OFF auto shoot, but still, the injector is supposed to make things easier so I guess this feature would be a cool one to re-add. As a side note, its really annoying to have to open my browser and log in to the ad filled normal surviv website if I want to check my xp, pass status and change my loadout. i know this whole injector makes an effort to bring back the old feel of surviv, but for us newer players, I feel like having a little side panel that shows me all that would be great. even if its just a toggle feature, I wouldn't mind. it would just be so handy. thanks!

**Comment by ViridianMoon** [comment]
also, i just remebered, where did the colored icons on the map go? they would identify where the secret stashes of items like the mosin tree or the storm bunker were, which was pretty cool. maybe add those back too?

**Comment by IceHacks** [comment]
Most of the colored map icons were patched. Working on a new UI. Pan hero is planned for readdition. This is not a final version of the cheat, most features will be seen again (even really old ones that were not in 2.X)
