### ISSUE TITLE
Something wrong with the Injector, Maybe.

### ISSUE THREAD

**Issue by ViridianMoon** [IceHacks/SurvivCheatInjector#796]
**Describe the bug**
<-- The cheat will continually fail to find any game, no matter what I try to do. It also gives an "always online" version of the page when I try to log in with google. It fails to load any game even if I restart, end task, or alt-f4. I am not logged in, and using a VPN for a better connection. I have tried switching the VPN too. this didn't work. The website works normally, just not the injector.  A strange thing though, when playing teams, sometimes the modes tab would bug up and put my friends and I into a classic game vs a Woods game. It fixed itself and did not occur often, but would still glitch whenever joining a game.-->

**Expected behavior**
<-- I thought the injector would load like normal. It was working fine just minutes before, and I was even playing squads with some friends. -->

**Screenshots**
![image](https://user-images.githubusercontent.com/81585050/141367416-e3105a93-5b6d-4429-9519-8acd3007b1e9.png)

![image](https://user-images.githubusercontent.com/81585050/141368257-6f21d881-8dc7-4b4d-b34f-f6faef572714.png)

**Cheat version**
<-- 3.08 -->

**Chromium version**
<-- 95.0.4638.69 (Official Build) (64-bit) (cohort: Stable) / (OS) Windows 11 Version Dev (Build 22489.1000) -->

**Comment by iBLiSSIN** [comment]
This thing happen because you have BANNED from Kongrerate

**Comment by ViridianMoon** [comment]
Bruh I'm not even signed in + using a VPN. Should be impossible.

**Comment by IceHacks** [comment]
That is weird. Bans look different (they have IP banned me many times). I'll play around with it tonight and see if I can reproduce.

**Comment by IceHacks** [comment]
I have not looked into it yet, but you could try clearing the application cache. It is in your `%APPDATA%` folder, under SurvivCheat and cache. Hope that helps.

**Comment by ViridianMoon** [comment]
Alright, so i found the cache, (ive dealt with kinda stuff before), and clearing it didn't work. after I restarted, it still gives me a failed finding game. there is a code cache folder though, should I try clearing that one? Also yeah, I was recently banned, but that was a few days ago, and I wasn't even playing on an open ip.

**Comment by ViridianMoon** [comment]
Side note: once i cleared the cache and restarted, I checked again and there is of course new files there, maybe the names of which will help. 
- b00a166e.3.0.8.1 (.cached)
- data_0 (then 1-3)
- then a bunch of f_ files which are preceded by like 4-5 0's, the a 1 or 2 digit number, and maybe a letter, then at the the end an index file.
- for some reason, f_00005a is the largest file in the folder at 5,350 kb. maybe this is relevant, idk. f_00005b is the fourth largest, maybe its something to do with both. again, idk o.O

**Comment by IceHacks** [comment]
Ok, thank you.
