### ISSUE TITLE
cant launch cheat

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#801]
cheat version 2.1.7 browser freeu
![image](https://user-images.githubusercontent.com/71010322/141857220-ec072774-35a3-4f58-8f2e-2a0a302663a3.png)

it thinks the extension is danger but i cant off security of extensions(idk how)

**Comment by JIAJIAPNXA** [comment]
tried use another browsers and 3v cheat and its very laggy and makes aimbot crazy

**Comment by IceHacks** [comment]
> tried use another browsers and 3v cheat and its very laggy and makes aimbot crazy

What are the specs of your machine. I suffer no lag or aim problems.

**Comment by JIAJIAPNXA** [comment]
i think lags happens because surviv io must be on HTML5. On some computers it veeery laggy and surviv io was on flash so long how flash was alive. but on some browsers flash still working... can you make surviv io cheat injector 3.0 on flash?
My vidiocard AMD Radeon HD 6800 Series
Processor AMD Phenom II X4 965

**Comment by IceHacks** [comment]
Surviv.io was never a flash game and it still isn't.

**Comment by IceHacks** [comment]
I am not aware of the browser you are using. Seeing as it isn't officially supported and how the 2.x cheat isn't supported, I will close this.
