### ISSUE TITLE
How To Log Out In IceHacks Client

### ISSUE THREAD

**Issue by PoPCaTLoL** [IceHacks/SurvivCheatInjector#802]
I wanted to switch an account (Google or Facebook) in the client, but the client remembers the previous one, which makes switching accounts a hard task.
Can anyone solve the problem?

**Comment by JIAJIAPNXA** [comment]
try clean browser history this must leave you from your acc but... it will leave from all saved accounts on browser

**Comment by IceHacks** [comment]
Can't you just click your account name and press logout?

**Comment by PoPCaTLoL** [comment]
I can logou

**Comment by PoPCaTLoL** [comment]
I could logout, but when I re-login, it seems to auto-login with the same account.
