### ISSUE TITLE
Variable color / features to determine certain actions or conditions

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#806]
**Describe the feature you'd like**

Determine the aimbot's target.  I think that in 3.0 instead of using a square around the enemy the aimbot is aiming for it would be much better to change the color of the enemy line from `ff0000,0.5` to `ff0000,1`.

**Describe alternatives you've considered**
Add it pls 

**Additional context**
Thanks you for read this things

**Comment by humphreygaming** [comment]
could see this being useful
