### ISSUE TITLE
Some ideas?

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#809]
**Additional context**
https://m.youtube.com/watch?v=bQXqrgWu8PY
Maybe, the features I want to said are:
* Improve mobile movement: allows customizing the radius (when the cursor is moved out of the circle, the mobile movement will be enabled, and if inside, it will be disabled)
* Bullet Dogle video preview (maybe it not important)
* Make a loot plan with line display
* Aim at object in all distance by press a bind (can custom this bind)
* Aim at downed will only enable while have healthy player by press shift or a custom bind 
* With cache tree and cache stone, make it like aim at object but display a more distinctive and clear color 
Hope you care about my ideas 😊

**Comment by russyboy** [comment]
bullet dodge preview???

**Comment by russyboy** [comment]
And if you ask me, I won't play surviv on mobile too

**Comment by iBLiSSIN** [comment]
> And if you ask me, I won't play surviv on mobile too

Hmm, I don’t ask you lol

**Comment by iBLiSSIN** [comment]
And, where is my auto aim pls

**Comment by russyboy** [comment]
> > And if you ask me, I won't play surviv on mobile too
> 
> Hmm, I don’t ask you lol

😂🤣

**Comment by sealvessel** [comment]
Stop auto aim for grenades.

**Comment by iBLiSSIN** [comment]
> Stop auto aim for grenades.

Yes
