### ISSUE TITLE
Extension NOT Working

### ISSUE THREAD

**Issue by BeatsEdge** [IceHacks/SurvivCheatInjector#81]
Hello,

I just got this extension on my Chromobook yesterday and used it 2-3 times. This morning, however, the extension did not work. I showed the menu when I pressed "n" and said the hacker message at the top of the updates. When I went into the game, nothing worked. I included a screenshot of why I think so. The Chromobook just also got updated in between these experiences.
![Screenshot 2019-10-02 at 8 28 02 AM](https://user-images.githubusercontent.com/37675336/66080766-5fcb6e00-e52c-11e9-9536-d60cc96e8450.png)

Thank you,
BeatsEdge

P.S. I am trying this to record a video for my YouTube video on how people hack Surviv.io and just want to say that if you see this and you know me from Surviv.io, don't think I hack... because I don't.

**Comment by IceHacks** [comment]
@BeatsEdge Just refresh extension. And make sure that it loaded correctly (there should be a play button on some lines where the tshirt add normally is).

**Comment by BeatsEdge** [comment]
@IceHacks Ok. I got it. I just re-downloaded it and it worked. I am not pretending otherwise I would not have played for two years... I am trying to make a YT video... BeatsEdge on YT if you want proof.
