### ISSUE TITLE
inverted aim

### ISSUE THREAD

**Issue by Yametekudashai** [IceHacks/SurvivCheatInjector#811]
Add inverted aim

**Comment by iBLiSSIN** [comment]
> Add inverted aim

You are Nguyễn Quang Nhật

**Comment by IceHacks** [comment]
already exists

**Comment by Yametekudashai** [comment]
> > Add inverted aim
> 
> You are Nguyễn Quang Nhật ?

nope, who is nguyen quang nhat?
