### ISSUE TITLE
Zoom feat and better aimbot i miss half my shots even with aimbot

### ISSUE THREAD

**Issue by ETbiz** [IceHacks/SurvivCheatInjector#812]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by humphreygaming** [comment]
Hold CTRL (I think) and scroll up or down to zoom in and out

**Comment by TheTrumpetMan** [comment]
But you dont see further

**Comment by TheTrumpetMan** [comment]
its just unloaded

**Comment by humphreygaming** [comment]
That's the point. Loading occurs server-side, only when you are in a specific range of it, in order to save you from having to load everything. To increase the loaded chunks, ask Kongregate, not us.
