### ISSUE TITLE
Not involve, but … pls read (for IceHacks)

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#814]
I feel surviv.io hack really interesting even though I don't have much experience.  So if you are free, can you teach me about coding?  Thanks for reading

**Comment by iBLiSSIN** [comment]
How to make bumbfire, aimbot and esp in a user script pls?

**Comment by IceHacks** [comment]
> How to make bumbfire, aimbot and esp in a user script pls?

You don't. Unless you want some cheat that you have to rewrite every other day.

**Comment by iBLiSSIN** [comment]
> > How to make bumbfire, aimbot and esp in a user script pls?
> 
> You don't. Unless you want some cheat that you have to rewrite every other day.

I trying to take it from surviv cheat source but it not work :(

**Comment by iBLiSSIN** [comment]
A example (esp hack) from surviv cheat source into a user script

**Comment by iBLiSSIN** [comment]
[Uploading WSBots.zip…](old hack)

**Comment by iBLiSSIN** [comment]
[WSBots.zip](https://github.com/IceHacks/SurvivCheatInjector/files/7792278/WSBots.zip)

**Comment by IceHacks** [comment]
> A example (esp hack) from surviv cheat source into a user script : https://greasyfork.org/vi/scripts/437748-surrviv-io-hack/code

That is not a userscript, it is a plugin for SCI. In SCI, one could create a plugin, send it to me, and have it added to the cheat. (Pan hero for example.)

**Comment by iBLiSSIN** [comment]
> > A example (esp hack) from surviv cheat source into a user script : https://greasyfork.org/vi/scripts/437748-surrviv-io-hack/code
> 
> That is not a userscript, it is a plugin for SCI. In SCI, one could create a plugin, send it to me, and have it added to the cheat. (Pan hero for example.)

Hmm can you make esp cheat in a user script?
