### ISSUE TITLE
Flashlight only works once

### ISSUE THREAD

**Issue by sealvessel** [IceHacks/SurvivCheatInjector#817]
**Describe the bug**
Flashlight only works on first open

**Expected behavior**
Flashlight does not work when you play more than one game. 

**Screenshots**
Flashlgiht does not work. 

**Cheat version**
Latest version. 

**Chromium version**
I use the dmg version.

**Comment by TylerWhat** [comment]
lol

**Comment by TylerWhat** [comment]
same

**Comment by iBLiSSIN** [comment]
Reinstall 3.0.6 and wait for auto update guys

**Comment by IceHacks** [comment]
This bug was already fixed. What version are you using.
