### ISSUE TITLE
A Bug on loading in.

### ISSUE THREAD

**Issue by TBSODedly** [IceHacks/SurvivCheatInjector#818]
**Describe the bug**

I can't load in the game. I'm on chromebook.
**Expected behavior**

I would load in the game?
**Screenshots**

![image](https://user-images.githubusercontent.com/96795510/147603309-fec365c8-12b4-4258-bfdb-c3fbab0b5790.png)

**Cheat version**

**Chromium version**

**Comment by IceHacks** [comment]
Extension no longer supported
