### ISSUE TITLE
long 5 mins

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#819]
the game loading is veery long because it waits something named http://chat-oven.glitch.me/ how to fix it

**Comment by JIAJIAPNXA** [comment]
![image](https://user-images.githubusercontent.com/71010322/147604077-b08e5e4f-598e-4f28-bf52-89d75d1a62f4.png)

**Comment by IceHacks** [comment]
Extension no longer supported
