### ISSUE TITLE
Yo I would want to know how u make the hack 

### ISSUE THREAD

**Issue by jhsjiho** [IceHacks/SurvivCheatInjector#82]
How do u make the hack? is it possible to make one for krunker.io? And, if u have discord, please friend me yee#5017 cause I want to learn further

**Comment by SwitchMe33** [comment]
I wish he would make one for zombsroyale... lol

**Comment by iBLiSSINonYT** [comment]
right sum coad

**Comment by crazylovebots** [comment]
how to use the hack im new

**Comment by IceHacks** [comment]
@crazylovebots Read the instructions in the README.md. That should help you.
