### ISSUE TITLE
Slow Aim Response (v3.0.8)

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#820]
well im not very good at vidio but you still can see how sci v3 works on my pc https://www.youtube.com/watch?v=n9Bin5SFTjM there i have very low fps so aimbot not working correctly. and the icons of weapons have more tight background how can i fix it?

**Comment by JIAJIAPNXA** [comment]
P.S. Same issue on chrome browser looks like game works correctly on browsers with flash integration like chrome flash edition what i using to play surviv io(but it still bad because this browser always crashing)

**Comment by IceHacks** [comment]
> P.S. Same issue on chrome browser looks like game works correctly on browsers with flash integration like chrome flash edition what i using to play surviv io(but it still bad because this browser always crashing) earlier i used yandex browser because there was flash but i needed to download windows 10 now yandex dont have flash and its laggy on it

Surviv has never ran on flash. It has never been a flash game. The perceived and anecdotal difference between your experiences must be caused by another issue.



> well im not very good at vidio but you still can see how sci v3 works on my pc https://www.youtube.com/watch?v=n9Bin5SFTjM there i have very low fps so aimbot not working correctly. and the icons of weapons have more tight background how can i fix it?

I can tell your gameplay is very choppy. It also appears that you have changed some settings with autoattack. Try enabling some performance settings. 

Does disabling everything in the cheat increase your performance?

What are the specs of your machine?

I also notice you are using 3.0.8, the latest version (3.0.9) has had some improvements to the aimbot. To get 3.0.9, download the 3.0.6 release and wait for autoupdate. Autoupdate for 3.0.7, 3.0.8, and 3.0.9 is broken.

**Comment by JIAJIAPNXA** [comment]
AMD Radeon HD 6800 Series vidio
AMD Phenom(tm) II X4 965 Processor 3.40 GHz processor
on SCI V3.0.9 it still lag
2.1.7 sci have same issue on browsers like chrome,egde,yandex,firefox. works correctly on chrome flash edition was correctly working on yandex(but now yandex dont have flash player) i can record gameplay on chrome flash edition.
ah yes. icons of weapons dont have more tight background like in sci. idk why but. its working correctly on browsers with flash (may be)
year ago i didnt had that issue (as i remmember this happened after 3or4 survivor pass release) 
performance settings does nothing for me.

**Comment by IceHacks** [comment]
Remember to press "save" and restart the app to apply performance settings. You might have a small/slow amount of RAM. Surviv is quite a RAM killer. I have not tested the cheat on less than 8GB. The flash chrome is an older chrome version, so it consumes less memory. That would be why you experience smoother gameplay on it. If you have plenty of RAM, I suggest running a RAM check. The cheat uses the latest Chromium APIs for security, but I might see if it works on older versions.

**Comment by JIAJIAPNXA** [comment]
yeah... i think if you make sciv3 based on chrome flash edition version  it will work correctly.
but there is not about chrome. this worked correctly on yandex with flash. when it was in it.
on chrome flash edition i have old icons of weapons what dont have more tight background
now on any browser without flash(may be) icons of weapons have more tight background.

**Comment by IceHacks** [comment]
> it works correctly+looks like i do not need to wait 5 mins its only 5 sec

I assume you are talking about the performance settings. Yes, I improved load times.

> i will try off flash player in chrome flash edition and see how it plays

You shouldn't see a difference

> i have old icons of weapons what dont have more tight background

If you could post screenshots comparing the icons, that would be nice. It could be that because the browser is older, it has less WebGL rendering capabilities.

**Comment by IceHacks** [comment]
It shouldn't be hard to downgrade the chromium version, it also shouldn't have many negative effects. My only thought is that we might already be using a version less than 88. (Meaning we have flash support)

**Comment by JIAJIAPNXA** [comment]
okay ill try post icon with chrome and sci

**Comment by JIAJIAPNXA** [comment]
![image](https://user-images.githubusercontent.com/71010322/147778823-19af0554-c0fa-4f3e-8f7a-88292829f580.png)
1

**Comment by JIAJIAPNXA** [comment]
![image](https://user-images.githubusercontent.com/71010322/147778937-790f5b5c-6c49-425c-b738-9c75069d8938.png)
2

**Comment by JIAJIAPNXA** [comment]
and this is about my browser 
![image](https://user-images.githubusercontent.com/71010322/147779327-fb431658-4340-4ea2-ba1a-e4f56de21b66.png)

**Comment by IceHacks** [comment]
Ok, thank you.

**Comment by JIAJIAPNXA** [comment]
so. can u fix this problem?

**Comment by IceHacks** [comment]
The cheat already uses Chromium 87, which has flash player

**Comment by IceHacks** [comment]
I have downgraded to Chromium 78, similar to the version you are using. It hasn't made a difference for me, but it also hasn't caused any errors. I will keep it at this level.

**Comment by JIAJIAPNXA** [comment]
good can i use it? may be it will fix my problem and i can finally play with 3.0 without problems

**Comment by JIAJIAPNXA** [comment]
i still have this problem how to fix it?

**Comment by IceHacks** [comment]
Just wait for v3.0.10

**Comment by JIAJIAPNXA** [comment]
it works correctly now
