### ISSUE TITLE
opensource

### ISSUE THREAD

**Issue by smartwe** [IceHacks/SurvivCheatInjector#824]
Do you have mind to make this project opensource??
And what's the language of this project??is it electron.js?

**Comment by IceHacks** [comment]
The problem with open source is that then Surviv can patch it easily. Making it useless. It is partially made with Electron, using some of my own things.

**Comment by smartwe** [comment]
ohoh
than if I want do you have mind to share?
I'm curious about injecting on webpages and edit it

**Comment by IceHacks** [comment]
Both Electron and the Chrome Extension API have methods for adding your own scripts, if that is what you want. There might be a tutorial out there to introduce you to Chrome Extensions. I just read the documentation, that might work for you.

https://developer.chrome.com/docs/extensions

**Comment by smartwe** [comment]
do you have discord account?

**Comment by IceHacks** [comment]
iceicebaby#2875

**Comment by smartwe** [comment]
I send friend request

**Comment by smartwe** [comment]
nick is kaizer#3026
