### ISSUE TITLE
grenades

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#827]
**Describe the bug**
nah can't throw grenade when using spinbot

**Expected behavior**
Fix pls

**Screenshots**
not have :c

**Cheat version**
3.0.11

**Comment by iBLiSSIN** [comment]
And where is the pan hero feature lol

**Comment by TylerWhat** [comment]
lol

**Comment by russyboy** [comment]
lol pan hero use v2.1.7 on browser then
