### ISSUE TITLE
make the cheat less extravagant

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#829]
the cheat is very extravagant 3.0.11
i have found much issues
1. aimbot is much worse than in 2.1.7 i won 1/10 (but it may be because all my enemies are total sneaky because all normal people leaved from this game)
2. main problem:auto crate break there is autoclicker for hands i cant off it i guess you can say (im working on that) but this function is very bad or in fight main task break the crate what i can use as cover or it trying to break crate (even if it unbreakable for hands) when i healing or reloading(yeah surviv io is super unbalanced because all of it very long). if you making switch off crate break disable it in cheat to when u will add switch off button i sure no one getting problem with press and hold left mouse button  when they need not when auto crate break ON.
3. underperformance very much functions is very unfinished like sniper switch it switches to next gun and do not care if it automatic weapon in 2.1.7 it switches to hand when u dont have sniper/shotgun when u have is switches to sniper/shotgun.
4.  3.0.11 is WORSE than 2.1.7. only what i likes in 3.0.11 vs 2.1.7 is visual scope scroll and no sniper switch for usas-12 otherwise, it is worse and does not pull for more.

**Comment by iBLiSSIN** [comment]
Same but, for aimbot, you should try to set forwardMultiplier in 0.1 , it will be better

**Comment by TylerWhat** [comment]
yup

but i still believe there have a lot of improve on 3.0.11.

**Comment by JIAJIAPNXA** [comment]
i really sad about 3.0.11 because it worse than 2.1.7 but yeah somewhere its good

**Comment by humphreygaming** [comment]
There is no 3.0.11 yet though?

**Comment by JIAJIAPNXA** [comment]
![Безымянный4](https://user-images.githubusercontent.com/71010322/148364787-f33fa88e-0e13-41e1-bc6e-48e0fef0f21c.png)

**Comment by JIAJIAPNXA** [comment]
![Безымянный4](https://user-images.githubusercontent.com/71010322/148364986-c578a0a3-8470-46e6-b5ac-10345ce06819.png)

**Comment by humphreygaming** [comment]
1. There is nothing wrong with the aimbot, you are just trash at the game
2. Just dodge the crates, boxes, whatever.
3. Just disable some of the autoswitch features then
4. If you have a problem with V3, guess what amazing, revolutionary thing you can do? **Stop using it!** I know, right? If you don't like it and you think it's worse than V2, stick to what is good for you and stop complaining.

**Comment by JIAJIAPNXA** [comment]
achivment unlocked: most angriest person  there.

**Comment by JIAJIAPNXA** [comment]
i didnt said v3 is totally bad and stop calling me trash at this game when i better than you so i guess if i trash in this game you are totally do not know about surviv io?

**Comment by JIAJIAPNXA** [comment]
i just said do not delete old functions or revrite them with better

**Comment by ViridianMoon** [comment]
hey bud.

its his and ice's hack. He can say whatever the hell he wants. your just a user.  nobody asked for your opinion, and the only thing this is here for is to suggest a feature or ask for help. if you think you can do a better job, than go ahead. don't fricking bother people, ok? nobody cares

**Comment by JIAJIAPNXA** [comment]
who cares? if he owns this hack he can disrespect all who he see or what?

**Comment by humphreygaming** [comment]
It's not disrespect, just facts. You aren't entitled to anything, stop

**Comment by ViridianMoon** [comment]
you are correct sir! now, go and whine to your mother about how an internet troll told you that nobody cares about you! have a nice day!

**Comment by JIAJIAPNXA** [comment]
i didnt and your facts are not true i just said 3.0.11 aimbot is worse than 2.1.7. 
and you are totally troll so i cant help your mental stability
so we do not have reasons to talk anyway
(both of you are totally crazy,worse than surviv io players lol)

**Comment by JIAJIAPNXA** [comment]
> you are correct sir! now, go and whine to your mother about how an internet troll told you that nobody cares about you! have a nice day!

with who are you talking

**Comment by humphreygaming** [comment]
> i didnt and your facts are not true i just said 3.0.11 aimbot is worse than 2.1.7.

Which is an obvious lie.

**Comment by JIAJIAPNXA** [comment]
why? i played with 2.1.7. much time now i tried 3.0.11 and get problem with aimbot
i am not saying the 3.0.11 is totally bad i just have found some problems and marked it
whats the problem?

**Comment by JIAJIAPNXA** [comment]
anyway you re not understand me and aggressing. i am good fighter on surviv io but it is not matter when the follow bot will be finished this will be totally devastating and skill will be useless like surviv io. i always hated surviv io because guns and much mechanics was made totally bad. (but hacks made this game more playable for me thats why i still playing this.).

**Comment by IceHacks** [comment]
This is mostly just anecdotes. Come here with actual bugs/issues. Most of the features you have complained about have seen little to no actual change since `2.1.7`. That is why this is closed.

**Comment by sealvessel** [comment]
V3 is vastly better than V2.0. 
Also, autoshoot is at 10fov and forward multi 0.2.
