### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by SwitchMe33** [IceHacks/SurvivCheatInjector#83]
**Describe the bug**
So the older program you had with the dark grayish background, it had a mode where you would only aim if you shot the gun...I loved that, I tried that mode on this one but its not working..

**Expected behavior**
So the older program you had with the dark grayish background, it had a mode where you would only aim if you shot the gun. it was a smooth transition...

**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by u1qqlv** [comment]
I think you mean: shot on click, I remember it was in a older version of the hack. Very nice feature I would like to see again in this hack.

**Comment by IceHacks** [comment]
@u1qqlv @SwitchMe33 I'm sorry but you both are very bad listeners. Every time somebody asks for this back I tell them it is still in the cheat and show them how to enable it. Also please update your cheat if something isn't working.

Disable autoaim and go into binds to change "aim" to the left mouse button.

**Comment by u1qqlv** [comment]
Oh I did not know!!!

**Comment by SwitchMe33** [comment]
> I think you mean: shot on click, I remember it was in a older version of the hack. Very nice feature I would like to see again in this hack.

Yes.. and it was awesome, I loved that feature!

**Comment by SwitchMe33** [comment]
> @u1qqlv @SwitchMe33 I'm sorry but you both are very bad listeners. Every time somebody asks for this back I tell them it is still in the cheat and show them how to enable it. Also please update your cheat if something isn't working.
> 
> Disable autoaim and go into binds to change "aim" to the left mouse button.

Word!  Sorry man but I only been here for a few weeks and haven't seen anyone ask this!  But I will try it out!

**Comment by SwitchMe33** [comment]
> > @u1qqlv @SwitchMe33 I'm sorry but you both are very bad listeners. Every time somebody asks for this back I tell them it is still in the cheat and show them how to enable it. Also please update your cheat if something isn't working.
> > Disable autoaim and go into binds to change "aim" to the left mouse button.
> 
> Word! Sorry man but I only been here for a few weeks and haven't seen anyone ask this! But I will try it out!
To be honest Ive tried it out just now, its not the same as the old one, but when surviv.io bans everyone from using the old hack.. it sucks when you have something great and it gets messed up because of their doings... someone probably reported your hack to them and they blocked it somehow. But I enjoyed your old hack, wish it wasn't messed up. Your the only one as I know that has a decent hack out there for this game, I did have another on another site but they blocked that one somehow too.
