### ISSUE TITLE
Add these features  (reminder)

### ISSUE THREAD

**Issue by ViridianMoon** [IceHacks/SurvivCheatInjector#830]
Put this on to do:

- Configurable bullet and grenade dodge (ie: detection radius, maybe sniper bullet vs auto weapons)
- add a PanHero config like the extension
- Smart bulletdodge
- Toggle for autocrate break
- add a pop-up menu or a drop-down for quests, also something to edit loadout (basically new UI)
- put grenade and bullet dodge in the same drop-down
- make the default roof transparency 0.3 , harder to be caught cheating that way, + you can still see inside
- autoemote compatible with specific emote slot, not just smiley ( I need the trollface)
- smoke transparency toggle:
![image](https://user-images.githubusercontent.com/81585050/148411234-dc297ee7-a24f-4a81-8c47-4c5e95a8efa7.png)
- scroll wheel zoom
- autoloot/bumpfire toggles

**Comment by IceHacks** [comment]
Scroll wheel zoom is already there (hold shift). I don't understand how the roof transparency keeps you from getting caught. Autoemote uses the right emote slot (I believe). You can only use emotes you have in your loadout. Bumpfire toggle is doable. Others either not doable, already in Todo, or not worthwhile.

**Comment by ViridianMoon** [comment]
L
 we really need a guide for this
