### ISSUE TITLE
when did 3.0.12 release? with the following bot

### ISSUE THREAD

**Issue by TylerWhat** [IceHacks/SurvivCheatInjector#832]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TylerWhat** [comment]
:>

:>

:>

**Comment by IceHacks** [comment]
It never has.

**Comment by TylerWhat** [comment]
then when did the following bot function release ?

**Comment by TylerWhat** [comment]
![截屏2022-01-10 19 53 55](https://user-images.githubusercontent.com/91678967/148761982-91613cb6-0cd2-434f-b4f1-ced9c35e1c6e.png)

**Comment by TylerWhat** [comment]
here

**Comment by JIAJIAPNXA** [comment]
![image](https://user-images.githubusercontent.com/71010322/149080072-a87fb383-a842-4cf8-9446-1f5e7fc60bed.png)
well they added wolfbots but my version still do not have it. is "Download for FREE" on this vidio are true?

**Comment by StabbyAlbert** [comment]
> ![image](https://user-images.githubusercontent.com/71010322/149080072-a87fb383-a842-4cf8-9446-1f5e7fc60bed.png)
> well they added wolfbots but my version still do not have it. is "Download for FREE" on this vidio are true?

It’s done but it isn’t released yet, some things like quickswitch doesent work with it.

**Comment by TylerWhat** [comment]
ok

what is wolfbot?

**Comment by JIAJIAPNXA** [comment]
didnt you watched the vidio  what you placed on this issue?

> ok
> 
> what is wolfbot?

**Comment by humphreygaming** [comment]
Build 12 never released

**Comment by TylerWhat** [comment]
> Build 12 never released

?????????????????????????????????????????????????????????????????????????
