### ISSUE TITLE
Hack not working

### ISSUE THREAD

**Issue by yooooooobaby** [IceHacks/SurvivCheatInjector#833]
Im playing on a mac, the app is downloaded, it just wont load me into a game.

Do you know how to fix this?

It says failed joining game.

**Comment by IceHacks** [comment]
Screenshots help!

**Comment by yooooooobaby** [comment]
![Screen Shot 2022-01-11 at 6 22 06 PM](https://user-images.githubusercontent.com/97568431/149047147-d049818e-d63f-4ea9-997b-9728fea479dc.png)

**Comment by yooooooobaby** [comment]
Im connected to wifi and tried different emails/accounts.

**Comment by IceHacks** [comment]
You are using an outdated version. Please install the latest one from the releases.

**Comment by yooooooobaby** [comment]
can you give me a link?

**Comment by yooooooobaby** [comment]
I really appreciate the help and the speed you got back to me. Keep it up

**Comment by IceHacks** [comment]
https://github.com/IceHacks/SurvivCheatInjector/releases/tag/v3.0.10
