### ISSUE TITLE
Flashlight only works on first open on macOS

### ISSUE THREAD

**Issue by sealvessel** [IceHacks/SurvivCheatInjector#834]
**Describe the bug**
After first game, flashlight no longer works. 

**Expected behavior**
It will work for all games. 

**Screenshots**

**Cheat version**
3.0.6

**Chromium version**

**Comment by iBLiSSIN** [comment]
Version 1.8.4?

**Comment by IceHacks** [comment]
What version did you download? Have you installed updates?

**Comment by IceHacks** [comment]
There is no reason that this bug would have anything to do with MacOS and it doesn't happen elsewhere, so I am assuming you are outdated.

**Comment by JIAJIAPNXA** [comment]
xd are you playing on 1.8.4 ver... its even not 2.1.7 looks like this guy downloaded this version from somewhere but not from official github.

**Comment by sealvessel** [comment]
Sorry, meant 3.0.6. I forgot, I pasted wrong number from other game.

**Comment by sealvessel** [comment]
> There is no reason that this bug would have anything to do with MacOS and it doesn't happen elsewhere, so I am assuming you are outdated.

It works on first time only, I think there wa another post on the discussion on 3.0.6 release where flashlight only works first.

**Comment by sealvessel** [comment]
Also tried 3.0.10. Does not work at all, green screen shown.

**Comment by JIAJIAPNXA** [comment]
try 3.0.11 it says green screen fixed. with flashlight may be this is because u have mac.(impressive that u so rich so you can buy MAC)

**Comment by HackerOrPro** [comment]
> Also tried 3.0.10. Does not work at all, green screen shown.

Restart to get the update bro

**Comment by sealvessel** [comment]
> > Also tried 3.0.10. Does not work at all, green screen shown.
> 
> Restart to get the update bro

I restarted. Nothing happened. Anyways, manually got 3.0.11 from the ice god.

**Comment by TylerWhat** [comment]
bruh

**Comment by sealvessel** [comment]
Fixed on 3.0.11

**Comment by TylerWhat** [comment]
> Fixed on 3.0.11

where is 3.0.11?

**Comment by smartwe** [comment]
what is flashlight?
