### ISSUE TITLE
Smoke hack fix 🤔

### ISSUE THREAD

**Issue by iBLiSSIN** [IceHacks/SurvivCheatInjector#836]
The code is here: https://pastebin.com/drt9Emrk

**Comment by JIAJIAPNXA** [comment]
![image](https://user-images.githubusercontent.com/71010322/149466572-453a23e1-cf76-4f57-9e85-81f7da02c354.png)
a?

**Comment by sealvessel** [comment]
^, can't see.

**Comment by IceHacks** [comment]
Link is broken, but smoke hack isn't broken (I just haven't added it back yet). Maybe make a feature request?
