### ISSUE TITLE
zoom hack (shift + scroll)

### ISSUE THREAD

**Issue by smartwe** [IceHacks/SurvivCheatInjector#837]
**Describe the bug**
when use zoom hack it is not rendered

**Expected behavior**
need to be rendered

**Screenshots**
nah I have some situation

**Cheat version**
3.0.11v

**Chromium version**
? nah

**Comment by smartwe** [comment]
huh?

**Comment by iBLiSSIN** [comment]
it impossible to fix

**Comment by smartwe** [comment]
y?
