### ISSUE TITLE
Bullet dodge bullets from outside of screen

### ISSUE THREAD

**Issue by sealvessel** [IceHacks/SurvivCheatInjector#840]
**Describe the bug**
Bullets from outside of screen are not dodged

**Expected behavior**
Dodge them.

**Screenshots**

**Cheat version**
3.0.11

**Chromium version**
3.0.11

**Comment by IceHacks** [comment]
Do you mean bullets you cannot see or bullets that aren't a danger to you.

**Comment by iBLiSSIN** [comment]
hey pls increase radius to dogle sniper bullets because them faster than a ar or smg bullets

**Comment by sealvessel** [comment]
> 

There are so many bullets that come from outside of the screen that I have to dodge manually otherwise I die from a sniper bullet. Bullet dodge radius needs to be increased to estimate the trajectories of bullets and update every quarter second when bullets are detected coming from outside of the screen, otherwise you will get hit. Dodging bullets manually is risky.
