### ISSUE TITLE
Quickswitch won't switch to the gun after switching to melee

### ISSUE THREAD

**Issue by CerealBowl** [IceHacks/SurvivCheatInjector#845]
**Describe the bug**
When combined with autoshoot and useBestGun, quickswitch isn't returning to the gun again after switching to melee, instead I have to switch back to it on my own to make client start shooting again which makes quickswitch pointless

**Expected behavior**
It should switch back to the weapon

**Cheat version**
v3.0.11

**Comment by iBLiSSIN** [comment]
disable the "Equip melee" pls

**Comment by CerealBowl** [comment]
> disable the "Equip melee" pls

why would I lol, also if you don't have any solution or proposition on how to solve the problem why are you even posting there

**Comment by idhygamingsurviv** [comment]
> > disable the "Equip melee" pls
> 
> why would I lol, also if you don't have any solution or proposition on how to solve the problem why are you even posting there

you're not even using it right, it won't automatically switch back if you enable "Equip melee" if you disable equip melee then it'll work

**Comment by IceHacks** [comment]
QuickSwitch is for switching after you fire a shot. UseBestGun is for using the most optimal weapon for the situation. They don't always play nicely because they both want to control your weapon. I suggest using one or the other. This is already in Projects and a noted issue.
