### ISSUE TITLE
Cheats are broken

### ISSUE THREAD

**Issue by hellcat34** [IceHacks/SurvivCheatInjector#846]
i dont know what happend but i was gunna hop on to make some kids mad and this happend.
![Screenshot 2022-01-25 162839](https://user-images.githubusercontent.com/98431330/151070853-580595bd-b849-41c1-9fb6-1d4fa84d9896.png)

**Comment by iBLiSSIN** [comment]
same

**Comment by adi18z** [comment]
same

**Comment by sealvessel** [comment]
same

**Comment by minhtq3-a11y** [comment]
same

**Comment by russyboy** [comment]
yeah i think it is patched

**Comment by russyboy** [comment]
and didn't include loadout page

**Comment by russyboy** [comment]
just have shop

**Comment by IceHacks** [comment]
It's not patched so much as it is broken by chance. I might get around to fixing it this week.

**Comment by Kingkongdara** [comment]
same

**Comment by russyboy** [comment]
> It's not patched so much as it is broken by chance. I might get around to fixing it this week.

thanks

**Comment by russyboy** [comment]
ill play 2.1.7 version on browser then 🤣

**Comment by russyboy** [comment]
its still working tho, if you delete the file and download it again

**Comment by russyboy** [comment]
i just dont know why you guys crashed the cheat

**Comment by JIAJIAPNXA** [comment]
Same problem... strange

**Comment by JIAJIAPNXA** [comment]
i think this issue from surviv io because i lost my long loading of surviv io page it loads in 3 sec. before it was 3 mins

**Comment by TylerWhat** [comment]
same with 3.0.10
but i can still use 3.0.6 to play

**Comment by IceHacks** [comment]
I'll fix it today
