### ISSUE TITLE
Cheats For Chrome OS

### ISSUE THREAD

**Issue by SpuriousCone668** [IceHacks/SurvivCheatInjector#849]
I think that it would be great to have this same cheat easily available for Chrome OS.
I am one of the only people I know that only has a chromebook in my group, and I am unable to download these cheats easily without modifying them and making them unusable. I feel like I've tried enough on this, so I decided to ask the devs of the hack. Thank you for listening!

**Comment by sealvessel** [comment]
no u

**Comment by russyboy** [comment]
you need to change your pc

**Comment by russyboy** [comment]
chrome os isnt for this

**Comment by IceHacks** [comment]
Look up how to install AppImages on ChromeOS
