### ISSUE TITLE
my aimbot is being goofy

### ISSUE THREAD

**Issue by minhtq3-a11y** [IceHacks/SurvivCheatInjector#850]
my aimbot is being goofy. Does anyone know how to make it better?
![image](https://user-images.githubusercontent.com/98383817/153164437-1e2d4511-49eb-4f23-be67-fb5f9af38144.png)

**Comment by russyboy** [comment]
delete it and download it again

**Comment by JIAJIAPNXA** [comment]
what version are you using

**Comment by JIAJIAPNXA** [comment]
use latest version start 3.0.10 i had this problem but it fixed on these versions for me

**Comment by minhtq3-a11y** [comment]
i used 3.0.12

**Comment by IceHacks** [comment]
Why is your forward multiplier so high?

**Comment by minhtq3-a11y** [comment]
so i will put is low???

**Comment by minhtq3-a11y** [comment]
so what should i do now?

**Comment by CerealBowl** [comment]
lower forward multiplier to 0.3 and check whether aimbot is still goofy

**Comment by kaden-tech** [comment]
> Why is your forward multiplier so high?

What does forward multiplier do?
