### ISSUE TITLE
you could use 2.1.7 properly

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#851]
you could delete the 2.1.7 chrome/browser extension, redownload it, then delete cookies or reset browser( not including passwords) , then the cheat 2.1.7 will be working perfectly

**Comment by russyboy** [comment]
it works too good for me, just dont have the new features

**Comment by IceHacks** [comment]
I honestly don't see how that would work. You could probably just do CTRL+F5 on Surviv and achieve the same result
