### ISSUE TITLE
weapon spawner

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#852]
Is it possible to set the chance for breaking a crate and getting a special weapon(m79, awm-s,m4a1-s etc.) to be higher? 
And if we can have a feature of spawning weapons on your spot, it will be fun

**Comment by JIAJIAPNXA** [comment]
well if you talking about this magic... i think 50v50  up for a leader/sniper/medic/bugler is too have something on client side. because i 3x streak got a leader

**Comment by russyboy** [comment]
oof

**Comment by IceHacks** [comment]
No
