### ISSUE TITLE
Im a retard and got banned and i dont want it to happen again. useful feature or not?

### ISSUE THREAD

**Issue by ViridianMoon** [IceHacks/SurvivCheatInjector#853]
you know how theres a "this account is found" popup when you load the page? can you redo that, but put it in the bottom right corner so its not intrusive and make it have a warning saying that if you use an account, you are vulnerable to being reported and so if you plan to play with an account, endorse yourself everyday with a teammate or an alt (and then some sort of disclaimer saying your not responsible). its basically just a reminder for me to not fuck up and be an idiot and i think it wouldnt be too much of a bother, especially if its out of the way

**Comment by russyboy** [comment]
lol

**Comment by IceHacks** [comment]
Comedic. Also, there is this ancient file: https://github.com/IceHacks/SurvivCheatInjector/blob/master/TERMS.md
