### ISSUE TITLE
a green screen, with sprinter rounds perk in the center. nothing works except the player counter. happen both on ver 3.0.10 and 3.0.12

### ISSUE THREAD

**Issue by lefishauchocolat** [IceHacks/SurvivCheatInjector#858]
![image](https://user-images.githubusercontent.com/99778256/154185840-bcc633c7-1cb1-4c34-80a4-d8d6922a6a7e.png)

**Comment by TylerWhat** [comment]
same

**Comment by ViridianMoon** [comment]
Can you please just fuck off?

Here's a usable version of the hack.

If the cheat breaks again, use this.

https://drive.google.com/file/d/1HN11_qSkpMEe-lN-C3E3bJwESu3fuTYU/view?usp=sharing

**Comment by TylerWhat** [comment]
> Can you please just fuck off?
> 
> Here's a usable version of the hack.
> 
> If the cheat breaks again, use this.
> 
> https://drive.google.com/file/d/1HN11_qSkpMEe-lN-C3E3bJwESu3fuTYU/view?usp=sharing

stop swearing 
...

**Comment by TylerWhat** [comment]
and also, the link cannot open for apple computer..... bro

**Comment by ViridianMoon** [comment]
sorry i dont use apple so i guess you'll just have to cope cuz you cant use the hack.

**Comment by idhygamingsurviv** [comment]
> sorry i dont use apple so i guess you'll just have to cope cuz you cant use the hack.
Stop being a rude ass bitch, my guy.

**Comment by sneexy-boi** [comment]
just downgrade to v3.0.6/v3 test build, that version still works

**Comment by sneexy-boi** [comment]
> Can you please just fuck off?
> 
> Here's a usable version of the hack.
> 
> If the cheat breaks again, use this.
> 
> https://drive.google.com/file/d/1HN11_qSkpMEe-lN-C3E3bJwESu3fuTYU/view?usp=sharing

whats with this random google drive link, my man be sharing malware
