### ISSUE TITLE
The "Cannot load Manifest" issue while importing extensions

### ISSUE THREAD

**Issue by Hi1024-github** [IceHacks/SurvivCheatInjector#866]
While importing the iceHacks (newest version) my computer said that it cannot unzip the extension. I unzipped it by myself and it said "cannot load manifest".

**Comment by ViridianMoon** [comment]
It's an exe not an extension. Download and install the program.

**Comment by humphreygaming** [comment]
I will assume "the iceHacks (newest version)" refers to V3.
If so, windows .exe files don't go into chrome://extensions

**Comment by Hi1024-github** [comment]
ex files? how?

**Comment by Hi1024-github** [comment]
exe files*

**Comment by lmssieh** [comment]
> I will assume "the iceHacks (newest version)" refers to V3. If so, windows .exe files don't go into chrome://extensions

any reason for releasing it as a separate program instead of a chrome extension, besides client support ofc.
