### ISSUE TITLE
When  iload in to a hame in just shows the full on hud but cant play

### ISSUE THREAD

**Issue by choclet12311** [IceHacks/SurvivCheatInjector#867]
![Screenshot 2022-02-22 221201](https://user-images.githubusercontent.com/98042038/155228309-8fd76aee-7205-4221-a488-55600c03b9b0.png)

**Comment by 1nnag3** [comment]
Also happening to me

**Comment by FuriouslyRed** [comment]
I think another game update broke the ui... so i guess we might have to wait a few days...

**Comment by sealvessel** [comment]
It broke again
