### ISSUE TITLE
not a bug and not a feature

### ISSUE THREAD

**Issue by Brandon981026** [IceHacks/SurvivCheatInjector#870]
does anyone know how to do this in Chromebook?
maybe the question is pretty dumb but plz tell me.

**Comment by Brandon981026** [comment]
and promise me that it is 100% not harmful

**Comment by humphreygaming** [comment]
V2.1.x is available on just about every platform (except mobile) if you have Developer Mode, in chrome://extensions, enabled
V3 is unofficially available on chromebooks if you have Developer Mode Chrome OS enabled. No full support is promised if you do decide to do odd things with your chromebook though, as it requires installing Linux or something.

If you think it's harmful, take a look at the virustotal scans.
