### ISSUE TITLE
Can you fix the look of it? It's kinda hard to change mode when on a team.

### ISSUE THREAD

**Issue by NopeProsOnly** [IceHacks/SurvivCheatInjector#871]
![image](https://user-images.githubusercontent.com/78925970/155337184-0c222602-8bc1-4601-94c8-cf13ee0db780.png)
The mode change is open. I can't switch because DUO is in the way

**Comment by kaden-tech** [comment]
Can you change the label from bug to feature request?

**Comment by kaden-tech** [comment]
![image](https://user-images.githubusercontent.com/78925970/155801260-f5625ef9-73d1-4ee1-9611-e15949516052.png)
The options are Classic and Woods. I can't see Classic. Can you fix it? @humphreygaming

**Comment by iBLiSSIN** [comment]
yea I fixed this problem
![Screenshot (217)](https://user-images.githubusercontent.com/77667370/158009993-79ccfdc1-54ef-42f3-b638-4d5e2ca227a5.png)
![Screenshot (216)](https://user-images.githubusercontent.com/77667370/158009995-6f5160fa-2235-4421-b6d2-58c2dfab3495.png)
s

**Comment by iBLiSSIN** [comment]
Download the "app.asar", then paste it to `C:\Users\Dell\AppData\Local\Programs\surviv-cheat\resources`
https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/0.0.0

**Comment by IceHacks** [comment]
Did i never push this fix? Oh well.
