### ISSUE TITLE
Remove ads and the thing that says "Remove ads" when spectating

### ISSUE THREAD

**Issue by NopeProsOnly** [IceHacks/SurvivCheatInjector#879]
title

**Comment by kaden-tech** [comment]
![image](https://user-images.githubusercontent.com/78925970/155801717-8c75c297-44e5-4fd2-a7f2-a980ec8d7e86.png)
![image](https://user-images.githubusercontent.com/78925970/155801809-387f808d-71c4-4efc-99d7-1f915136798a.png)
Remove the ad and the stuff.
