### ISSUE TITLE
semi-godmode

### ISSUE THREAD

**Issue by JIAJIAPNXA** [IceHacks/SurvivCheatInjector#887]
i saw very much hackers/glitchers with health bug. when you re shooting they with MP220 full 2 rounds+1 mosin round. and die. when they easily have 42 hp. i think there is a funny glitch what you can do. or explain me how this happened. but do not say that they have good armor. this happens even with 1 lvl armor and helm players.

**Comment by IceHacks** [comment]
Easy answer.

1) they had adrenaline (soda, painkillers, etc.)
2) bullet damage decreases with distance and they don't always do the maximum damage.
