### ISSUE TITLE
i cant use it

### ISSUE THREAD

**Issue by Determined-face** [IceHacks/SurvivCheatInjector#888]
when i open it, it kept showing " . . . ."very long.
it's the latest version

**Comment by JIAJIAPNXA** [comment]
then reopen it i had something like that and reopened. in some of times it fixed

**Comment by Determined-face** [comment]
> then reopen it i had something like that and reopened. in some of times it fixed

I tried many times but it doesn't  work

**Comment by JIAJIAPNXA** [comment]
> > then reopen it i had something like that and reopened. in some of times it fixed
> 
> I tried many times but it doesn't work

then wait more time. drink a coffe or something.

**Comment by russyboy** [comment]
you should configure your browser
just clean cookies or cache with chrome cleaner like cleaner master which you could find on google web extension shop
