### ISSUE TITLE
AutoFight Doesn't work

### ISSUE THREAD

**Issue by Space-Turtle0** [IceHacks/SurvivCheatInjector#89]
**I don't know what happened but all of a sudden the autofight doesn't work. I think I pressed something. but it just stopped.**

**Version**
1.1.7

**Comment by Space-Turtle0** [comment]
Is there a key I press or something? I clicked N and looked. Nothing with autofight was listed under the menu.

**Comment by IceHacks** [comment]
works

**Comment by IceHacks** [comment]
make sure aimbot is on
