### ISSUE TITLE
I can't play

### ISSUE THREAD

**Issue by trung2291** [IceHacks/SurvivCheatInjector#895]
Why the 3.0.14 version is so laggy? I cannot play well

**Comment by JIAJIAPNXA** [comment]
same on browser. looks like... thats it. what all of us going to do. surviv io servers is sick. looks like this wasteland going to be closed.

**Comment by russyboy** [comment]
> Why the 3.0.14 version is so laggy? I cannot play well

i could

**Comment by russyboy** [comment]
just clean the cookies or the cache on your browser or reinstall the .exe file of this cheat then you could play well

**Comment by russyboy** [comment]
because the post 3.0 version used a client side to retrieve info from surviv , and surviv was based on browsers
