### ISSUE TITLE
What is the best way to set up aimbot?

### ISSUE THREAD

**Issue by minhtq3-a11y** [IceHacks/SurvivCheatInjector#897]
**What is the best way to set up aimbot?**

**Comment by russyboy** [comment]
what you mean

**Comment by russyboy** [comment]
you mean on the client side or on browser

**Comment by russyboy** [comment]
in the client the aimbot is already set up

**Comment by minhtq3-a11y** [comment]
i mean browser

**Comment by humphreygaming** [comment]
Not an issue, move it someplace else. Closed.
