### ISSUE TITLE
I can't play on my mac.

### ISSUE THREAD

**Issue by RuleTheRift** [IceHacks/SurvivCheatInjector#898]
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/102222810/159677156-61bdb5e4-c57c-4d57-9c9b-bec22fe06a8d.png">

**Comment by carlni2008** [comment]
Mee too, same problem

**Comment by carlni2008** [comment]
Fixing anytime soon?

**Comment by russyboy1** [comment]
clear browser cache
or find the devs @IceHacks
