### ISSUE TITLE
how to make your cheat not goofy or not working

### ISSUE THREAD

**Issue by russyboy** [IceHacks/SurvivCheatInjector#899]
in many cases ur cheat is not working is because your browser is goofy, you play with surviv and goofed up sth and you crashed your surviv and cant open. surviv post 3.0 versions are used with a client, pre 3.0 versions(like 2.1.7,2.1.6.1) are using a browser extension, so if you hv fixed your browser you could play it smoothly.

clean master could help you clean cache and cookies, which is the most important problem of your cheat to be not working

clean master link: https://chrome.google.com/webstore/detail/clean-master-the-best-chr/eagiakjmjnblliacokhcalebgnhellfi

if ur not using chrome(like me), if ur using opera or opera GX, it should tell u to download a changer for opera to download chrome extensions, just complete it and done, you could clean cache and if will be fine.

**Comment by iBLiSSIN** [comment]
lmao thanks

**Comment by russyboy** [comment]
gg

**Comment by russyboy** [comment]
but did it work

**Comment by russyboy** [comment]
or you dont have anything to deal with the cheat
