### ISSUE TITLE
Client lags a bunch, but its not my internet connection

### ISSUE THREAD

**Issue by sneexy-boi** [IceHacks/SurvivCheatInjector#902]
**Describe the bug**
The client has a lot of lag and surviv puts me in a server that (I assume) also has other users with bad connections and usually has about 2-5 players. Joining vanilla surviv.io in a web browser does not have this problem at all. Including using the old v2 extension, but I wish to use the newer version.

**Expected behavior**
I expect a regular surviv.io experience (with hacks ofc) without any annoying (almost to unplayable) lag/latency and to be connected to the regular server. 

**Cheat version**
v3.0.14

**Comment by iBLiSSIN** [comment]
choose other server pls

**Comment by IceHacks** [comment]
> choose other server pls

^
