### ISSUE TITLE
For the sake of surviv itself and all the pros, streamers, and youtubers that left due to these cheats... please delete icehacks....

### ISSUE THREAD

**Issue by DangerClown** [IceHacks/SurvivCheatInjector#905]
For the sake of surviv itself, and all the pros that love the game but are always dying to people using this cheat plugin without trying to hide it.... please delete icehacks. It may have taken a while to develop, sure.... but for a cheat to be developed for a game by people that never even played the game? seriously... why...? to those that developed this cheat plugin.... do you even realize how much fun you've taken away from surviv? the game had over 10k people during peak time in daytime hours at one point.... i doubt it even has 2000 players worldwide at this point because so many people quit months ago due to the absurd amount of hackers using icehacks.....
This icehacks has ruined the game... more and more people leaving daily.... And I ask, with the best interests of all the pros and streamers and youtubers that suffer due to hackers, at hand, that this hack client for surviv just be deleted... it'd make the game so much more worth playing, all the famous youtubers like Siper, iHASYOU, and the others, would see that there are no more hacks.... and maybe even all the others that quit months ago would come back....
I'd love to see one game I often play not have cheaters literally crashing every twitch stream claiming "its trolling".... not just using blatant aimbot, etc... but stream sniping while using those hacks....

**Comment by DangerClown** [comment]
I couldn't care less if this got deleted... but please take into careful consideration what I said.

**Comment by ViridianMoon** [comment]
Lmao no. Thanks for your opinion tho. If the game is dead, why do you still play it? Just learn to deal.with hackers or quit. Don't need to get mad about it 😜

**Comment by humphreygaming** [comment]
"Deleting" IceHacks would be a crime. Murder is not well looked at by the authorities and is a punishable offense (death or life in prison without parole).

**Comment by DangerClown** [comment]
are you high? seriously what are you talking about? deleting a hack plugin for google chrome isn't a crime...

**Comment by humphreygaming** [comment]
Do your research, IceHacks is not the name of the cheat; it's the name of the person who created it. You can't "delete" a human being.

**Comment by cumnugget** [comment]
nice essay dumbfuck. don't think anyone gives a shit, give up and let a dead game rest. you're actually mentally challenged if you think these hacks are getting deleted. use your brain.

**Comment by DangerClown** [comment]
> nice essay dumbfuck. don't think anyone gives a shit, give up and let a dead game rest. you're actually mentally challenged if you think these hacks are getting deleted. use your brain.

and you're actually mentally challenged if you think hacking on a dead game is fun. use your brain.

**Comment by DangerClown** [comment]
don't be the pot calling the kettle black.

**Comment by russyboy** [comment]
lol little kids saying deleting the cheat

**Comment by russyboy** [comment]
retard

**Comment by russyboy** [comment]
just fuckoff and quit the game then

**Comment by russyboy** [comment]
please go to IceHack's blog to read the intro














































Then you will know IceHacks is a person

**Comment by russyboy** [comment]
just dont fucking argue about this issue

**Comment by DangerClown** [comment]
sorry for a misunderstanding. and i may be a quote on quote "retard" for a misunderstanding on my part. but what is more retarded is you hackers. hacking on a dead game. honestly can we just appreciate the irony of that? you hackers literally hack on a dead ass game and think its fun. honestly you hackers.... thats just something to laugh at because its so fucking absurd. you could do a million other things but you choose to spend all your time sitting in a garbage office chair every day hacking on a dead ass game. thats something only retards would do.

**Comment by DangerClown** [comment]
before calling me a retard, rethink your retarded choices in your sad hopeless life. you won't get anywhere if you choose to sit in an office chair hacking on a dead ass game.

**Comment by ViridianMoon** [comment]
bro most of us are kids still in school or like students in college or uni. nobody maintains this hack, nor does anyone care to delete it. Surviv is a dead game, and the entire playerbase, even those who still play it, know that. Nobody cares to hear your shit about some io game hack that literally everyone uses anyways. Even most pros nowadays use esp or some sort of game glitch. If you really have a problem with the hack, just quit  you dumbass. nobody cares what you do, just leave us  the hell alone.

**Comment by russyboy** [comment]
> before calling me a retard, rethink your retarded choices in your sad hopeless life. you won't get anywhere if you choose to sit in an office chair hacking on a dead ass game.

just quit the game bro fuck off

**Comment by russyboy** [comment]
> 

lol then why u play surviv then, you called it a dead game

**Comment by russyboy** [comment]
just quit the game then it will be fine

**Comment by russyboy** [comment]
if you are still playing it then you suck

**Comment by russyboy** [comment]
> > nice essay dumbfuck. don't think anyone gives a shit, give up and let a dead game rest. you're actually mentally challenged if you think these hacks are getting deleted. use your brain.
> 
> and you're actually mentally challenged if you think hacking on a dead game is fun. use your brain.

just don't play surviv

**Comment by russyboy** [comment]
none of your business on this cheat

**Comment by russyboy** [comment]
and too many people are opening a new github acc just for complaining

**Comment by russyboy** [comment]
you will see it is their first issue ever and quoted joined GitHub this month

**Comment by russyboy** [comment]
as you said surviv is a dead game, just don't fucking play it anymore

**Comment by russyboy** [comment]
consider quitting bro.......... just dont give a fuck

**Comment by JIAJIAPNXA** [comment]
wtf with this one. hey look surviv io is about to be dead game. kongregate can only make skins. i sure this game will never  restart with anticheat and new updates... this is the end of this game. it will be closed when all people will leave from this unbalanced wasteland, so.. play which you can, i do and i always using hacks (even with hacks you still need skill and brain to became the best. and hacks is not only reason why this game dying, creators stopped responding this game with updates. and much players with old and bad PC (like my friend) getting this game veery laggy because of newest browser versions, so for them HTML5 games (like surviv) much laggy my friend is old at this game and still playing this but it may be because of me.(and so if all laggy players gone i think he is strongest laggy player in surviv io).
