### ISSUE TITLE
can't play the game

### ISSUE THREAD

**Issue by moonshineslazy** [IceHacks/SurvivCheatInjector#906]
when i open it up it's just stuck on a screen like this:
![image](https://user-images.githubusercontent.com/95142029/162394807-9b295032-391c-4655-b2e4-0ad4e8386f4b.png)
(it says complete quests to level up in turkish btw)
it worked the first time when i opened the cheat but when i closed it and reopened it it's stuck like this no matter the times i restart
the version is 3.0.13

**Comment by russyboy1** [comment]
update it
it is 3.0.14 now

**Comment by russyboy1** [comment]
if it doesnt work either, clear browser cache
