### ISSUE TITLE
Hacks not working

### ISSUE THREAD

**Issue by WinterCf** [IceHacks/SurvivCheatInjector#91]
**Game freezes after joining about 15-30 seconds in.**
Every time I opened a game recently, the hacks completely dont work, they show the icepacks logo, in smokes etc, however the aim and transparency or anything other than the GUI and things. 
**I would join the game, and then none of my hacks would be on(even after restarting and reinstalling 1.1.7.)** then my game would freeze either on any button press or 15-30 seconds after getting in the game.

<img width="1440" alt="Screen Shot 2019-10-24 at 8 48 22 PM" src="https://user-images.githubusercontent.com/56984777/67535575-41770f00-f6a1-11e9-9592-6605b61c25a2.png"> (frozen in front of enemy)
<img width="1440" alt="Screen Shot 2019-10-24 at 8 47 25 PM" src="https://user-images.githubusercontent.com/56984777/67535576-41770f00-f6a1-11e9-8746-4c0a491dd028.png">
<img width="1440" alt="Screen Shot 2019-10-24 at 8 47 47 PM" src="https://user-images.githubusercontent.com/56984777/67535577-41770f00-f6a1-11e9-9ead-2e001b7eea52.png">
<img width="870" alt="Screen Shot 2019-10-24 at 8 58 58 PM" src="https://user-images.githubusercontent.com/56984777/67535578-420fa580-f6a1-11e9-810e-4633960eb87a.png">
<img width="1072" alt="Screen Shot 2019-10-24 at 8 59 19 PM" src="https://user-images.githubusercontent.com/56984777/67535579-420fa580-f6a1-11e9-9f9c-66509b90e895.png">
<img width="1081" alt="Screen Shot 2019-10-24 at 8 59 34 PM" src="https://user-images.githubusercontent.com/56984777/67535580-420fa580-f6a1-11e9-8622-e19d079d8e0b.png">

**1.1.7**

**Comment by HissingLambo500c** [comment]
The freezing is the anti cheat thing I think

**Comment by IceHacks** [comment]
@WinterCf Try disabling the transparency, I'll check this out tho.

**Comment by WinterCf** [comment]
Yea I think its some kind of anti-cheat based on what the errors are. Appreciate the response

**Comment by IceHacks** [comment]
I found the issue. Shouldn't give any errors, just won't run because it couldn't find the correct values.

**Comment by WinterCf** [comment]
Alright sounds good

**Comment by WinterCf** [comment]
Anything I should do?

**Comment by IceHacks** [comment]
nah, it might take a while to fix tho as I haven't much time already. You could join the discord tho, for updates.

**Comment by WinterCf** [comment]
Link?

**Comment by IceHacks** [comment]
https://discord.gg/rcFcV6

**Comment by IceHacks** [comment]
temporarily fixed
