### ISSUE TITLE
When new version will be released?

### ISSUE THREAD

**Issue by Budloks** [IceHacks/SurvivCheatInjector#911]
its been 2 months and we saw working new version here - https://www.youtube.com/watch?v=mHdUczUrMEo
 please release it

**Comment by ViridianMoon** [comment]
Budlocks my dude, in this video he clearly states everything to do with releasing the next version of the hack. 

My guy, you just need to pay attention and everything will make sense. Im not joking ok, like he address all sorts:
[https://youtu.be/xvFZjo5PgG0](url)
