### ISSUE TITLE
I can't play on Window 11 :( 

### ISSUE THREAD

**Issue by DeleteEarth** [IceHacks/SurvivCheatInjector#916]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**

**Chromium version**

**Comment by russyboy1** [comment]
what
you didnt give any info about it

**Comment by DeleteEarth** [comment]
When I enter the game, my screen does not show the match but is blue with
the items :(

Vào Chủ Nhật, 12 tháng 6, 2022, russyboy1 ***@***.***> đã
viết:

**Comment by russyboy1** [comment]
blue?
it should be green

**Comment by russyboy1** [comment]
should ask the mods @IceHacks

**Comment by russyboy1** [comment]
or clear cache from browser
