### ISSUE TITLE
FİX İT

### ISSUE THREAD

**Issue by LORKKAYRA** [IceHacks/SurvivCheatInjector#917]
**Describe the bug**
I NEEED HELPP
FİXX İT DEVELOPERSSS
**Expected behavior**

**Screenshots**

**Cheat version**

**Chromium version**

**Comment by IceHacks** [comment]
AAAAAAHHHHHHHHH

**Comment by russyboy1** [comment]
you might need to wait until next update, prob. next year or something

**Comment by russyboy1** [comment]
my main acc broke so this is new acc
previously russyboy

**Comment by humphreygaming** [comment]
Can't fix developers, sorry.
