### ISSUE TITLE
Auto Aim not working, 

### ISSUE THREAD

**Issue by sobol3d** [IceHacks/SurvivCheatInjector#92]
**Describe the bug**
The auto loot and the auto aim do not work 
The game also freeze after about 30 second of play
They do have change something to prewent Your Hack
Im using Windows with chrome. 

btw Great job You ddoing here :) regards

**Version**
(ex: 0.8.65)

**Comment by IceHacks** [comment]
Thanks, I'll see if I can fix this

**Comment by gophobic** [comment]
oh god I used to be a pro at this game, until today, I can't even get survive the first 30 seconds

**Comment by IceHacks** [comment]
I am working on a fix. it really isn't that difficult I just haven't the time most of the time.

**Comment by IceHacks** [comment]
Fixed
