### ISSUE TITLE
Button to reset the presets to default and removing presets

### ISSUE THREAD

**Issue by PeaceGodH** [IceHacks/SurvivCheatInjector#920]
Please make a button to remove a preset and also a button to reset it to the default value.

**Comment by russyboy1** [comment]
you mean in the client version?
there was a button on top of the cheat control named reset (i mean revert)

**Comment by russyboy1** [comment]
![image](https://user-images.githubusercontent.com/107330802/183328571-6b313c22-882f-4c42-b013-1dd80d598366.png)
you could see in the official icehacks photo there was three buttons(save, new, revert)
revert could help you
