### ISSUE TITLE
Player count is acting weird

### ISSUE THREAD

**Issue by OsirisUser** [IceHacks/SurvivCheatInjector#922]
Whenever I play on regular surviv.io I usually get 18-30 people in one solo game. However, in ice hacked surviv.io I get 2-4 people in my games. 

I have no clue why this is happening.

**Comment by alany08** [comment]
did kong finally add anticheat?

**Comment by russyboy1** [comment]
lel

**Comment by humphreygaming** [comment]
No idea what this is. If the players are acting oddly (all of them have aimbot or all of them play like mobile players), then you are getting sent to some lobby of sorts. Possibly Kongregate doing something to your connection or the cheat itself sending you to the mobile lobbies, respectively.

**Comment by etechic** [comment]
personally you need to fix the cheat cause i need surviv and its my human rights that you fix surviv cheats

**Comment by humphreygaming** [comment]
Shut the fuck up, Lima
