### ISSUE TITLE
Stuck loading

### ISSUE THREAD

**Issue by IndianaJhones** [IceHacks/SurvivCheatInjector#923]
When ever I click open, I get stuck on a screen that looks like this.
I tried closing and reopening many times.
<img width="1324" alt="Screen Shot 2022-08-27 at 8 00 13 AM" src="https://user-images.githubusercontent.com/112255244/187029270-9c7b4326-1251-4474-80ea-a3385dcebd76.png">
Im playing on a mac.

**Comment by humphreygaming** [comment]
> ...playing on a Mac
There's your first problem.

**Comment by IndianaJhones** [comment]
<img width="1440" alt="Screen Shot 2022-08-30 at 6 37 56 PM" src="https://user-images.githubusercontent.com/112255244/187555753-ede27602-127e-44ff-b2c9-682dfb229ba9.png">
pls help?

**Comment by ghost** [comment]
Same thing is happening to me as well in browser but in some rare occasions it does load up but still it's not working for me as it always stuck in loading.
![2022-09-01](https://user-images.githubusercontent.com/112638646/187935840-202d0aee-b8ab-4054-a2a5-972e0b654880.png)

**Comment by russyboy1** [comment]
lol

**Comment by russyboy1** [comment]
try to clear cache bro

**Comment by russyboy1** [comment]
its much about your browser
CLEAR CACHE

**Comment by russyboy1** [comment]
the cache always makes your game crash bro

**Comment by russyboy1** [comment]
> Same thing is happening to me as well in browser but in some rare occasions it does load up but still it's not working for me as it always stuck in loading. ![2022-09-01](https://user-images.githubusercontent.com/112638646/187935840-202d0aee-b8ab-4054-a2a5-972e0b654880.png)

and i think you shouldn't use browser to play, its fking outdated bro

**Comment by russyboy1** [comment]
> <img alt="Screen Shot 2022-08-30 at 6 37 56 PM" width="1440" src="https://user-images.githubusercontent.com/112255244/187555753-ede27602-127e-44ff-b2c9-682dfb229ba9.png">
> 
> pls help?

dont ever use old version, use client, dont use extension

**Comment by russyboy1** [comment]
how many times do i need to explain to you guys

**Comment by ghost** [comment]
I don't want to download any of that anymore. last time I did it and something went so wrong for no reason at all so I prefer the browser version for me.

**Comment by russyboy1** [comment]
okok

**Comment by russyboy1** [comment]
i want to tell you that browser version was not supported anymore

**Comment by JIAJIAPNXA** [comment]
> > Same thing is happening to me as well in browser but in some rare occasions it does load up but still it's not working for me as it always stuck in loading. ![2022-09-01](https://user-images.githubusercontent.com/112638646/187935840-202d0aee-b8ab-4054-a2a5-972e0b654880.png)
> 
> and i think you shouldn't use browser to play, its fking outdated bro

its old but good. much better game experience than in client version. client hack is worse than browser in almost everything

**Comment by russyboy1** [comment]
clear cache for surviv and it will just fix everything
