### ISSUE TITLE
Don't ask, just do it (how to fix cheat)

### ISSUE THREAD

**Issue by russyboy1** [IceHacks/SurvivCheatInjector#924]
If you are here, you should be finding ways to fix problems like "cheat not working", "cheat stuck on loading screen", "doesnt work" etc

Always heard people saying about cheat not working, they never follow my advice

Again, if you experience game stuck at loading or can't play, **FIRST** clear browser cache. **SECONDLY**, don't use outdated cheat version

**How to clear browser cache:**
opera: opera://settings/siteData
chrome: chrome://settings/siteData
if other browser: just type the browser name and add  ://settings/siteData after the browser name
You will see a "cookies and site data" page, search for surviv.io and clear the cache by simply clicking on the trash bin logo(easy)

**How to download latest version:** 
go to the "releases" page( if you don't know where to find, here is it: https://github.com/IceHacks/SurvivCheatInjector/releases ) and download the latest version (should be v.3.0.13) and most importantly tagged "latest"

If you still cannot solve the problem, discord pm me Aimbot#3734
(humphrey or icehacks pls pin this issue)

**Comment by russyboy1** [comment]
it should be the solution for most of the "stuck loading" problems

**Comment by JIAJIAPNXA** [comment]
2.1.7. much better than 3.0.13 but yeah. there are appears a loading what takes like a 5 mins
