### ISSUE TITLE
Surviv.io Aimbot Shacking

### ISSUE THREAD

**Issue by Gurwinder2** [IceHacks/SurvivCheatInjector#927]
**Hi, whenever i use 2.1.7 aimbot just shakes a lot so the enemy kills me. I cant use 3.0.13 because its very very laggy.**

**Aimbot Shaking A LOT.**

**2.1.7 **

**104.0.5112.110 (Official Build) (64-bit)**

**Comment by russyboy1** [comment]
clear browser cache

**Comment by russyboy1** [comment]
3.0.13 is based on browser, so clear browser cache

**Comment by russyboy1** [comment]
it will DEFINETLY help you

**Comment by russyboy1** [comment]
2.1.7 not supported till a long time ago

**Comment by russyboy1** [comment]
only you could help yourself
clear browser cache

**Comment by russyboy1** [comment]
if you dont know how to clear cache:
chrome://settings/siteData

**Comment by russyboy1** [comment]
if opera: opera://settings/siteData

**Comment by russyboy1** [comment]
and search for "surviv.io", clear surviv's cache

**Comment by russyboy1** [comment]
2.1.7 will be discontinued, as the manifest version 2 will be not supported in 2023, 2.1.7 ver uses manifest verion 2

**Comment by russyboy1** [comment]
dunno if the cheat really uses that

**Comment by russyboy1** [comment]
why people always don't accept my suggestions???

**Comment by russyboy1** [comment]
if clearing cache doesnt work, my bad

**Comment by Gurwinder2** [comment]
Wait thanks but it doesnt fix shaking :( dont worry

**Comment by Gurwinder2** [comment]
Does 3.0.13 if i download it when i open surviv.io on browser will it automatically work on it?

**Comment by russyboy1** [comment]
yes

**Comment by russyboy1** [comment]
oh my god you are the first person to listen to me

**Comment by russyboy1** [comment]
mines shake too, dont worry

**Comment by humphreygaming** [comment]
If V3 lags a lot, that seems like a problem with your pc, not the cheat. Consequently, the lag will cause the aimbot's prediction to go haywire both in V3 and V2.

Or V2 is just broken, as is expected from a **discontinued** product.

**Comment by russyboy1** [comment]
yes yes yes
