### ISSUE TITLE
Get a fucking life faggots, this is practically a mobile game and you can't even get a kill without aimbot lmao

### ISSUE THREAD

**Issue by PinkMonkeyBirdCoder** [IceHacks/SurvivCheatInjector#928]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Cheat version**

**Chromium version**

**Comment by russyboy1** [comment]
really? do you really think surviv is practically a mobile game?

**Comment by russyboy1** [comment]
you still lost to cheats, dont you?

**Comment by russyboy1** [comment]
pro cheat player dont really use cheats tho, they dont rely on aimbots

**Comment by russyboy1** [comment]
we are pro players who played surviv without cheats before, "you cant get a kill without aimbots" ,ha 
surviv is a dead game alr, why dont have some fun?

**Comment by humphreygaming** [comment]
Stop falling for the bait, my guy. This isn't a new thing.

**Comment by kyu-lua** [comment]
Sir please no homophobic slurs as we have many gay members on the icehacks team.

**Comment by russyboy1** [comment]
respect

**Comment by russyboy1** [comment]
> Stop falling for the bait, my guy. This isn't a new thing.

same feeing

**Comment by kyu-lua** [comment]
my discord got banned :( 
-drugaddict

**Comment by PinkMonkeyBirdCoder** [comment]
> Sir please no homophobic slurs as we have many gay members on the icehacks team.

I bet :)
