### ISSUE TITLE
loading...it doesn't work

### ISSUE THREAD

**Issue by hHey28** [IceHacks/SurvivCheatInjector#929]
Humm.. always loading, like this
![屏幕截图 2022-10-15 170410](https://user-images.githubusercontent.com/62040509/195978601-b932f49b-bdaa-4fca-ab34-d67dac9744d4.png)
what should I do?

**Comment by hHey28** [comment]
When I first started it, I got this error
![屏幕截图 2022-10-16 072415](https://user-images.githubusercontent.com/62040509/196011107-56cbaeac-15e6-48d2-8d0f-0e4c9fe46cea.png)

**Comment by russyboy1** [comment]
delete the client and redownload again

**Comment by russyboy1** [comment]
if still doesnt work, clear browser cache

**Comment by russyboy1** [comment]
or watch my post https://github.com/IceHacks/SurvivCheatInjector/issues/924#issue-1361556839

**Comment by hHey28** [comment]
thanks but it still doesnt work

**Comment by hHey28** [comment]
i cleared all the cookies

**Comment by russyboy1** [comment]
redownload

**Comment by russyboy1** [comment]
> When I first started it, I got this error ![屏幕截图 2022-10-16 072415](https://user-images.githubusercontent.com/62040509/196011107-56cbaeac-15e6-48d2-8d0f-0e4c9fe46cea.png)

you are missing a file, you missed a file and could make the whole program crash

**Comment by hHey28** [comment]
I downloaded sci-3.0.13.exe from here : https://github.com/x89-h/x12-update/releases/tag/v3.0.13
and i got this error again

**Comment by hHey28** [comment]
is there anything going wrong with my operating system?
i'm using windows11

**Comment by humphreygaming** [comment]
Using Windows 11 is probably a mistake, to begin with. Regardless, the error being thrown seems like the installer failed to create a "Cache" folder where it usually does (AppData, settings and whatnot go there). Either there is some sort of error with your file access privileges (i.e SCI's installer is unable to access that specific place), the installer has failed.. installing, or it's some Windows 11 thing.
