### ISSUE TITLE
Everything patched.

### ISSUE THREAD

**Issue by xKeksbyte** [IceHacks/SurvivCheatInjector#93]
**Describe the bug**
Currently The cheat got patched, And the anticheat freezes me after 20 seconds not even Esp work.

**Expected behavior**
It should work oof

**Screenshots**
none

**Version**
latest

**Comment by MattKneale** [comment]
Agreed

1.1.7 is broken, the 1.1.8 patch does not resolve the issue either. Menu opens and opens are selectable but no features work. Freezes each time at around 20-30 seconds.

**Comment by DNSGriff** [comment]
Nothing Is working. Can open menu but breezes after about 30 seconds ingame
