### ISSUE TITLE
Is working in 2023?

### ISSUE THREAD

**Issue by alkabane** [IceHacks/SurvivCheatInjector#932]
I tested the windows app its doesn't working..

**Comment by humphreygaming** [comment]
Ice has pretty much abandoned this project, so I wouldn't be surprised if it broke / doesn't work.

**Comment by russyboy1** [comment]
its still working for me

**Comment by alkabane** [comment]
> its still working for me

which link did you download? for me it freezes after a few minutes of play :(

Thanks in advance
