### ISSUE TITLE
I can tell you how to fix it

### ISSUE THREAD

**Issue by RandomComradee** [IceHacks/SurvivCheatInjector#939]
How to fix it. :

                                                                   Change the link and website it uses in the app to survev.io. 
                      Due to Kongregate sunsetting Surviv, Survev is Surviv, but it's a fan website to keep the community going.

 
 
                                                                            I hope you see this and I hope I helped a bit.

**Comment by RandomComradee** [comment]
ill just do it
]

**Comment by aidan-laursen** [comment]
Any idea where to change the website in the app? I've sifted through the app files and couldn't find anything to change. And opening it doesn't show any options for changing it either. using the mac vers btw
