### ISSUE TITLE
функции чита не работают

### ISSUE THREAD

**Issue by arsen1235456** [IceHacks/SurvivCheatInjector#95]
Опишите ошибку. чит не работает вообще все функции не работают.

Ожидаемое поведение. работа функций аим спинбот.

Скриншоты. к сожелению не имеются

Версия (0.8.65)

**Comment by MattKneale** [comment]
WE KNOW!

#92 #93 #91

**Comment by arsen1235456** [comment]
и долго это будет продолжатся?

**Comment by arsen1235456** [comment]
> WE KNOW!
> 
> #92 #93 #91

и долго это будет продолжатся
