### ISSUE TITLE
More info in the new version issue (maybe)

### ISSUE THREAD

**Issue by TheSatanicAngeI** [IceHacks/SurvivCheatInjector#98]
**Describe the bug**
All aim related options aren't working. Game freeze after 30 seconds. 
**Expected behavior**
Everything working just cool as 🍨 
**Errors**
`{activePlayer: {…}, camera: "ne", objectCreator: "Vt", inputManager: "$e", players: {…}, …}
activePlayer: {main: "Gt", netData: "he", localData: false}
bullets: "ft"
camera: "ne"
inputManager: "$e"
loot: {barn: "Ct", pool: "Ft", array: "Ve", active: "ya"}
objectCreator: "Vt"
players: {barn: "yt", info: "_a"}
__proto__: Object`

_There's way more than that but I dont feel like copy pasting 10k lines of text_
**Version**
Chrome : Version 77.0.3865.120 (Build officiel) (64 bits)
Surviv.io : 0.8.65 - October 22, 2019

**Comment by IceHacks** [comment]
I know what's causing it, I just am in school right now :)
