### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by HissingLambo500c** [IceHacks/SurvivCheatInjector#99]
As i am playing i am getting loads of freezing on playing. It didn't do lots at first but now its just constant to the point i cant play for 30 to 50 secs before freezing 

here is me frozen right next to inf ammo perk
![Screenshot (189)](https://user-images.githubusercontent.com/40362091/67613290-bae23080-f779-11e9-8620-b2e3f960fd5c.png)

**Comment by HissingLambo500c** [comment]
And just realized  that the hack stopped working

**Comment by IceHacks** [comment]
I'm trying to find out why

**Comment by TheSatanicAngeI** [comment]
@IceHacks Didn't you said you already knew why ? XD 

👍 I believe in you! You can do it! 🎊

**Comment by santiagorendon** [comment]
Hey yeah expering similar issues

**Comment by santiagorendon** [comment]
Game randomly freezes
here was my error location according to chrome://extension:
background.js:1 (_0x4a3dbe)

maybe the new content from update might be causing it to freeze? not sure.

**Comment by alexvornoffice** [comment]
it freezes BECAUSE of anti-cheat system from surviv.io

**Comment by zbot473** [comment]
Does it freeze without aimbot?

**Comment by IceHacks** [comment]
@alexvornoffice thanks Mr Obvious just trying to find the system I found several already. I think I patched tho, testing. @zbot473 yes

**Comment by IceHacks** [comment]
@TheSatanicAngeI Thanks! When I said that I was talking about another anticheat that I patched which is why you see the freeze only sometimes late in-game.

**Comment by IceHacks** [comment]
I think I fixed please test the new 1.1.9

**Comment by HissingLambo500c** [comment]
Will do

**Comment by xKeksbyte** [comment]
Still freezing & not working

**Comment by lfatal1ty** [comment]
confirm, still freezing

**Comment by HissingLambo500c** [comment]
its not freezing for me

**Comment by ShadoKima** [comment]
It's freezing for me, unfortunately

**Comment by herbieLoaded** [comment]
mine is works perfect. others may not use new patch use 1.1.9 new patch morons

**Comment by lfatal1ty** [comment]
just redownloaded 1.1.9, freezing same

**Comment by gitgitgithubhubhub1** [comment]
fixed for me

**Comment by HissingLambo500c** [comment]
Tho i do miss the zoom lol

**Comment by gitgitgithubhubhub1** [comment]
wait no it froze again

**Comment by ShadoKima** [comment]
Yes it's not working for me, try this modified version and let me know if it works: https://anonfile.com/F5eep99dnc/surviv.ioupdate_rar

**Comment by IceHacks** [comment]
@ShadoKima you can not modify and fix it and the cheat is a zip. Which leads me to believe that was a virus.

**Comment by IceHacks** [comment]
you **all** re-downloaded it right?

**Comment by lfatal1ty** [comment]
> you **all** re-downloaded it right?

yes boss, its still freezing, i tried twice

**Comment by xKeksbyte** [comment]
> you **all** re-downloaded it right?

yep

**Comment by bughitbughit** [comment]
works fine for me, just got a 14 kill solo game rofl

**Comment by HissingLambo500c** [comment]
> you **all** re-downloaded it right?

Yep and i have no isses

**Comment by xKeksbyte** [comment]
Found a fix how to get it working.

Instructions: 
Delete the ext folder, Than new Folder > Paste the new NOT REPLACE IT & it do work XD

**Comment by IceHacks** [comment]
Could be, @xKeksbyte, that people need to refresh the extension but I doubt it. I'll keep playing surviv to see if I run into a freeze

**Comment by alexvornoffice** [comment]
I tried 3 games, and did not freeze

**Comment by friedchicken931** [comment]
game still freezes for me

**Comment by Arytor** [comment]
Updated. Froze the first game near the end.

**Comment by sadisme12** [comment]
freezing in hack version 1.1.9  is not working
confirmed by comentaries comments

**Comment by IceHacks** [comment]
Who wants to try a patch I made?

**Comment by Arytor** [comment]
> Who wants to try a patch I made?

Sure

**Comment by HissingLambo500c** [comment]
I am down to try

**Comment by IceHacks** [comment]
ok
[latest.zip](https://github.com/IceHacks/SurvivCheatInjector/files/3775354/latest.zip)

**Comment by Arytor** [comment]
> ok
> [latest.zip](https://github.com/IceHacks/SurvivCheatInjector/files/3775354/latest.zip)

Froze for me

**Comment by HissingLambo500c** [comment]
Its working completely fine for me

**Comment by bughitbughit** [comment]
not freezing for me. I'm playing asia server if it makes a difference

**Comment by IceHacks** [comment]
gotcha @Arytor try this
[latest.zip](https://github.com/IceHacks/SurvivCheatInjector/files/3775357/latest.zip)

**Comment by Arytor** [comment]
@IceHacks Did one game and worked fine. Gonna keep playing.

**Comment by IceHacks** [comment]
[latest.zip](https://github.com/IceHacks/SurvivCheatInjector/files/3775366/latest.zip)

**Comment by IceHacks** [comment]
I think I'll release that ^ soon as no one has had a freeze in it yet. In my server

**Comment by BaffaroDE** [comment]
Is still freezing 30 seconds after start for me. I deleted all data before trying your hack

**Comment by xKeksbyte** [comment]
BaffaroDE you dint Delete the whole folder, Than remove out of chrome extract it aagain and redrop the folder into extensions

Btw It freezes at almost the end of tha game (only sometimes)

**Comment by IceHacks** [comment]
I see why my changes made it freeze at start again

**Comment by BaffaroDE** [comment]
I mean browserdatas like cache something, then I replaced the old hack with new hack [https://github.com/IceHacks/SurvivCheatInjector/files/3775366/latest.zip](url)

**Comment by IceHacks** [comment]
ye

**Comment by IceHacks** [comment]
ok I believe I just patched for the last time :)

**Comment by santiagorendon** [comment]
@IceHacks where is new patch?

**Comment by sadisme12** [comment]
still frozen .Hack Version 1.1.10 is not working

**Comment by xKeksbyte** [comment]
Ît does retard

**Comment by sadisme12** [comment]
still frozen Again .Hack Version 1.2.0 is not working
